### ISSUE TITLE
PyPI package (install with pip install pyenv)

### ISSUE THREAD

**Issue by obestwalter** [yyuu/pyenv#272]
First things first: **big thumbs up for pyenv :)** for me it takes away the cumbersomeness of switching between Py2 and Py3 and different projects in combination with pyenv-virtualenvwrapper.

I am aware that this is technically not a python Package but I still think it belongs on PyPi and should be pip installable. I am not deeply into Python Packaging myself, as most of the stuff  I do is SAAS, but I would be interested if this is allowed. I am sure it is technically possible and not even very hard to do. Did you look into that already?

The sad state atm is that there is [pyenv package](https://pypi.python.org/pypi/pyenv/0.0.1) by @kennethreitz on PyPi with similar motivation, but it is clearly abandoned as it is pointing to a non existing Github repo. There should be at least a pointer to this project here instead.

**Comment by obestwalter** [comment]
@kennethreitz freed the name on PyPi (thanks Kenneth :) ): https://sourceforge.net/p/pypi/support-requests/441/

For now I registered my fork of the installer there, basically just to secure the name and clarify the intention till it is decided how to move forward with this.

@yyuu I would like to maintain the Python specific wrapper part of the installer. I will think about how to deal best with keeping the two in sync (easiest would be to fetch the newest installer script directly on each install, but that would cause problems for people which use devpi, so the installer bin should somehow be part of the package). 

Another idea would be to merge the wrapper code directly into the main project and maintain it together. I actually like that idea. As it really belongs together. There are just two possible ways to use the installer then. And the code of the shell script and the setup.py stuff do not collide anyway.

Anyway - I will whip my fork into shape over the next few days and go from there.

**Comment by yyuu** [comment]
Great effort :+1:

I think it is better to merge the changes in [obestwalter/pyenv-installer](https://github.com/obestwalter/pyenv-installer) into [yyuu/pyenv-installer](https://github.com/yyuu/pyenv-installer). Plus, I'd like to add you as a collaborator of yyuu/pyenv-installer. How do you think of it?

**Comment by obestwalter** [comment]
Great! I will get the fork into a shape that is not cpmletely embarassing and then I will send you a pull request. Thanks for taking me on board :)

**Comment by obestwalter** [comment]
ok - here it is: https://github.com/yyuu/pyenv-installer/pull/16

@yyuu I released it already from my fork - please let me know if you see any problems. 

The [README](https://pypi.python.org/pypi/pyenv/20150113) still recommends the direct way of installation as I can't guarantee that this will work smoothly and the direct way is the time proven way to do it. 

The necessary --egg parameter is still a major annoyance for me which I couldn't solve yet ... but I'll get there in the end.

**Comment by yyuu** [comment]
Merged yyuu/pyenv-installer#16

**Comment by kirankotari** [comment]
@yyuu There is a way to install the pyenv out site of `python site-packages`, that doesn't need admin privileges. I have ported pyenv for windows with pip install feature.

This is my setup file: https://github.com/pyenv-win/pyenv-win/blob/master/setup.py
Installation steps: `pip install pyenv --target $HOME/.pyenv`
How to get updates from pip: [link](https://github.com/pyenv-win/pyenv-win/blob/master/README.md#how-to-get-updates)
