### ISSUE TITLE
Error with pyenv-version-file-read: line 12: type: write error: Broken pipe

### ISSUE THREAD

**Issue by blueyed** [yyuu/pyenv#294]
When using bup-cron/bup, I've noticed the following output:

    calling command `bup fsck --par2-ok`
    /home/user/.pyenv/libexec/pyenv-version-file-read: line 12: type: write error: Broken pipe
    generating par2(1) recovery blocks

The code is:

    words=( $(cut -b 1-1024 "$VERSION_FILE" | $(type -p gawk awk | head -1) '{ print($1) }') )

Ref: https://github.com/yyuu/pyenv/blob/master/libexec/pyenv-version-file-read#L12

**Comment by yyuu** [comment]
@blueyed Is this still a problem for you?

**Comment by yyuu** [comment]
I'll close this for now. Feel free to reopen if this is still a matter for you.
