### ISSUE TITLE
Using pyenv to switch between two system versions of Python

### ISSUE THREAD

**Issue by hakonhagland** [yyuu/pyenv#297]
Is it possible to have pyenv switch between two system versions of Python? I have recently installed Ubuntu 14.04 on my laptop, and it comes shipped with both python2 (v2.7.6) and python3 (v3.4.0) commands. (And the command python links to python2).

After installing pyenv, and typing pyenv versions it shows only one entry with * system, which is apparently the python2 version..

Do I need to install Python3 with pyenv, in order for it to be able to switch between Python2 and Python3? (I hope it is not necessary since I already have it installed)

Note: I know that I could just type python3 prog.py to run Python3, or I could insert an alias python=python3 in my ~/.bashrc but this is not what I am looking for. I am more interested to have programs with the #! /usr/bin/env python shebang to run with the Python3 interpreter..

Note: This question was first asked at stackoverflow [using-pyenv-to-switch-between-two-system-versions-of-python](http://stackoverflow.com/questions/27603497/using-pyenv-to-switch-between-two-system-versions-of-python).

**Comment by yyuu** [comment]
With `system` version, pyenv will find an executable as same manner as standard shell. Only possible workaround must be `python3 prog.py`. If you'd like to run Python 3.x with `python`, I'd recommend you to install any of Python 3.x inside pyenv.
