### ISSUE TITLE
Homebrew pyenv is good. Now Feature Request or Issue or Just a question...

### ISSUE THREAD

**Issue by tjsoftworks** [yyuu/pyenv#301]
I also had an issues attempting to build various versions. I tried 3.4.2 and others .... 
But I decided to use homebrew to install the versions instead. 
Now the questions is how to "link" or symlink so that pyenv can do it's job 
Is this a question? or a Feature Request or not what pyenv is about ....
Homebrew makes installing of many things easy and one stop. 
I have experience with rbenv so the question becomes how to use pyenv in the best way.

**Comment by yyuu** [comment]
I really don't like feature request without working patch. Basically you don't have to symlink executables. As same as rbenv, pyenv has `system` version and it tries to find `python` executables from `PATH` as same manner as standard shell.
