### ISSUE TITLE
Python 2.4.6 fails to build on OS 10.10

### ISSUE THREAD

**Issue by kormoc** [yyuu/pyenv#302]
Throws the following

		~ > pyenv install 2.4.6
	   Downloading Python-2.4.6.tgz...
	   -> http://python.org/ftp/python/2.4.6/Python-2.4.6.tgz
	   Installing Python-2.4.6...
	   patching file setup.py
	   Hunk #2 succeeded at 239 with fuzz 2 (offset -4 lines).
	   
	   BUILD FAILED (OS X 10.10.1 using python-build 20141028)
	   
	   Inspect or clean up the working tree at /var/folders/kd/fkybt4cs19xgrbg2jtxzxkbh0000gn/T/python-build.20150105205706.30693
	   Results logged to /var/folders/kd/fkybt4cs19xgrbg2jtxzxkbh0000gn/T/python-build.20150105205706.30693.log
	   
	   Last 10 log lines:
	   clang: error: unknown argument: '-mno-fused-madd'
	   make: *** [Parser/parser.o] Error 1
	   make: *** Waiting for unfinished jobs....
	   make: *** [Parser/acceler.o] Error 1
	   make: *** [Parser/parsetok.o] Error 1
	   make: *** [Parser/node.o] Error 1
	   make: *** [Parser/listnode.o] Error 1
	   make: *** [Modules/python.o] Error 1
	   make: *** [Parser/grammar1.o] Error 1
	   make: *** [Parser/bitset.o] Error 1

**Comment by yyuu** [comment]
You would need bunch of extra patches to build ancient versions of CPython on recent OS X.
