### ISSUE TITLE
Can show the download progress bar ？

### ISSUE THREAD

**Issue by iloveyo123u1** [yyuu/pyenv#306]
thank you very much

today ,i install pyenv

i run : pyenv install 3.4.2
---------------------
Downloading Python-3.4.2.tgz...
-> https://yyuu.github.io/pythons/44a3c1ef1c7ca3e4fd25242af80ed72da941203cb4ed1a8c1b724d9078965dd8
------------------

I waited for a long time

It doesn't work ？  i don't know!

not show download progress bar

**Comment by iloveyo123u1** [comment]
qqqq@ubuntu:~/Desktop$ ping yyuu.github.io
PING github.map.fastly.net (103.245.222.133) 56(84) bytes of data.
64 bytes from 103.245.222.133: icmp_req=1 ttl=128 time=119 ms
64 bytes from 103.245.222.133: icmp_req=2 ttl=128 time=70.2 ms
64 bytes from 103.245.222.133: icmp_req=4 ttl=128 time=136 ms
64 bytes from 103.245.222.133: icmp_req=5 ttl=128 time=116 ms
64 bytes from 103.245.222.133: icmp_req=6 ttl=128 time=117 ms
64 bytes from 103.245.222.133: icmp_req=7 ttl=128 time=72.6 ms
64 bytes from 103.245.222.133: icmp_req=8 ttl=128 time=114 ms
64 bytes from 103.245.222.133: icmp_req=9 ttl=128 time=71.6 ms
64 bytes from 103.245.222.133: icmp_req=10 ttl=128 time=121 ms

**Comment by iloveyo123u1** [comment]
I waited for a long time， Don't download success，Can I use the browser to download successful

**Comment by yyuu** [comment]
dupe #267
