### ISSUE TITLE
Use semver to find latest version

### ISSUE THREAD

**Issue by Toilal** [yyuu/pyenv#308]
It's just an idea for now, but it could be handy to use semver to find latest version on some command.

For example, `pyenv install 3.3` could install the latest available version of python 3.3 (3.3.6 for now), and `pyenv install 3` could install the latest available of python3 (3.4.2 for now). Same for `pyenv local/global`.

I want to use pyenv for a continuous integration system, and I would like to avoid hardcoding the python version to use in the build scripts. It's implemented in environment manager for other languages like [nvm](https://github.com/creationix/nvm) (node) and [jenv](https://github.com/gcuisinier/jenv) (java).

**Comment by yyuu** [comment]
Basically, I don't like ambiguous/implicit version specifier. This would be implemented in pyenv plugin, though.

Installing the following script as `$(pyenv root)/pyenv.d/install/sembar.bash` will force pyenv to install `3.3.6` (latest release version) from `pyenv install 3.3`. Though, this doesn't working well with 2.7.x since the first release version of 2.7.x is `2.7`, not `2.7.0`.

```sh
if [ -n "${DEFINITION}" ]; then
  PYTHON_BUILD_INSTALL_PREFIX="${0/*/*}"
  ORIGIFS="${IFS}"
  IFS=: PYTHON_BUILD_DEFINITIONS=($PYTHON_BUILD_DEFINITIONS ${PYTHON_BUILD_ROOT:-$PYTHON_BUILD_INSTALL_PREFIX}/share/python-build)
  IFS="${ORIGIFS}"

  unset FOUND_DEFINITION
  for DEFINITION_DIR in "${PYTHON_BUILD_DEFINITIONS[@]}"; do
    if [ -f "${DEFINITION_DIR}/${DEFINITION}" ]; then
      FOUND_DEFINITION=1
      break
    fi
  done

  if [ -z "${FOUND_DEFINITION}" ]; then
    list_definition_candidates() {
      { for DEFINITION_DIR in "${PYTHON_BUILD_DEFINITIONS[@]}"; do
          if [ -d "${DEFINITION_DIR}" ]; then
            find "${DEFINITION_DIR}" -maxdepth 1 -type f -and -name "${DEFINITION}*" -print0 | xargs -0 -n 1 basename 2>/dev/null
          fi
        done
      } | sort_versions | uniq | remove_unstable_versions
    }

    sort_versions() {
      sed 'h; s/[+-]/./g; s/.p\([[:digit:]]\)/.z\1/; s/$/.z/; G; s/\n/ /' | \
        LC_ALL=C sort -t. -k 1,1 -k 2,2n -k 3,3n -k 4,4n -k 5,5n | awk '{print $2}'
    }

    remove_unstable_versions() {
      sed -e '/-beta[1-9][0-9]$/d' -e '/-dev$/d' -e '/-nightly$/d'  -e '/-src$/d' -e '/rc[1-9][0-9]*$/d'
    }
    DEFINITION_CANDIDATES=($(list_definition_candidates))
    if [ "${#DEFINITION_CANDIDATES[@]}" -gt 1 ]; then
      DEFINITION_CANDIDATE="${DEFINITION_CANDIDATES[${#DEFINITION_CANDIDATES[*]}-1]}"
      echo "pyenv-sembar: use ${DEFINITION_CANDIDATE} for ${DEFINITION}" 1>&2
      DEFINITION="${DEFINITION_CANDIDATE}"
    fi
  fi
fi
```

**Comment by Toilal** [comment]
:+1: Great ! Thanks. 

So is this planned as a new plugin, or not ?

**Comment by yyuu** [comment]
I don't want to publish this as a plugin since I don't have any plans to use this with my installation.... I hope you to maintain your plugin repository if it's possible :grinning: 

https://github.com/yyuu/pyenv/wiki/Authoring-plugins

**Comment by Toilal** [comment]
Ok no problem, i'll try to create a new plugin :) thanks for the code, it really helps as i never write anything in bash !

**Comment by yyuu** [comment]
No more action is needed in this issue.
