### ISSUE TITLE
Add pypy 2.5.0

### ISSUE THREAD

**Issue by alex** [yyuu/pyenv#311]
http://morepypy.blogspot.com/2015/02/pypy-250-released.html

**Comment by alex** [comment]
Awesome :sparkles: thanks!

**Comment by alex** [comment]
Any chance there'll be a release done for this?

**Comment by yyuu** [comment]
i will do release later today. plz wait for awhile....

On Wednesday, February 4, 2015, Alex Gaynor <notifications@github.com>
wrote:

> Any chance there'll be a release done for this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yyuu/pyenv/issues/311#issuecomment-72767491>.
>


-- 
山下 優 (やました ゆう)
peek824545201@gmail.com

**Comment by alex** [comment]
Awesome! Thanks so much for all your hard work.
