### ISSUE TITLE
python installation failed because 'C compiler cannot create executables' (Mac OSX Lion)

### ISSUE THREAD

**Issue by ChrisBail** [yyuu/pyenv#314]
I'm having this issue when trying to instal python 2.6. Here is my log:

/var/folders/r9/771hsm9931sd81ppz31384p80000gn/T/python-build.20150213120811.66272 ~
HTTP/1.1 200 OK

Date: Fri, 13 Feb 2015 11:03:26 GMT

Server: GitHub.com

Content-Type: application/octet-stream

Last-Modified: Tue, 04 Nov 2014 09:32:24 GMT

Expires: Fri, 13 Feb 2015 11:13:24 GMT

Cache-Control: max-age=600

Content-Length: 13285074

Accept-Ranges: bytes

Via: 1.1 varnish

Age: 1

X-Served-By: cache-fra1239-FRA

X-Cache: MISS

X-Cache-Hits: 0

X-Timer: S1423825404.761097,VS0,VE1588

Vary: Accept-Encoding

/var/folders/r9/771hsm9931sd81ppz31384p80000gn/T/python-build.20150213120811.66272/Python-2.6.9 /var/folders/r9/771hsm9931sd81ppz31384p80000gn/T/python-build.20150213120811.66272 ~
checking for --enable-universalsdk... no
checking for --with-universal-archs... 32-bit
checking MACHDEP... darwin
checking EXTRAPLATDIR... $(PLATMACDIRS)
checking machine type as reported by uname -m... x86_64
checking for --without-gcc... no
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/var/folders/r9/771hsm9931sd81ppz31384p80000gn/T/python-build.20150213120811.66272/Python-2.6.9':
configure: error: C compiler cannot create executables
See `config.log' for more details.
make: *** No targets specified and no makefile found.  Stop.

**Comment by yyuu** [comment]
Read the error from your compiler.
