### ISSUE TITLE
Multiple system versions

### ISSUE THREAD

**Issue by simonzack** [yyuu/pyenv#316]
On many linux systems (arch linux, ubuntu), python comes with 2 system versions, 2 & 3. Would it be possible to switch between the two?

I've recently tried to install github's "atom" editor and pyenv is showing me errors that python 2.7 is not installed (despite it being so on the system), which could be related to the build failure.

**Comment by yyuu** [comment]
What's your actual problem? It's possible to use system's `python2` and `python3` if you enabled `system` version in pyenv.

**Comment by simonzack** [comment]
Atom's problem appears to be separate. I'll close this since I don't have other use cases for now.
