### ISSUE TITLE
Completions out of the box like in rbenv

### ISSUE THREAD

**Issue by bucaran** [yyuu/pyenv#320]
Sorry, I didn't have the time to dig in the source to find the answer, I may get around that later, but in the meantime, how come I have to manually `pyenv init...` in order to get completions on OS X, when `rbenv` and `ruby-build` just works out of the box? 

I am on fishell.

> Note: In `rbenv` just like in `pyenv` you do still have to `eval "$(rbenv init -)` in order for stuff to work as expected, e.g, get `gem install <pkg>` to install for the currently global/local version, etc.

**Comment by yyuu** [comment]
I don't have enough time to dig into too. Because there's no significant difference between pyenv and rbenv from the perspective of shell completion configuration, I don't know why only pyenv isn't working well for you. Please let me know again if you find something.

**Comment by bucaran** [comment]
Hey, sorry I forgot to close this. I was using `pyenv` incorrectly. Everything is working smooth as silk.
