### ISSUE TITLE
Issues with zsh and source

### ISSUE THREAD

**Issue by bmcorser** [yyuu/pyenv#321]
Following [the quickstart](http://tmuxp.readthedocs.org/en/latest/cli.html#bash-completion) for tmuxp, I am told to source [this script](https://github.com/tony/tmuxp/blob/master/pkg/tmuxp.zsh).

When I source through pyenv's shim, like this
``` bash
$ source tmuxp.zsh
```
my shell explodes (the window closes). When I source directly, like this
``` bash
$ source .pyenv/versions/2.7.8/bin/tmuxp.zsh
```
I get no errors. When I run the script through pyenv's shim I get some errors:
``` bash
$  tmuxp.zsh
/home/ben/.pyenv/versions/2.7.8/bin/tmuxp.zsh: line 22: autoload: command not found
/home/ben/.pyenv/versions/2.7.8/bin/tmuxp.zsh: line 23: bashcompinit: command not found
```
When I run the script directly (skipping the shim), I get even different errors:
```  bash
$ .pyenv/versions/2.7.8/bin/tmuxp.zsh
.pyenv/versions/2.7.8/bin/tmuxp.zsh: 22: .pyenv/versions/2.7.8/bin/tmuxp.zsh: autoload: not found
.pyenv/versions/2.7.8/bin/tmuxp.zsh: 23: .pyenv/versions/2.7.8/bin/tmuxp.zsh: bashcompinit: not found
.pyenv/versions/2.7.8/bin/tmuxp.zsh: 35: .pyenv/versions/2.7.8/bin/tmuxp.zsh: Syntax error: "(" unexpected (expecting "}")
```

Is pyenv's shimming designed to cope with sourcing scripts in this way?

**Comment by blueyed** [comment]
There is a pending / incomplete PR for this: #100.

Do you feel like picking it up maybe?

**Comment by bmcorser** [comment]
Ah, I searched issues for "source", didn't look into open PRs. I'll see if I can help
