### ISSUE TITLE
Use portable PyPy versions

### ISSUE THREAD

**Issue by BengtOFFIS** [yyuu/pyenv#326]
Currently, pyenv downloads a PyPy binary that is compatible with Ubuntu only on any Linux system. That leads to errors and should be avoided. One way to do this would be to detect the Linux variant and install an appropriate binary. That would however put a lot of burden onto pyenv, because there are a lot of Linux distributions out there and all would need to be detected, a binary version would need to be found and everything maintained. Instead I would suggest to use [the portable PyPy binaries linked at the PyPy Download page](https://github.com/squeaky-pl/portable-pypy). They are only a bit bigger than the source distributions and all errors that occur with them should be reported over at the project portable-pypy.

**Comment by yyuu** [comment]
Sounds interesting. I'd merge if someone sent me a PR, or I may be write it later.

**Comment by BengtOFFIS** [comment]
Thanks for commenting on this. I am glad you like the idea. Sorry, I fear I can not do this myself. I tried but failed to modify the install scripts to download the portable PyPy. If someone wants to give this a shot, there is [a list of all versions of this portable PyPy distribution](https://bitbucket.org/squeaky/portable-pypy/downloads) on BitBucket.

**Comment by olliewalsh** [comment]
> If someone wants to give this a shot

@BengtOFFIS did you miss the pull request I opened a few hours ago?

**Comment by BengtOFFIS** [comment]
Oh, yes, I must have left this tab open. I will have a look at your PR.
