### ISSUE TITLE
SQLite not found when building CPython

### ISSUE THREAD

**Issue by willvousden** [yyuu/pyenv#327]
I'm using Pyenv on a system where I don't have root access.  I therefore installed SQLite from source (`sqlite-autoconf-3080803.tar.gz` on [this page][1]) into `~/local` and invoked `pyenv install` like so:

    export PKG_CONFIG_PATH=$HOME/local/lib/pkgconfig:$PKG_CONFIG_PATH
    CFLAGS="$(pkg-config --cflags sqlite3) $CFLAGS" LDFLAGS="$(pkg-config --libs sqlite3) $LDFLAGS" pyenv install -v 2.7.9

However, the build process doesn't seem to pick up SQLite, and I get the following:

    WARNING: The Python sqlite3 extension was not compiled. Missing the SQLite3 lib?

`pkg-config` gives the following output:

    $ pkg-config --libs sqlite3
    -L/home/spxwv/local/lib -lsqlite3
    $ pkg-config --cflags sqlite3
    -I/home/spxwv/local/include

[1]: http://www.sqlite.org/download.html#amalgtarball

**Comment by yyuu** [comment]
looks weird. I'll try to reproduce later.

**Comment by LanceVan** [comment]
I met same problem while building CPython 3.5.0, my OS is OS X 10.11 El Captain.

According to issue 263, it seems solved after I run following command in terminal:

xcode-select --install

**Comment by AliTajeldin** [comment]
Ran into same issue as original poster.  The solution was to use `CPPFLAGS` instead of `CFLAGS`.  The rest of the command was the same as in the original post.
