### ISSUE TITLE
pyenv: version `3.4.1' is not installed

### ISSUE THREAD

**Issue by xZise** [yyuu/pyenv#330]
Hi I got a strange problem. I've installed 3.4.3 today and removed 3.4.1 and now it complains that it's not installed and I couldn't really understand why. Only after quite some time searching I noticed that in one directory there was still a `.python-version` file.

Maybe add an information why that version was selected (if that is possible)?

**Comment by yyuu** [comment]
If the version is in `.python-version`, it is expected behaviour. `pyenv version` (or `pyenv version-origin`) will show where the currently activated version came from.

**Comment by xZise** [comment]
It wasn't intended as a big report but as a feature request/suggestion.
