### ISSUE TITLE
../libexec/pyenv: no such file or directory

### ISSUE THREAD

**Issue by bbenne10** [yyuu/pyenv#332]
I'm attempting to get started with pyenv, but I'm running into a problem almost immediately upon installation. I'm getting the error referenced in the title whenever I launch `pyenv *`. Upon investigating, it looks like it's expecting `$CWD` to be equal to `$PYENV_ROOT` whenever `pyenv` is run. 

Hoping this was an environment problem that I was running into and not understanding fully, I wanted to make sure that `$PYENV_ROOT` and `$PATH` were what I expected them to be upon running `pyenv init -` in `.zprofile`. What I did was add a printf call to the top of all of my zsh config files to ensure that `.zshenv` was being called prior to `.zprofile`, which it is. I then made sure that the value of `$PYENV_ROOT` was right in `.zprofile`, so I echo'd it and it seems to be correct  (i.e. it points to the cloned directory)

At this point, I'm not sure what expectation I'm violating. I can verify that pyenv will run after I `cd $PYENV_ROOT/bin`, but this is obviously not a good solution. Can anyone point me in the right direction? My zsh initialization files are available [here](http://github.com/bbenne10/dotfiles), though they're not pared down at all. The only ones that should matter though are zshenv and zprofile, which are both extremely small.

**Comment by yyuu** [comment]
I am using pyenv with zsh and it is working fine for me. Fine here means I
can run pyenv outside from $PYENV_ROOT/bin.

I am not 100% sure what is wrong in your zsh configuration but you would be
better to put pyenv configurations in zshenv or zshrc rather than zprofile
because pyenv needed to be sourced into all shell processes you want to
work with it. Actually I'm putting all pyenv stuff in my zshenv.
Because pyenv will work with some of environment variables such like
PYENV_ROOT and PATH, it is very important to have correct values in
environment variables. Please make sure your shell configuration and
running processes are configured properly.



On Monday, March 16, 2015, Bryan Bennett <notifications@github.com> wrote:

> I'm attempting to get started with pyenv, but I'm running into a problem
> almost immediately upon installation. I'm getting the error referenced in
> the title whenever I launch pyenv *. Upon investigating, it looks like
> it's expecting $CWD to be equal to $PYENV_ROOT whenever pyenv is run.
>
> Hoping this was an environment problem that I was running into and not
> understanding fully, I wanted to make sure that $PYENV_ROOT and $PATH
> were what I expected them to be upon running pyenv init - in .zprofile.
> What I did was add a printf call to the top of all of my zsh config files
> to ensure that .zshenv was being called prior to .zprofile, which it is.
> I then made sure that the value of $PYENV_ROOT was right in .zprofile, so
> I echo'd it. It's right.
>
> At this point, I'm not sure what expectation I'm violating. I can verify
> that pyenv will run after I cd $PYENV_ROOT/bin, but this is obviously not
> a good solution. Can anyone point me in the right direction? My zsh
> initialization files are available here
> <https://github.com/bbenne10/dotfiles>, though they're not pared down at
> all. The only ones that should matter though are zshenv and zprofile, which
> are both extremely small.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yyuu/pyenv/issues/332>.
>


-- 
山下 優 (やました ゆう)
peek824545201@gmail.com

**Comment by yyuu** [comment]
FYI, here's the pyenv configuration in my `~/.zshenv`. I'd recommend you to set `PYENV_ROOT` just before invoking `eval "$(pyenv init -)"`.

```sh
if [ -d "$HOME/.pyenv" ]; then
  if [ -d "$HOME/.pyenv/bin" ]; then
    export PATH="$HOME/.pyenv/bin:$PATH"
  else
    export PATH="$HOME/.pyenv/shims:$PATH"
  fi
  if command -v pyenv >/dev/null 2>&1; then
    eval "$(pyenv init - --no-rehash)"
    eval "$(pyenv virtualenv-init -)"
  fi
fi
```

**Comment by bbenne10** [comment]
Let me attempt to pare down my zsh configuration to only pyenv and report back.

**Comment by bbenne10** [comment]
After trying with a bare zsh configuration, this still doesn't work. Steps that I took:
* `for i in $(ls -1 ~/.z*); do rm $i; done`
* `git clone git@github.com:yyuu/pyenv.git ~/.pyenv`
* `pkill dwm` (this kills my entire login session and logs me out so there's no chance that the results are tainted)
* After I log back in, `pyenv`. This reports "permission denied", so...
* `chmod +x ~/.pyenv/bin/pyenv`
* `pyenv`, which gives me `/home/bryan/.pyenv/bin/pyenv: line 1: ../libexec/pyenv: No such file or directory`

I tried essentially the same steps with pyenv_installer as well (though got caught up on the fact that the github page for the installer says to pipe to bash where I needed to pipe to zsh to get the shell detection working properly. This could be fixed by something like curl -L {{url}} | ${SHELL:-/bin/bash}, but I digress)

I'll be honest - I'm not sure how the hell this works for you (or any other zsh user).

**Comment by blueyed** [comment]
@bbenne10 
What is line 1 of `/home/bryan/.pyenv/bin/pyenv` (which is a symlink to `../libexec/pyenv`)?  It should be `#!/usr/bin/env bash`.
I assume you have bash installed?  Can you start it (via `/usr/bin/env bash`)?  Maybe something in the bash startup scripts is broken, regarding the pyenv setup?

Is `bin/pyenv` a symlink for you after all?
Can you run `libexec/pyenv`?

**Comment by bbenne10** [comment]
Interesting. I'm not seeing that `~/.pyenv/bin/pyenv` is a symlink. It's a script with only one line: `../libexec/pyenv`. Running `libexec/pyenv` works fine, but that was to be expected as running `./pyenv` from inside `$PYENV_ROOT/bin` worked (though now I'm curious as to what happens with arguments, as `bin/pyenv` doesn't pass them along at all.

If it's supposed to be a symlink, that makes a lot of sense. I just need to figure out why a git clone isn't recreating that on my side.

**Comment by bbenne10** [comment]
AHHH. For some reason, `git config --list` has `core.symlinks` set to false. This isn't present in my dotfiles (in the repo linked above), so I'm not sure how it got there, but setting it to true makes this work just fine. Sorry for the noise, guys!

**Comment by blueyed** [comment]
The strangest things happen..

I'm glad you figured it out!

**Comment by bgyu** [comment]
Just do this in your **.bash_profile** or **.bashrc**:
``` bash
export PATH="$(pyenv root)/libexec/pyenv:$PATH"
```

**Comment by lyzs90** [comment]
`export PATH="$(pyenv root)/libexec:$PATH"` works for me

**Comment by AnilRedshift** [comment]
FYI if you are on OSX and hit this, you may need to change your shell back to bash:
http://osxdaily.com/2012/03/21/change-shell-mac-os-x/

(or re-set this up to work on zsh)

**Comment by aizkhaj** [comment]
If you use Oh My Zsh on your zsh, I find that you can also enable the `pyenv` plugin.

**Comment by sailist** [comment]
or try this one #1457 by executing `pyenv rehash`

**Comment by kunomaclis** [comment]
> or try this one #1457 by executing `pyenv rehash`

Worked for me in OSX 11.2. Thank you!

**Comment by boatengfrankenstein** [comment]
pyenv was updated and is pointing to an executable that no longer exists.
run
`pyenv rehash`
to resolve the issue

**Comment by p-alik** [comment]
solved the issue by setting `core.symlinks` to `true`
```
✔ ~/git/github/pyenv/pyenv [master|✔] 
17:26 $ git config core.symlinks true
17:26 $ git reset --hard origin/master
17:26 $ pyenv --version
pyenv 2.0.4-8-gd209e061
```

**Comment by ishallbethat** [comment]
export PATH="$(pyenv root)/libexec:$PATH" works for me. I'm using ubuntu

**Comment by kranfnus** [comment]
Got the same error with Git Bash...

**Comment by monicaluodialpad** [comment]
Maybe not relevant, but had similar issue.
```
$ python --version
/Users/monicaluo/.pyenv/shims/python: line 21: /usr/local/Cellar/pyenv/1.2.21/libexec/pyenv: No such file or directory
```

I was able to go inside pyenv root folder and got the python file
```
#!/usr/bin/env bash
set -e
[ -n "$PYENV_DEBUG" ] && set -x

program="${0##*/}"
if [[ "$program" = "python"* ]]; then
  for arg; do
    case "$arg" in
    -c* | -- ) break ;;
    */* )
      if [ -f "$arg" ]; then
        export PYENV_FILE_ARG="$arg"
        break
      fi
      ;;
    esac
  done
fi

export PYENV_ROOT="/Users/monicaluo/.pyenv"
exec "/usr/local/Cellar/pyenv/1.2.21/libexec/pyenv" exec "$program" "$@"
```
On the other hand, I found that I don't have 1.2.21 version of pyenv under `/usr/local/Cellar/pyenv/ `, all I have is 2.*.
So I fix the python file using correct link and try again, it worked.

**Comment by 2784343633** [comment]
just modify the file .pyenv/bin/pyenv: "../libexec/pyenv" to "$PYENV_ROOT/libexec/pyenv"
