### ISSUE TITLE
Link to a specific version of sqlite3 when building Python 3 versions

### ISSUE THREAD

**Issue by cilia** [yyuu/pyenv#333]
Hello,

I used homebrew to install/upgrade `sqlite3` (the database, not the python library), and I want to build a Python 3 using the newer `sqlite3` by homebrew instead of the system wide version by OS X.

I have tried the following:

    env LD_RUN_PATH="/usr/local/opt" LDFLAGS="-L/usr/local/opt" CPPFLAGS="-I/usr/local/include" pyenv install 3.4.3

where `/usr/local/opt` and `/usr/local/include` are the directories where homebrew symlinks the libraries, headers and so on. But it didn't work. The linked `sqlite3` linked by Python 3.4.3 is still the older version that comes with OS X.

My attempt above stems from this: http://stackoverflow.com/questions/26261080/compile-python-3-4-with-sqlite3, and my adaptation to `pyenv` may be wrong.

Any suggestion?

**Comment by cilia** [comment]
Tried the following two alternatives:

    env PYTHON_CONFIGURE_OPTS='LD_RUN_PATH="/usr/local/opt" LDFLAGS="-L/usr/local/opt" CPPFLAGS="-I/usr/local/include"' PYTHON_MAKE_OPTS='LD_RUN_PATH="/usr/local/opt"' pyenv install 3.4.3

and

    export LD_RUN_PATH="/usr/local/opt" LDFLAGS="-L/usr/local/opt" CPPFLAGS="-I/usr/local/include"
    pyenv install 3.4.3

Neither works.

The first failed during the Python build, and the second built successfully but still linked to the wrong `sqlite3` version.

**Comment by danielb2** [comment]
:+1: 

I've got the same issue on FreeBSD

``` bash
$ ls /usr/local/include/sqlite3.h
/usr/local/include/sqlite3.h
```

but ...

```  bash
pyenv install 2.6.9
...
WARNING: The Python sqlite3 extension was not compiled. Missing the SQLite3 lib?
...
```

**Comment by danielb2** [comment]
Found this: 

* `CONFIGURE_OPTS` lets you pass additional options to `./configure`.

**Comment by yyuu** [comment]
You're right. You can use 'CONFIGURE_OPTS' or 'PYTHON_CONFIGURE_OPTS' (only
for python) to pass some options to './configure' at compile time.

On Thursday, March 19, 2015, Daniel Bretoi <notifications@github.com> wrote:

> Found this:
>
>    - CONFIGURE_OPTS lets you pass additional options to ./configure.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yyuu/pyenv/issues/333#issuecomment-83249601>.
>


-- 
山下 優 (やました ゆう)
peek824545201@gmail.com

**Comment by danielb2** [comment]
Yeah, doesn't work though. Options to configure doesn't help it find the path to sqlite3.h. I didn't see any options to configure that would anyway. Do you have suggestions of what to pass?

**Comment by yyuu** [comment]
I cannot remember how CPython tries to find `sqlite3.h`. Please read the impl of CPython.

**Comment by cilia** [comment]
@yyuu What is the difference between 'CONFIGURE_OPTS' or 'PYTHON_CONFIGURE_OPTS' in our case here? I thought only 'PYTHON_CONFIGURE_OPTS' is relevant as we are trying to compile the specific version of sqlite3 into Python.

In addition, is there way in `pyenv` to prefix the `./configure` and `make` commands with options or definitions of variables when building Python?

**Comment by yyuu** [comment]
@cilia `CONFIGURE_OPTS` will be passed to all `./configure`, and `PYTHON_CONFIGURE_OPTS` will be passed only if package name starts from `python`. If you'd like to pass something to `./configure` of CPython, using `PYTHON_CONFIGURE_OPTS` would be the best option.

https://github.com/yyuu/pyenv/blob/e9aa6cf649673e7de416ef7346be19501d096cb1/plugins/python-build/bin/python-build#L668

The packages to be build is depending on the definition of the version. For example, `pyenv install 3.4.3` will build `readline-6.3` and `python-3.4.3` on OS X.

https://github.com/yyuu/pyenv/blob/e9aa6cf649673e7de416ef7346be19501d096cb1/plugins/python-build/share/python-build/3.4.3

**Comment by cilia** [comment]
@yyuu thanks.

Seeing the line of code you referenced, I wonder if there is a way to pass in `PACKAGE_PREFIX_PATH`  or `PREFIX_PATH` variables to `./configure` and `make` during the build?

Based on this: http://stackoverflow.com/questions/8656158/building-python-2-5-with-full-sqlite3-as-a-user-on-linux, those might be what we need here.

**Comment by cilia** [comment]
Found a solution, at least what it works for me.

By only using the `PYTHON_CONFIGURE_OPTS` like the following works:

    PYTHON_CONFIGURE_OPTS="LD_RUN_PATH=/usr/local/opt/sqlite/lib LDFLAGS=-L/usr/local/opt/sqlite/lib CPPFLAGS=-I/usr/local/include" pyenv install 3.4.3

Where `/usr/local/opt/sqlite/lib` is the location of the `sqlite` lib installed by `homebrew`, and `/usr/local/include` is where header files are by `homebrew`.

Hope this helps.

**Comment by techdragon** [comment]
This workaround should probably be turned into some kind of option or configurable.

**Comment by blueyed** [comment]
@techdragon 
Not sure, because `PYTHON_CONFIGURE_OPTS` is the option to configure this in the end.

It is about CPython not finding SQLite.

Are you also / all using homebrew? Then it might be related to how it's (sqlite) installed there maybe?

**Comment by odonnellryan** [comment]
It'd be really nice to be able to do this. SQLite comes with some nifty extensions.

**Comment by cheeming** [comment]
i also encountered some issues, but solved with the following, maybe it can help others.
```bash
LDFLAGS="-L/usr/local/opt/sqlite/lib -L/usr/local/opt/zlib/lib" CPPFLAGS="-I/usr/local/opt/sqlite/include -I/usr/local/opt/zlib/include" pyenv install -v 3.4.5
```

**Comment by aubricus** [comment]
> i also encountered some issues, but solved with the following, maybe it can help others.
> 
> ```shell
> LDFLAGS="-L/usr/local/opt/sqlite/lib -L/usr/local/opt/zlib/lib" CPPFLAGS="-I/usr/local/opt/sqlite/include -I/usr/local/opt/zlib/include" pyenv install -v 3.4.5
> ```

This worked for me on 10.14.2 (Mojave)
