### ISSUE TITLE
pyenv doctor and docs

### ISSUE THREAD

**Issue by tony** [yyuu/pyenv#337]
Hi,

Docs mentions pyenv doctor at https://github.com/yyuu/pyenv/wiki. The gist if a 404 now.

https://github.com/yyuu/pyenv-doctor, when used, looks for ``python-build``. What's the current status with python doctor? When we find out we can update docs accordingly.

**Comment by yyuu** [comment]
Hmm. That was my mistake. I updated the Wiki page.

https://github.com/yyuu/pyenv/wiki/Home/_compare/e7e0bcb%5E...e7e0bcb
