### ISSUE TITLE
Pypy 2.5.1 not appearing?

### ISSUE THREAD

**Issue by kevinburkeshyp** [yyuu/pyenv#342]
I've updated my local repo to the latest master branch, however when I run `pyenv install -l` I do not see pypy-2.5.1 in the resulting list. It looks like it is present in plugins/python-build/share/python-build however. What do I have to do to make it visible/install it? 

Sorry for the trouble.. happy to submit doc fixes or whatever once I figure it out.

**Comment by thomasjo** [comment]
Shows up fine here. Make sure you haven't got pyenv installed via some package manager (e.g. Homebrew) in addition to `~/.pyenv`.

**Comment by kevinburkeshyp** [comment]
Weird.. I had both installed, the version I cloned showed up first in my  PATH, yet somehow the homebrew version was running.

Deleted the homebrew version and now the `pyenv install` command is missing... working through it now.
