### ISSUE TITLE
pyenv fails to load libxml2mod

### ISSUE THREAD

**Issue by sidazad** [yyuu/pyenv#343]
Environment: OS-X Maverick
Python: 2.7.9

A program that used to work has stopped working. The error seems to be in the line import libxml2mod (which is being invoked from import libxml2). The error message is:

```
Fatal Python error: PyThreadState_Get: no current thread
```

When I look in my pyenv python install I am able to see the shared objects for libxml2mod:

```
ls -alt  /Users/sidazad/.pyenv/versions/2.7.9/lib/python2.7/site-packages/libxml2*
-rwxrwxrwx  1 sidazad  staff   483002 Mar 28 00:10 /Users/sidazad/.pyenv/versions/2.7.9/lib/python2.7/site-packages/libxml2.pyc
-rwxrwxrwx@ 1 sidazad  staff   345667 Mar 28 00:10 /Users/sidazad/.pyenv/versions/2.7.9/lib/python2.7/site-packages/libxml2.py
-rwxrwxrwx  1 sidazad  staff  1226632 Mar 28 00:10 /Users/sidazad/.pyenv/versions/2.7.9/lib/python2.7/site-packages/libxml2mod.a
-rwxrwxrwx  1 sidazad  staff     1124 Mar 28 00:10 /Users/sidazad/.pyenv/versions/2.7.9/lib/python2.7/site-packages/libxml2mod.la
-rwxrwxrwx  1 sidazad  staff  2362252 Mar 28 00:10 /Users/sidazad/.pyenv/versions/2.7.9/lib/python2.7/site-packages/libxml2mod.so
Siddharthas-MacBook-Pro-2:libxml2-2.9.2 sidazad$ 
```

It seems as if libxml2mod SO is not able to be loaded. I checked the permissions and they are fine. I am also invoking the correct version of Python.

Any ideas?

**Comment by yyuu** [comment]
I am not sure but it looks like some linkage issue of dynamic loading library. Reinstalling `libxml2` package doesn't help?

https://bitbucket.org/mirror/cpython/src/648dcafa7e5f40da31079bc7a7f0c445f1ea4ab9/Python/pystate.c?at=v2.7.9#cl-330

**Comment by sidazad** [comment]
Hi Yamashita - It was a compilation issue. I was trying to install libxml2 from the source but it seemed to be linking to the default mac osx framework python includes. I was able to solve the problem by temporarily renaming the Framework python include directory to something else and then linking libxml2 and then manually copying over the generated libs (from python setup.py install inside of libxml2/python) into the .pyenv site-packages directory. 
That worked. Phew!

Thanks for the reply though.
