### ISSUE TITLE
OSX: `pyenv which` not finding installed python

### ISSUE THREAD

**Issue by n8henrie** [yyuu/pyenv#348]
New to pyenv. Installed with homebrew today, set `PYENV_ROOT` to `/usr/local/opt/pyenv`, put in the env variables, logged out and back in. Installed python 3.3.6 no problem in addition to my system python 3.4.3.

However, I was hoping the `pyenv which` command would give me a full path, and it doesn't.

```bash
$ pyenv versions
* system (set by /usr/local/opt/pyenv/version)
  3.3.6
$ pyenv which python3.3
pyenv: python3.3: command not found

The `python3.3' command exists in these Python versions:
  3.3.6

$ pyenv which 3.3.6
pyenv: 3.3.6: command not found
```

Tried logging out and in with no result.

3.3.6 seems to be working fine.

```bash
$ ls /usr/local/opt/pyenv/versions
3.3.6
${PYENV_ROOT}/versions/3.3.6/bin/python3.3
Python 3.3.6 (default, Apr  5 2015, 12:18:46) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

Any thoughts?

**Comment by yyuu** [comment]
This is totally expected behaviour since you configured `pyenv global` as `system` in `/usr/local/opt/pyenv/version`.

**Comment by n8henrie** [comment]
Ah, okay. I expected it to output the path to the executable even if that wasn't the active pyenv. Easy enough to implement in a little alias.

    $ function find_pyenv() { find -L ${PYENV_ROOT} -ipath "*/bin/$1"; }
    $ find_pyenv python3.3
    /usr/local/opt/pyenv/versions/3.3.6/bin/python3.3
    $(pyenv which python3) --version
    Python 3.4.3

**Comment by blueyed** [comment]
@n8henrie 
You can also just activate/use multiple versions, e.g.

    pyenv shell 3.4.3:2.7.9:system

This can be added to `/usr/local/opt/pyenv/version` also.

**Comment by n8henrie** [comment]
Awesome! 

When I saw the relevant part of the readme, I assumed this only allowed for a single python3 and a single python2, based on the example.

> NOTE: You can activate multiple versions at the same time, e.g. pyenv global 3.4.2 2.7.8. This allows for parallel usage of python2 and python3, and is required with tools like tox.

Would anyone mind if I updated the readme with an example that makes this more clear? E.g.

```bash
$ pyenv global system 3.3.6 3.2 2.5
$ penv version
system (set by /usr/local/opt/pyenv/version)
3.3.6 (set by /usr/local/opt/pyenv/version)
3.2 (set by /usr/local/opt/pyenv/version)
2.5 (set by /usr/local/opt/pyenv/version)```

**Comment by blueyed** [comment]
> Would anyone mind if I updated the readme with an example that makes this more clear?

:+1: 
Please go ahead!

You might want to include the latest 3.4 and 2.7 versions in there then.
And please use

**Comment by n8henrie** [comment]
And please use...? Did that sentence get cut off?

**Comment by n8henrie** [comment]
https://github.com/yyuu/pyenv/pull/362

**Comment by blueyed** [comment]
> And please use...?

Don't know anymore.. ;)

Thanks for the PR!
