### ISSUE TITLE
pyenv prefix doesn't work with `/bin`

### ISSUE THREAD

**Issue by mskblackbelt** [yyuu/pyenv#349]
As the title suggests, when the system python path is `/bin/python`, the command `pyenv prefix` strips off everything and fails to find the python path. Is there a way to create a workaround for this? I've worked around it by changing my PATH variable, but I believe this is an issue with any Fedora install where `/usr/bin` is symlinked to `/bin` (I believe this is the default behavior for Fedora 20+).

**Comment by yyuu** [comment]
I found that `pyenv-prefix` strips trailing `/bin/*` from `PYTHON_PATH`. This isn't work well if `PYTHON_PATH=/bin/python`.

https://github.com/yyuu/pyenv/blob/71c9ff565be5a7f0a7dd47e84730095a4b6d555e/libexec/pyenv-prefix#L34

Probably same would happen in `rbenv` as well. Good opportunity to send a patch to `rbenv` :octocat:

**Comment by yyuu** [comment]
I don't believe this is common situation.

**Comment by blueyed** [comment]
I had this happening myself, and submitted a. PR for rbenv yesterday.

**Comment by yyuu** [comment]
Please post a link to your PR

**Comment by yyuu** [comment]
And, I am happy if you can work to import recent changes from rbenv.... I'll try to work for ruby-build later.

**Comment by blueyed** [comment]
https://github.com/sstephenson/rbenv/pull/819

**Comment by yyuu** [comment]
subscribed it

**Comment by yyuu** [comment]
@blueyed sstephenson/rbenv#819 is merged by #487
