### ISSUE TITLE
Listing of versions with slash in version name

### ISSUE THREAD

**Issue by blueyed** [yyuu/pyenv#353]
I've tried using `pyenv virtualenv /tmp/foo`, which created the version `tmp/foo` in ~/.pyenv/versions.
This version can be activated using `pyenv shell tmp/foo`.

So far, so good.  But this version is not listed in `pyenv versions` - only `tmp` (the parent directory) is listed there.

This might be considered a feature, given that it allows to not pollute the output of `versions`, but I'd rather have all versions being listed.

(Ref: https://github.com/yyuu/pyenv-virtualenv/issues/5)

**Comment by blueyed** [comment]
When trying to use `pip` in such a version, it fails:

> pyenv: version `tmp/venv-2.7.9-mqO' is not installed

**Comment by blueyed** [comment]
And `pyenv uninstall` omits the `tmp/` part:

> pyenv: remove /home/user/.pyenv/versions/venv-2.7.9-mqO

**Comment by yyuu** [comment]
This feature might be helpful if the user is using `conda` environments will be created in `~/.pyenv/versions/anaconda-X.Y.Z/envs/`. As of pyenv-virtualenv v20150719, it can list `conda` environments by `pyenv virtualenvs`, but `pyenv versions` doesn't show nothing about those environments. Allow nesting structure of versions would introduce complexity to manage versions, though.

**Comment by yyuu** [comment]
After #471, now pyenv can handle virtualenvs in nested directory. At least for now, it only supports virtualenvs inside `envs`, though.
