### ISSUE TITLE
Check for executable might be true (finds shim), while execution fails

### ISSUE THREAD

**Issue by blueyed** [yyuu/pyenv#354]
Usually other programs check for existence of a program by checking if it's executable, e.g. via `if executable("autopep8")` in Vim.

This is true, while the execution itself then might fail:

    % autopep8
    pyenv: autopep8: command not found

    The `autopep8' command exists in these Python versions:
      3.4.3
      2.7.9

The workaround would be to use `pyenv which autopep8`, but that requires changes to the other programs, which could do this:

    prog=$(command -v autopep8)
    if [[ $prog == $PYENV_ROOT/shims/autopep8 ]] && [[ $(command -v pyenv) ]]; then
        prog=$(pyenv which autopep8 2>/dev/null)
    else
        prog=$(command -v autopep8)
    fi

Another workaround would be to also try execution the found command, e.g. with `--help` or `--version`, but this still needs adjustments to the other program/plugin.

Is there a better way to fix pyenv for this use case?

**Comment by yyuu** [comment]
Try running `--help` or `--version` would be the easiest for now.

**Comment by yyuu** [comment]
I think this is a kind of limitation of pyenv's _shims_ approach. Because it's a core of its concept, it is hard to deal with.
