### ISSUE TITLE
Pyenv can't detect the python which had been installed ?

### ISSUE THREAD

**Issue by robot527** [yyuu/pyenv#359]
:~$ which python
/usr/bin/python
:~$ which python3
/usr/bin/python3
:~$ pyenv versions
\* system (set by /home/luoyz/.python-version)

:~$ pyenv version
system (set by /home/luoyz/.python-version)

I must install python by pyenv ?

**Comment by yyuu** [comment]
RTFM

**Comment by blueyed** [comment]
Hint: `which python` should result in the path to pyenv's shim, so you probably have not installed it correctly.

**Comment by yyuu** [comment]
You're a nice guy :stuck_out_tongue_closed_eyes:

**Comment by robot527** [comment]
I'm a newer to pyenv.
My system is Ubuntu 14.10(32bit) .
I want to know that  could I manage multiple versions of Python without using the command " pyenv install x.y.z ".


:~$ pyenv versions
  system
\* 2.7.9 (set by /home/luoyz/.python-version)
:~$ python3
Python 3.4.2 (default, Oct  8 2014, 13:18:07) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by blueyed** [comment]
You should really read the fine manual probably.. :)

> I want to know that could I manage multiple versions of Python without using the command " pyenv install x.y.z ".

Yes, pyenv can use the "system" version, but all others should be installed through pyenv.

What does `which python3` and `which python` give you?
It should point to pyenv's shims for it to have an effect.

`python3` maybe picks up your distribution's version.

**Comment by robot527** [comment]
I see.
Thanks a lot! @blueyed

**Comment by paulochf** [comment]
I'll use this thread since it's the problem pointed in the title.

I'm using pyenv and virtualenvwrapper, don't know what's going on. Trying to change the versions of Python used by a project (below happens inside its folder) with a virtualenv set, but it seems not to work. I  would like some help.

```
$ pyenv versions   
  system
* 2.7 (set by /home/paulo/path/to/project/.python-version)
  2.7.9 
  3.4.3

$ python --version
Python 2.7

$ pyenv local 2.7.9

$ python --version
Python 2.7.9

$ workon proj-env-2.7.9

(proj-env-2.7.9)
$ python --version
Python 2.7.9

(proj-env-2.7.9)
$ pyenv versions   
  system
* 2.7 (set by /home/paulo/path/to/project/.python-version)
  2.7.9 
  3.4.3
```

Thanks!

**Comment by IntelligentFunction** [comment]
Maybe a link to the manual would be useful, as I can't get pyenv to do anything, claims no python is installed at all.

**Comment by IntelligentFunction** [comment]
Found it, ignore me, my eyes don't work the way I thought they did.

**Comment by Jeklah** [comment]
Or better installation instructions. I followed them with no error and am running into this issue.

**Comment by Jeklah** [comment]
> 
> 
> Hint: `which python` should result in the path to pyenv's shim, so you probably have not installed it correctly.

What's a shim?

**Comment by dv-ord** [comment]
I ran into the same issue. As mentioned in the post I went through the installation instructions. However, I followed the steps, but I couldn't figure out what is going wrong. I made post on stackoverflow describing the issue: https://stackoverflow.com/questions/65637759/pyenv-not-picking-up-other-python-installations
