### ISSUE TITLE
pyenv-prefix: support use case to add it to $PATH

### ISSUE THREAD

**Issue by blueyed** [yyuu/pyenv#361]
I find that `PATH="$(pyenv prefix | sed 's/:.*//')/bin:$PATH"` is a good way to improve performance, by adding the current / selected version to the path explicitly.

It would be helpful if `pyenv-prefix` would have an option to help with that, e.g. `--suffix /bin`, which adds that suffix to each entry (in case you have several python versions enabled).

I could also imagine to have a `sh`-script (which would be sourced) to help with that, e.g. `pyenv set-path --suffix /bin`.

What do you think?
Is it too much of a corner-case and against what pyenv tries to itself?

This would be equivalent to the following (zsh) shell script:

    for p in ${(s/:/aO)$(pyenv prefix)}; do path=($p/bin $path); done

(splits by `:` (`s/:/`) and sorts in reverse (`aO`)).

A more advanced (zsh) function:

    pyenv-prefix-to-path () {
        typeset -a prefixes
        local shim_index
        setopt localoptions rcexpandparam
        prefixes=(${(s/:/)$(pyenv prefix)}/bin)
        shim_index=${path[(i)${PYENV_ROOT}/shims*]}
        if (( $shim_index > $#path ))
        then
            echo "No pyenv shims found in path!" >&2
            return 1
        fi
        path=($path[1,$((shim_index-1))] $prefixes $path[$shim_index,-1])
        echo "Added ${(j~:~)prefixes} to PATH."
    }

**Comment by yyuu** [comment]
I'm really sorry for delay :disappointed:

Adding `--suffix` might not be useful for upstream rbenv since they would not need it (only pyenv would need it since it supports multiple versions). I think that this is a kind of corner case. And, I believe it would be better to go for approach like [mislav/anyenv](https://github.com/mislav/anyenv) if the performance of string manipulation is a matter.

**Comment by blueyed** [comment]
Ok, feel free to close it then.

I am fine with my `pyenv-prefix-to-path` function, but still think that a helper might be useful.  But I do not have the time currently to add it.

**Comment by yyuu** [comment]
Okay, I'll close this for now. Anyway thanks for your help improving the performance!
