### ISSUE TITLE
building in an encrypted .encryptfs hits the filename character limit and breaks the build

### ISSUE THREAD

**Issue by sigkill** [yyuu/pyenv#365]
✗ sorting Python versions
   (in test file test/definitions.bats, line 91)
     `touch "${PYTHON_BUILD_ROOT}/share/python-build/$ver"' failed
   touch: cannot touch ‘/home/user/code/pyenv/plugins/python-build/test/tmp/share/python-build/2.7-dev\n2.7\n2.7.1\n2.7.2\n2.7.3\n3.4.0\n3.4-dev\n3.4.1\n3.4.2\njython-dev\njython-2.5.0\njython-2.5-dev\njython-2.5.1\njython-2.5.2\njython-2.5.3\njython-2.5.4-rc1\njython-2.7-beta1\njython-2.7-beta2\njython-2.7-beta3’: File name too long

---

93 tests, 1 failure
make: *** [test] Error 1

Work around is to put the pyenv in a non-encrypted dir, but just wanted to put this in as an issue as there might be a better way to handle the issue.

**Comment by blueyed** [comment]
The problem with the test failure appears to be that the versions are not split correctly.

They should be `touch`ed one by one, not as a whole.

How did you run the tests?

**Comment by blueyed** [comment]
And what shell are you using?

**Comment by blueyed** [comment]
AFAIK `bats` should use `bash`.  Do you have symlinked this to `zsh` or something like that?

**Comment by sigkill** [comment]
Using bash on Ubuntu 14.04 LTS - I can re-run with more output.

I can confirm that as soon as I moved the directory / complete git clone of this project out of my encrypted home dir I was able to run make successfully under the same shell.

"root@kilgore:/tmp/PYTHON_BUILD_ROOT/pyenv# chsh
Changing the login shell for root
Enter the new value, or press ENTER for the default
        Login Shell [/bin/bash]:"

As root in the user dir:
root@kilgore:/home/user/code/pyenv# make
PATH="./bats/bin:$PATH" test/run
 ✓ commands
 ✓ commands --sh
 ✓ commands in path with spaces
 ✓ commands --no-sh
 ✓ command with no completion support
 ✓ command with completion support
 ✓ forwards extra arguments
 ✓ fails with invalid version
 ✓ completes with names of executables
 ✓ supports hook path with spaces
 ✓ carries original IFS within hooks
 ✓ forwards all arguments
 ✓ supports python -S <cmd>
 ✓ default
 ✓ read PYENV_ROOT/version
 ✓ set PYENV_ROOT/version
 ✓ fail setting invalid PYENV_ROOT/version
 ✓ without args shows summary of common commands
 ✓ invalid command
 ✓ shows help for a specific command
 ✓ replaces missing extended help with summary text
 ✓ extracts only usage
 ✓ multiline usage section
 ✓ multiline extended help section
 ✓ prints usage help given no argument
 ✓ prints list of hooks
 ✓ supports hook paths with spaces
 ✓ resolves relative paths
 ✓ resolves symlinks
 ✓ creates shims and versions directories
 ✓ auto rehash
 ✓ setup shell completions
 ✓ detect parent shell
 ✓ setup shell completions (fish)
 ✓ fish instructions
 ✓ option to skip rehash
 ✓ adds shims to PATH
 ✓ adds shims to PATH (fish)
 ✓ can add shims to PATH more than once
 ✓ doesn't add shims to PATH more than once (fish)
 ✓ outputs sh-compatible syntax
 ✓ outputs fish-specific syntax (fish)
 ✓ no version
 ✓ local version
 ✓ supports legacy .pyenv-version file
 ✓ local .python-version has precedence over .pyenv-version
 ✓ ignores version in parent directory
 ✓ ignores PYENV_DIR
 ✓ sets local version
 ✓ changes local version
 ✓ renames .pyenv-version to .python-version
 ✓ doesn't rename .pyenv-version if changing the version failed
 ✓ unsets local version
 ✓ unsets alternate version file
 ✓ prefix
 ✓ prefix for invalid version
 ✓ prefix for system
 ✓ prefix for invalid system
 ✓ blank invocation
 ✓ invalid command
 ✓ default PYENV_ROOT
 ✓ inherited PYENV_ROOT
 ✓ default PYENV_DIR
 ✓ inherited PYENV_DIR
 ✓ invalid PYENV_DIR
 ✓ adds its own libexec to PATH
 ✓ adds plugin bin dirs to PATH
 ✓ PYENV_HOOK_PATH preserves value from environment
 ✓ PYENV_HOOK_PATH includes pyenv built-in plugins
 ✓ empty rehash
 ✗ non-writable shims directory
   (from function `flunk' in file test/test_helper.bash, line 36,
    from function `assert_failure' in file test/test_helper.bash, line 49,
    in test file test/rehash.bats, line 24)
     `assert_failure "pyenv: cannot rehash: ${PYENV_ROOT}/shims isn't writable"' failed
   expected failed exit status
 ✓ rehash in progress
 ✓ creates shims
 ✓ removes stale shims
 ✓ binary install locations containing spaces
 ✓ carries original IFS within hooks
 ✓ sh-rehash in bash
 ✓ sh-rehash in fish
 ✓ no shell version
 ✓ shell version
 ✓ shell version (fish)
 ✓ shell unset
 ✓ shell unset (fish)
 ✓ shell change invalid version
 ✓ shell change version
 ✓ shell change version (fish)
 ✓ no shims
 ✓ shims
 ✓ shims --short
 ✓ default version
 ✓ reads version from git repo
 ✓ prints default version if no tags in git repo
 ✓ no version selected
 ✓ set by PYENV_VERSION
 ✓ set by local file
 ✓ set by global file
 ✓ prints global file if no version files exist
 ✓ detects 'global' file
 ✓ detects 'default' file
 ✓ 'version' has precedence over 'global' and 'default'
 ✓ in current directory
 ✓ legacy file in current directory
 ✓ .python-version has precedence over legacy file
 ✓ in parent directory
 ✓ topmost file has precedence
 ✓ legacy file has precedence if higher
 ✓ PYENV_DIR has precedence over PWD
 ✓ PWD is searched if PYENV_DIR yields no results
 ✓ fails without arguments
 ✓ fails for invalid file
 ✓ fails for blank file
 ✓ reads simple version file
 ✓ ignores leading spaces
 ✓ reads only the first word from file
 ✓ loads *not* only the first line in file
 ✓ ignores leading blank lines
 ✓ handles the file with no trailing newline
 ✓ ignores carriage returns
 ✓ invocation without 2 arguments prints usage
 ✓ setting nonexistent version fails
 ✓ writes value to arbitrary file
 ✓ no version selected
 ✓ system version is not checked for existance
 ✓ PYENV_VERSION has precedence over local
 ✓ local file has precedence over global
 ✓ missing version
 ✓ version with prefix in name
 ✓ reports global file even if it doesn't exist
 ✓ detects global file
 ✓ detects PYENV_VERSION
 ✓ detects local file
 ✓ detects alternate version file
 ✓ no versions installed
 ✓ not even system python available
 ✓ bare output no versions installed
 ✓ single version installed
 ✓ single version bare
 ✓ multiple versions
 ✓ indicates current version
 ✓ bare doesn't indicate current version
 ✓ globally selected version
 ✓ per-project version
 ✓ ignores non-directories under versions
 ✓ lists symlinks under versions
 ✓ finds versions where present
 ✓ outputs path to executable
 ✓ searches PATH for system version
 ✓ searches PATH for system version (shims prepended)
 ✓ searches PATH for system version (shims appended)
 ✓ searches PATH for system version (shims spread)
 ✓ version not installed
 ✓ versions not installed
 ✓ no executable found
 ✓ executable found in other versions
 ✓ carries original IFS within hooks
 ✓ discovers version from pyenv-version-name

156 tests, 1 failure
make: *** [test] Error 1

As the user, initial tests pass but then fail while in the encrypted dir:
user@kilgore:~/code/pyenv$ make
PATH="./bats/bin:$PATH" test/run
 ✓ commands
 ✓ commands --sh
 ✓ commands in path with spaces
 ✓ commands --no-sh
 ✓ command with no completion support
 ✓ command with completion support
 ✓ forwards extra arguments
 ✓ fails with invalid version
 ✓ completes with names of executables
 ✓ supports hook path with spaces
 ✓ carries original IFS within hooks
 ✓ forwards all arguments
 ✓ supports python -S <cmd>
 ✓ default
 ✓ read PYENV_ROOT/version
 ✓ set PYENV_ROOT/version
 ✓ fail setting invalid PYENV_ROOT/version
 ✓ without args shows summary of common commands
 ✓ invalid command
 ✓ shows help for a specific command
 ✓ replaces missing extended help with summary text
 ✓ extracts only usage
 ✓ multiline usage section
 ✓ multiline extended help section
 ✓ prints usage help given no argument
 ✓ prints list of hooks
 ✓ supports hook paths with spaces
 ✓ resolves relative paths
 ✓ resolves symlinks
 ✓ creates shims and versions directories
 ✓ auto rehash
 ✓ setup shell completions
 ✓ detect parent shell
 ✓ setup shell completions (fish)
 ✓ fish instructions
 ✓ option to skip rehash
 ✓ adds shims to PATH
 ✓ adds shims to PATH (fish)
 ✓ can add shims to PATH more than once
 ✓ doesn't add shims to PATH more than once (fish)
 ✓ outputs sh-compatible syntax
 ✓ outputs fish-specific syntax (fish)
 ✓ no version
 ✓ local version
 ✓ supports legacy .pyenv-version file
 ✓ local .python-version has precedence over .pyenv-version
 ✓ ignores version in parent directory
 ✓ ignores PYENV_DIR
 ✓ sets local version
 ✓ changes local version
 ✓ renames .pyenv-version to .python-version
 ✓ doesn't rename .pyenv-version if changing the version failed
 ✓ unsets local version
 ✓ unsets alternate version file
 ✓ prefix
 ✓ prefix for invalid version
 ✓ prefix for system
 ✓ prefix for invalid system
 ✓ blank invocation
 ✓ invalid command
 ✓ default PYENV_ROOT
 ✓ inherited PYENV_ROOT
 ✓ default PYENV_DIR
 ✓ inherited PYENV_DIR
 ✓ invalid PYENV_DIR
 ✓ adds its own libexec to PATH
 ✓ adds plugin bin dirs to PATH
 ✓ PYENV_HOOK_PATH preserves value from environment
 ✓ PYENV_HOOK_PATH includes pyenv built-in plugins
 ✓ empty rehash
 ✓ non-writable shims directory
 ✓ rehash in progress
 ✓ creates shims
 ✓ removes stale shims
 ✓ binary install locations containing spaces
 ✓ carries original IFS within hooks
 ✓ sh-rehash in bash
 ✓ sh-rehash in fish
 ✓ no shell version
 ✓ shell version
 ✓ shell version (fish)
 ✓ shell unset
 ✓ shell unset (fish)
 ✓ shell change invalid version
 ✓ shell change version
 ✓ shell change version (fish)
 ✓ no shims
 ✓ shims
 ✓ shims --short
 ✓ default version
 ✓ reads version from git repo
 ✓ prints default version if no tags in git repo
 ✓ no version selected
 ✓ set by PYENV_VERSION
 ✓ set by local file
 ✓ set by global file
 ✓ prints global file if no version files exist
 ✓ detects 'global' file
 ✓ detects 'default' file
 ✓ 'version' has precedence over 'global' and 'default'
 ✓ in current directory
 ✓ legacy file in current directory
 ✓ .python-version has precedence over legacy file
 ✓ in parent directory
 ✓ topmost file has precedence
 ✓ legacy file has precedence if higher
 ✓ PYENV_DIR has precedence over PWD
 ✓ PWD is searched if PYENV_DIR yields no results
 ✓ fails without arguments
 ✓ fails for invalid file
 ✓ fails for blank file
 ✓ reads simple version file
 ✓ ignores leading spaces
 ✓ reads only the first word from file
 ✓ loads *not* only the first line in file
 ✓ ignores leading blank lines
 ✓ handles the file with no trailing newline
 ✓ ignores carriage returns
 ✓ invocation without 2 arguments prints usage
 ✓ setting nonexistent version fails
 ✓ writes value to arbitrary file
 ✓ no version selected
 ✓ system version is not checked for existance
 ✓ PYENV_VERSION has precedence over local
 ✓ local file has precedence over global
 ✓ missing version
 ✓ version with prefix in name
 ✓ reports global file even if it doesn't exist
 ✓ detects global file
 ✓ detects PYENV_VERSION
 ✓ detects local file
 ✓ detects alternate version file
 ✓ no versions installed
 ✓ not even system python available
 ✓ bare output no versions installed
 ✓ single version installed
 ✓ single version bare
 ✓ multiple versions
 ✓ indicates current version
 ✓ bare doesn't indicate current version
 ✓ globally selected version
 ✓ per-project version
 ✓ ignores non-directories under versions
 ✓ lists symlinks under versions
 ✓ finds versions where present
 ✓ outputs path to executable
 ✓ searches PATH for system version
 ✓ searches PATH for system version (shims prepended)
 ✓ searches PATH for system version (shims appended)
 ✓ searches PATH for system version (shims spread)
 ✓ version not installed
 ✓ versions not installed
 ✓ no executable found
 ✓ executable found in other versions
 ✓ carries original IFS within hooks
 ✓ discovers version from pyenv-version-name

156 tests, 0 failures
cd plugins/python-build && /home/user/code/pyenv/bats/bin/bats ${CI:+--tap} test
 ✓ not enought arguments for python-build
 ✓ extra arguments for python-build
 ✓ yaml is installed for python
 ✓ apply python patch before building
 ✓ apply python patch from git diff before building
 ✓ yaml is linked from Homebrew
 ✓ readline is linked from Homebrew
 ✓ readline is not linked from Homebrew when explicitly defined
 ✓ number of CPU cores defaults to 2
 ✓ number of CPU cores is detected on Mac
 ✓ number of CPU cores is detected on FreeBSD
 ✓ setting PYTHON_MAKE_INSTALL_OPTS to a multi-word string
 ✓ setting MAKE_INSTALL_OPTS to a multi-word string
 ✓ custom relative install destination
 ✓ make on FreeBSD 9 defaults to gmake
 ✓ make on FreeBSD 10
 ✓ can use PYTHON_CONFIGURE to apply a patch
 ✓ copy strategy forces overwrite
 ✓ mruby strategy overwrites non-writable files
 ✓ mruby strategy fetches rake if missing
 ✓ rbx uses bundle then rake
 ✓ fixes rbx binstubs
 ✓ JRuby build
 ✓ JRuby+Graal does not install launchers
 ✓ JRuby Java 7 missing
 ✓ JRuby Java is outdated
 ✓ JRuby Java 7 up-to-date
 ✓ non-writable TMPDIR aborts build
 ✓ non-executable TMPDIR aborts build
 ✓ packages are saved to download cache
 ✓ cached package without checksum
 ✓ cached package with valid checksum
 ✓ cached package with invalid checksum falls back to mirror and updates cache
 ✓ nonexistent cache directory is ignored
 ✓ package URL without checksum
 ✓ package URL with valid checksum
 ✓ package URL with invalid checksum
 ✓ package URL with checksum but no shasum support
 ✓ package URL with valid md5 checksum
 ✓ package URL with md5 checksum but no md5 support
 ✓ package with invalid checksum
 ✓ existing tarball in build location is reused
 ✓ existing tarball in build location is discarded if not matching checksum
 ✓ require_gcc on OS X 10.9
 ✓ require_gcc on OS X 10.10
 ✓ require_gcc silences warnings
 ✓ CC=clang by default on OS X 10.10
 ✓ list built-in definitions
 ✓ custom PYTHON_BUILD_ROOT: nonexistent
 ✓ custom PYTHON_BUILD_ROOT: single definition
 ✓ one path via PYTHON_BUILD_DEFINITIONS
 ✓ multiple paths via PYTHON_BUILD_DEFINITIONS
 ✓ installing definition from PYTHON_BUILD_DEFINITIONS by priority
 ✓ installing nonexistent definition
 ✗ sorting Python versions
   (in test file test/definitions.bats, line 91)
     `touch "${PYTHON_BUILD_ROOT}/share/python-build/$ver"' failed
   touch: cannot touch ‘/home/user/code/pyenv/plugins/python-build/test/tmp/share/python-build/2.7-dev\n2.7\n2.7.1\n2.7.2\n2.7.3\n3.4.0\n3.4-dev\n3.4.1\n3.4.2\njython-dev\njython-2.5.0\njython-2.5-dev\njython-2.5.1\njython-2.5.2\njython-2.5.3\njython-2.5.4-rc1\njython-2.7-beta1\njython-2.7-beta2\njython-2.7-beta3’: File name too long
 ✓ removing duplicate Python versions
 ✓ failed download displays error message
 ✓ fetching from git repository
 ✓ updating existing git repository
 ✓ pyenv-install hooks
 ✓ pyenv-uninstall hooks
 ✓ installs python-build into PREFIX
 ✓ build definitions don't have the executable bit
 ✓ overwrites old installation
 ✓ unrelated files are untouched
 ✓ package URL without checksum bypasses mirror
 ✓ package URL with checksum but no shasum support bypasses mirror
 ✓ package URL with checksum hits mirror first
 ✓ package is fetched from original URL if mirror download fails
 ✓ package is fetched from original URL if mirror download checksum is invalid
 ✓ default mirror URL
 ✓ install proper
 ✓ install pyenv local version by default
 ✓ list available versions
 ✓ nonexistent version
 ✓ Homebrew upgrade instructions
 ✓ no build definitions from plugins
 ✓ some build definitions from plugins
 ✓ list build definitions from plugins
 ✓ completion results include build definitions from plugins
 ✓ not enough arguments for pyenv-install
 ✓ too many arguments for pyenv-install
 ✓ show help for pyenv-install
 ✓ not enough arguments pyenv-uninstall
 ✓ too many arguments for pyenv-uninstall
 ✓ show help for pyenv-uninstall
 ✓ apply built-in python patch before building
 ✓ apply built-in python patches should be sorted by its name
 ✓ allow custom make install target
 ✓ python-build static version
 ✓ python-build git version
 ✓ git describe fails
 ✓ git remote doesn't match

93 tests, 1 failure
make: *** [test] Error 1

Finally outside my encrypted home dir - Success:
user@kilgore:/tmp/PYTHON_BUILD_ROOT/pyenv$ make
PATH="./bats/bin:$PATH" test/run
 ✓ commands
 ✓ commands --sh
 ✓ commands in path with spaces
 ✓ commands --no-sh
 ✓ command with no completion support
 ✓ command with completion support
 ✓ forwards extra arguments
 ✓ fails with invalid version
 ✓ completes with names of executables
 ✓ supports hook path with spaces
 ✓ carries original IFS within hooks
 ✓ forwards all arguments
 ✓ supports python -S <cmd>
 ✓ default
 ✓ read PYENV_ROOT/version
 ✓ set PYENV_ROOT/version
 ✓ fail setting invalid PYENV_ROOT/version
 ✓ without args shows summary of common commands
 ✓ invalid command
 ✓ shows help for a specific command
 ✓ replaces missing extended help with summary text
 ✓ extracts only usage
 ✓ multiline usage section
 ✓ multiline extended help section
 ✓ prints usage help given no argument
 ✓ prints list of hooks
 ✓ supports hook paths with spaces
 ✓ resolves relative paths
 ✓ resolves symlinks
 ✓ creates shims and versions directories
 ✓ auto rehash
 ✓ setup shell completions
 ✓ detect parent shell
 ✓ setup shell completions (fish)
 ✓ fish instructions
 ✓ option to skip rehash
 ✓ adds shims to PATH
 ✓ adds shims to PATH (fish)
 ✓ can add shims to PATH more than once
 ✓ doesn't add shims to PATH more than once (fish)
 ✓ outputs sh-compatible syntax
 ✓ outputs fish-specific syntax (fish)
 ✓ no version
 ✓ local version
 ✓ supports legacy .pyenv-version file
 ✓ local .python-version has precedence over .pyenv-version
 ✓ ignores version in parent directory
 ✓ ignores PYENV_DIR
 ✓ sets local version
 ✓ changes local version
 ✓ renames .pyenv-version to .python-version
 ✓ doesn't rename .pyenv-version if changing the version failed
 ✓ unsets local version
 ✓ unsets alternate version file
 ✓ prefix
 ✓ prefix for invalid version
 ✓ prefix for system
 ✓ prefix for invalid system
 ✓ blank invocation
 ✓ invalid command
 ✓ default PYENV_ROOT
 ✓ inherited PYENV_ROOT
 ✓ default PYENV_DIR
 ✓ inherited PYENV_DIR
 ✓ invalid PYENV_DIR
 ✓ adds its own libexec to PATH
 ✓ adds plugin bin dirs to PATH
 ✓ PYENV_HOOK_PATH preserves value from environment
 ✓ PYENV_HOOK_PATH includes pyenv built-in plugins
 ✓ empty rehash
 ✓ non-writable shims directory
 ✓ rehash in progress
 ✓ creates shims
 ✓ removes stale shims
 ✓ binary install locations containing spaces
 ✓ carries original IFS within hooks
 ✓ sh-rehash in bash
 ✓ sh-rehash in fish
 ✓ no shell version
 ✓ shell version
 ✓ shell version (fish)
 ✓ shell unset
 ✓ shell unset (fish)
 ✓ shell change invalid version
 ✓ shell change version
 ✓ shell change version (fish)
 ✓ no shims
 ✓ shims
 ✓ shims --short
 ✓ default version
 ✓ reads version from git repo
 ✓ prints default version if no tags in git repo
 ✓ no version selected
 ✓ set by PYENV_VERSION
 ✓ set by local file
 ✓ set by global file
 ✓ prints global file if no version files exist
 ✓ detects 'global' file
 ✓ detects 'default' file
 ✓ 'version' has precedence over 'global' and 'default'
 ✓ in current directory
 ✓ legacy file in current directory
 ✓ .python-version has precedence over legacy file
 ✓ in parent directory
 ✓ topmost file has precedence
 ✓ legacy file has precedence if higher
 ✓ PYENV_DIR has precedence over PWD
 ✓ PWD is searched if PYENV_DIR yields no results
 ✓ fails without arguments
 ✓ fails for invalid file
 ✓ fails for blank file
 ✓ reads simple version file
 ✓ ignores leading spaces
 ✓ reads only the first word from file
 ✓ loads *not* only the first line in file
 ✓ ignores leading blank lines
 ✓ handles the file with no trailing newline
 ✓ ignores carriage returns
 ✓ invocation without 2 arguments prints usage
 ✓ setting nonexistent version fails
 ✓ writes value to arbitrary file
 ✓ no version selected
 ✓ system version is not checked for existance
 ✓ PYENV_VERSION has precedence over local
 ✓ local file has precedence over global
 ✓ missing version
 ✓ version with prefix in name
 ✓ reports global file even if it doesn't exist
 ✓ detects global file
 ✓ detects PYENV_VERSION
 ✓ detects local file
 ✓ detects alternate version file
 ✓ no versions installed
 ✓ not even system python available
 ✓ bare output no versions installed
 ✓ single version installed
 ✓ single version bare
 ✓ multiple versions
 ✓ indicates current version
 ✓ bare doesn't indicate current version
 ✓ globally selected version
 ✓ per-project version
 ✓ ignores non-directories under versions
 ✓ lists symlinks under versions
 ✓ finds versions where present
 ✓ outputs path to executable
 ✓ searches PATH for system version
 ✓ searches PATH for system version (shims prepended)
 ✓ searches PATH for system version (shims appended)
 ✓ searches PATH for system version (shims spread)
 ✓ version not installed
 ✓ versions not installed
 ✓ no executable found
 ✓ executable found in other versions
 ✓ carries original IFS within hooks
 ✓ discovers version from pyenv-version-name

156 tests, 0 failures
cd plugins/python-build && /tmp/PYTHON_BUILD_ROOT/pyenv/bats/bin/bats ${CI:+--tap} test
 ✓ not enought arguments for python-build
 ✓ extra arguments for python-build
 ✓ yaml is installed for python
 ✓ apply python patch before building
 ✓ apply python patch from git diff before building
 ✓ yaml is linked from Homebrew
 ✓ readline is linked from Homebrew
 ✓ readline is not linked from Homebrew when explicitly defined
 ✓ number of CPU cores defaults to 2
 ✓ number of CPU cores is detected on Mac
 ✓ number of CPU cores is detected on FreeBSD
 ✓ setting PYTHON_MAKE_INSTALL_OPTS to a multi-word string
 ✓ setting MAKE_INSTALL_OPTS to a multi-word string
 ✓ custom relative install destination
 ✓ make on FreeBSD 9 defaults to gmake
 ✓ make on FreeBSD 10
 ✓ can use PYTHON_CONFIGURE to apply a patch
 ✓ copy strategy forces overwrite
 ✓ mruby strategy overwrites non-writable files
 ✓ mruby strategy fetches rake if missing
 ✓ rbx uses bundle then rake
 ✓ fixes rbx binstubs
 ✓ JRuby build
 ✓ JRuby+Graal does not install launchers
 ✓ JRuby Java 7 missing
 ✓ JRuby Java is outdated
 ✓ JRuby Java 7 up-to-date
 ✓ non-writable TMPDIR aborts build
 ✓ non-executable TMPDIR aborts build
 ✓ packages are saved to download cache
 ✓ cached package without checksum
 ✓ cached package with valid checksum
 ✓ cached package with invalid checksum falls back to mirror and updates cache
 ✓ nonexistent cache directory is ignored
 ✓ package URL without checksum
 ✓ package URL with valid checksum
 ✓ package URL with invalid checksum
 ✓ package URL with checksum but no shasum support
 ✓ package URL with valid md5 checksum
 ✓ package URL with md5 checksum but no md5 support
 ✓ package with invalid checksum
 ✓ existing tarball in build location is reused
 ✓ existing tarball in build location is discarded if not matching checksum
 ✓ require_gcc on OS X 10.9
 ✓ require_gcc on OS X 10.10
 ✓ require_gcc silences warnings
 ✓ CC=clang by default on OS X 10.10
 ✓ list built-in definitions
 ✓ custom PYTHON_BUILD_ROOT: nonexistent
 ✓ custom PYTHON_BUILD_ROOT: single definition
 ✓ one path via PYTHON_BUILD_DEFINITIONS
 ✓ multiple paths via PYTHON_BUILD_DEFINITIONS
 ✓ installing definition from PYTHON_BUILD_DEFINITIONS by priority
 ✓ installing nonexistent definition
 ✓ sorting Python versions
 ✓ removing duplicate Python versions
 ✓ failed download displays error message
 ✓ fetching from git repository
 ✓ updating existing git repository
 ✓ pyenv-install hooks
 ✓ pyenv-uninstall hooks
 ✓ installs python-build into PREFIX
 ✓ build definitions don't have the executable bit
 ✓ overwrites old installation
 ✓ unrelated files are untouched
 ✓ package URL without checksum bypasses mirror
 ✓ package URL with checksum but no shasum support bypasses mirror
 ✓ package URL with checksum hits mirror first
 ✓ package is fetched from original URL if mirror download fails
 ✓ package is fetched from original URL if mirror download checksum is invalid
 ✓ default mirror URL
 ✓ install proper
 ✓ install pyenv local version by default
 ✓ list available versions
 ✓ nonexistent version
 ✓ Homebrew upgrade instructions
 ✓ no build definitions from plugins
 ✓ some build definitions from plugins
 ✓ list build definitions from plugins
 ✓ completion results include build definitions from plugins
 ✓ not enough arguments for pyenv-install
 ✓ too many arguments for pyenv-install
 ✓ show help for pyenv-install
 ✓ not enough arguments pyenv-uninstall
 ✓ too many arguments for pyenv-uninstall
 ✓ show help for pyenv-uninstall
 ✓ apply built-in python patch before building
 ✓ apply built-in python patches should be sorted by its name
 ✓ allow custom make install target
 ✓ python-build static version
 ✓ python-build git version
 ✓ git describe fails
 ✓ git remote doesn't match

93 tests, 0 failures

**Comment by blueyed** [comment]
What about the user running it in the user's dir?
Same error? (with "touch in sorting Python versions")?

**Comment by yyuu** [comment]
Realistically it is not possible to support all the filesystem. Please use filesystem which supports _longer_ path name.
