### ISSUE TITLE
Raspberry pi: I cannot install python versions 

### ISSUE THREAD

**Issue by crazcalm** [yyuu/pyenv#369]
Regardless of which version of python I try to install, I get the same build error (See photo for details).

Device: Rasberry pi B+

![2015-05-02 1](https://cloud.githubusercontent.com/assets/3482344/7443226/56413890-f109-11e4-99b9-8b22d8330fa6.jpg)

**Comment by yyuu** [comment]
Please check if you have connectivity to the internet .

**Comment by crazcalm** [comment]
I got everything to work. I am at a hackathon, so the internet is so-so.

Anyway, after I got connected to the internet and installed all the packages in your common build issues page, everything starting to work.

Thanks again!
