### ISSUE TITLE
"pip install pyenv" fails with error: option --single-version-externally-managed not recognized

### ISSUE THREAD

**Issue by ralhei** [yyuu/pyenv#387]
Trying to install pyenv with
    `pip install pyenv`
unfortunately fails with 
```
Collecting pyenv
  Using cached pyenv-20150113.1.tar.gz
Installing collected packages: pyenv
  Running setup.py install for pyenv
    Complete output from command /usr/local/software/Python-2.7.9/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-1LJ4tO/pyenv/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-CJIaMp-record/install-record.txt --single-version-externally-managed --compile:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: option --single-version-externally-managed not recognized
```
I'm using the most recent version of pip (7.0.3) and setuptools (17.0) on Python 2.7.9 on linux.

Any ideas what is wrong?

**Comment by yyuu** [comment]
pyenv itself isn't providing the pip installer. please report the issue to https://github.com/yyuu/pyenv-installer

**Comment by ralhei** [comment]
will do. Thanks for your feedback.

**Comment by ssbarnea** [comment]
Why is this `--egg` even needed?! As far as I remember eggs became deprecated long time ago.  Cannot use wheels?

**Comment by joshfriend** [comment]
pyenv isnt even distributed on pypi anymore. Install it with one of the methods in the [README](https://github.com/yyuu/pyenv#installation)

**Comment by ssbarnea** [comment]
I still see the package there at https://pypi.python.org/pypi/pyenv/ -- and it does not say: don't use me. In fact if is broken it should just be removed or hidden on pypi.

Any reason for not updating it there?

**Comment by yyuu** [comment]
The pip package is not maintained as a part of this project. It's experimental hacky solution and not a recommended way to install pyenv at least for now.

**Comment by archonsd** [comment]
Thanks for the hint about --egg.  It helped me get 'pip install pyenv' going on Ubuntu 14.04.5 LTS just now.  Without it I get the OP's error.

**Comment by ssbarnea** [comment]
10 months later I hit the same bug,... and read the thread again with my own comments inside. :(
