### ISSUE TITLE
pyenv rehash segmentation fault

### ISSUE THREAD

**Issue by greenthreads** [yyuu/pyenv#388]
while installing a package I came acroos the segfault:

[root@billme test]# pip install newrelic
Collecting newrelic
  Downloading newrelic-2.50.0.39.tar.gz (662kB)
    99% |███████████████████████████████▉| 659kB 8.2MB/s eta 0:00:01/root/.pyenv/plugins/pyenv-pip-rehash/libexec/pip: line 20:  9261 Segmentation fault      "$PYENV_COMMAND_PATH" "$@"

[root@billme test]# pip --version
pip 6.1.1 from /root/.pyenv/versions/2.7.8/lib/python2.7/site-packages (python 2.7)

No idea what's going on here..

**Comment by yyuu** [comment]
Could not reproduce the problem on my installation.

Basically pyenv just invokes `pip` from its shell scripts, and the problem would be in the package or pip itself.

**Comment by greenthreads** [comment]
can install any package with the global version of PIP. there is no problem. My suspect is there is something wrong with the environment variables in CentOS 7. anyway thanks for having a look, I will try to fix it myself ;)
