### ISSUE TITLE
`pyenv global <other_version> system` doesn't work

### ISSUE THREAD

**Issue by aiguofer** [yyuu/pyenv#391]
I originally asked this in #331 since it was related, but I think this is a separate issue. I have a few system wide python libs that are better installed through my Linux distro (matplotlib, pygtk, and a few others). In order to avoid installing them on each python env, I'd like to have them fall back to the systemwide library.

I found that this can be accomplished by 'chaining' the versions like so `pyenv global <other_version> ... system`. This chaining works as expected, except when `system` is the last one in the chain.

```
 ~  pyenv prefix system
/usr
 ~  pyenv global system
 ~  pyenv prefix
/usr
 ~  pyenv global system 2.7.10
 ~  pyenv prefix              
/usr:/home/rdu/difernan/.pyenv/versions/2.7.10
 ~  pyenv global 2.7.10 system 
 ~  pyenv prefix                     
/home/rdu/difernan/.pyenv/versions/2.7.10:/home/rdu/difernan/.pyenv/versions/2.7.10
```

**Comment by yyuu** [comment]
I confirmed the reproduction. I'll investigate the cause. Thanks for reporting :octocat:

**Comment by yyuu** [comment]
Found a bug in `pyenv-prefix`. I fixed that and then added test for it. Thanks again for reporting.
