### ISSUE TITLE
Example of enabling build with shared Python library.

### ISSUE THREAD

**Issue by GrahamDumpleton** [yyuu/pyenv#392]
The wiki page for common problems should give an example of how to install Python with a shared library. A shared library is needed in any embedded system where the Python library itself has to be linked to a dynamically loaded module.

The prime example of this is mod_wsgi.

For Linux it is a simple matter of using:

```
CONFIGURE_OPTS=--enable-shared pyenv install 2.7.10
```

**Comment by yyuu** [comment]
Anyone on GH can edit wiki.

**Comment by muxator** [comment]
In the meantime, the wiki was long updated.

Since Google keeps linking to this old issue, this is a direct link to the relevant page (hopefully more up-to-date than this ticket):

https://github.com/pyenv/pyenv/wiki#how-to-build-cpython-with---enable-shared

**Comment by le-travie** [comment]
$ env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.5.0 what would this be for windows? I have been trying and failing to get it to work on my machine. Obviously windows does not have env

**Comment by native-api** [comment]
@le-travie [Pyenv doesn't support Windows outside of WSL](https://github.com/pyenv/pyenv#windows), https://github.com/pyenv-win/pyenv-win does.

**Comment by le-travie** [comment]
> @le-travie [Pyenv doesn't support Windows outside of WSL](https://github.com/pyenv/pyenv#windows), https://github.com/pyenv-win/pyenv-win does.

Ah. Thanks.
