### ISSUE TITLE
question about 3.5-dev

### ISSUE THREAD

**Issue by changsijay** [yyuu/pyenv#395]
I found that `pyenv install -l` have `3.5-dev` in it.
it get latest code from python Mercurial repository(https://bitbucket.org/mirror/cpython).

How can I keep it be the latest code everyday after I install it?
`pyenv install 3.5-dev` everyday?

**Comment by yyuu** [comment]
At first, you should create cache directory by `mkdir -p "$(pyenv root)/cache"` to create repository cache. Then, run `pyenv uninstall -f 3.5-dev && pyenv install 3.5-dev` everyday.

**Comment by changsijay** [comment]
got it. thank you very much :100:
