### ISSUE TITLE
Python development headers not found

### ISSUE THREAD

**Issue by AbdealiJK** [yyuu/pyenv#397]
When using pyenv's python to compile a module, I get the following error.
Weirdly, I do not get the error with python3.4 ... but only with python3.3

```
checking for Python headers in /home/ubuntu/.pyenv/versions/3.3.3 and /home/ubuntu/.pyenv/versions/3.3.3... -I/home/ubuntu/.pyenv/versions/3.3.3/include/python3.3
checking whether those headers are sufficient... no
```

**Comment by yyuu** [comment]
pyenv doesn't do nothing special other than custom prefix. Even if there is some problem it would be a problem of the package itself. Anyway you should describe what you did actually and put all the output.

**Comment by AbdealiJK** [comment]
thanks for the response !

What I did was the following:
 1. I installed python3.3 using `pyenv install -ks 3.3.3`
 1. Installed system binaries using deadsnakes ppa (in ubuntu) `sudo apt-get -qq install python3.3-dev`
 1. I then try to install dbus using `./configure` and `make` .. the `make` fails

The whole log can be found at the circleci build https://circleci.com/gh/coala-analyzer/coala/1132

Over there, container 1 is python3.4 container 2 is python 3.2 ... and only python3.3 seems to fail

**Comment by yyuu** [comment]
I don't know much about dbus-python, but you don't need to install system's python-dev package if you install python via pyenv. Because pyenv builds and installs from source, obviously it is including headers. And, you would need to specify dbus' ./configure script where your python is installed, like './configure --with-python=$(pyenv root)versions/3.3.3/bin/python' or something like that. This is heavily depending how the build system of the package.

**Comment by yyuu** [comment]
I think this is a generic question if building python, and not an issue of pyenv.

**Comment by AbdealiJK** [comment]
I did do a `pyenv local 3.3.3` which should do that.
And it works if I use the system python `python3.3` ... So, I dont see how it's a problem with the package.

I find the same things happening with python-gi also.

**Comment by blueyed** [comment]
`pyenv local 3.3.3` won't necessarily make a build system pick it up properly.
Also note that `sudo` won't pick up / use your local `python`, too.

**Comment by blueyed** [comment]
@AbdealiJK 
The error is pretty clear, isn't it:

    checking for Python headers using /home/ubuntu/.pyenv/shims/python-config --includes... pyenv: python-config: command not found

    The `python-config' command exists in these Python versions:
      2.6.6
      2.6.8
      2.7
      2.7.3
      2.7.4
      2.7.5
      2.7.6
      2.7.7
      2.7.8
      2.7.9
      3.4.2

**Comment by AbdealiJK** [comment]
@blueyed Sorry, I didn't understand that.
Why would the python-config command not exist for 3.3.3 and exist for all others ? I assumed it was something `pyenv install 3.3.3` would handle for me.

Sorry, I'm not very used to pyenv - so, maybe I'm missing something very obvious.

**Comment by blueyed** [comment]
There might be only `python3-config` (although 3.3.6 has `python-config`).
(I remember something odd like that happening to me before)

**Comment by AbdealiJK** [comment]
I see - I'll check that out !
Thanks :)

**Comment by blueyed** [comment]
@AbdealiJK 
Any news / new findings?

**Comment by AbdealiJK** [comment]
Thanks for enquiring.
Yes, I got the circleci build to work. I used python 3.3.6 and it seems to work.
3.3.3 still doesn't seem to work on circleci - but when I tried to run it on a virtualmachine with a fresh installation of ubuntu - 3.3.3 also worked. So, I guess something weird with circleci here.

**Comment by yyuu** [comment]
:+1:

**Comment by bmcorser** [comment]
I'm seeing something similar (trying to build [YouCompleteMe](https://github.com/Valloric/YouCompleteMe)) on OSX ...
```
$ which python
/Users/ben/.pyenv/versions/virtualenv-xyz/bin/python
$ python --version
Python 2.7.8
$ python-config
pyenv: python-config: command not found

The `python-config' command exists in these Python versions:
  2.7.8
```

**Comment by bmcorser** [comment]
This seemed to be related to my having a `3`-series Python in my `global`:
```
$ pyenv global
3.4.2
3.3.6
2.7.8
$ pyenv global 2.7.8
$ pyenv global
2.7.8
```
Open a new shell:
```
$ python-config
Usage: /Users/ben/.pyenv/versions/2.7.8/bin/python-config [--prefix|--exec-prefix|--includes|--libs|--cfla
gs|--ldflags|--help]
```
However if I activate my vitrualenv:
```
$ pyenv activate virtualenv-xyz
(virtualenv-xyz) $ python-config
pyenv: python-config: command not found
...
```

**Comment by bartekbrak** [comment]
I believe this is a `pyenv-virtualenv` issue. When creating a new virtualenv, the headers are not created/symlinked in its folder. Neither is `python-config` or as in my case `python3.5-config` that `dbus` I'm installing now is looking for. I switched to the global python and installation went fine. Then back to virtualenv and bang:

```
$ pyenv local 3.5.0
$ pip install git+https://github.com/posborne/dbus-python.git
# all ok
$ pyenv local myenv
$ pip install git+https://github.com/posborne/dbus-python.git | grep -C 1 "could not find Python headers"
    checking whether those headers are sufficient... no
    configure: error: could not find Python headers
```

@yyuu, Do you think virtualenv should symlink the headers and so on? Should I open a separate issue on its gh page?

**Comment by yyuu** [comment]
@bartekbrak pyenv-virtualenv is just a wrapper for virtualenv. I think this kind of thing is basically an issue of underlying virtualenv. Go ahead to create separate issue.

**Comment by yyuu** [comment]
I added a hook file in yyuu/pyenv-virtualenv@cce1b9535d31abb083f1f0fe56d3dd221472c70b to allow pyenv to find `python-config` from the source version of currently activated virtualenv. I believe this works well with most cases when building native extensions.

Although, the problem with dbus-python won't be solved by ^ since its build script is expecting `python-config` at the same directory as `python` executable. This expectation would be wrong even with vanilla `virtualenv` (or, `pyvenv`). I believe it should be fixed in dbus-python side, and I'll try to fix it later if I have time.

https://github.com/posborne/dbus-python/blob/ff53d1085dfc005cefecc5e2a495117b9248caf3/configure.ac#L81

**Comment by yyuu** [comment]
Just for reference, I've prepared another hook script as a workaround for dbus-python. Save this file at `$(pyenv root)/plugins/pyenv-virtualenv/etc/pyenv.d/virtualenv/python-config.bash` and recreate virtualenv with `pyenv virtualenv` then newly created virtualenv will come with symlinks of `python-config`.

```sh
# symlink `python-config` into virtualenv since some of native extensions (e.g. dbus-python)
# expects it as the same path as `python` executable.
# https://github.com/yyuu/pyenv/issues/397

symlink_python_config() {
  local real_prefix="$(pyenv-virtualenv-prefix 2>/dev/null || pyenv-prefix 2>/dev/null || true)"
  if [ -n "${real_prefix}" ] && [ -d "${VIRTUALENV_PATH}" ]; then
    local file
    for file in "${real_prefix}/bin/"*; do
      if [ -x "${file}" ]; then
        case "${file##*/}" in 
        "python"*"-config" )
          ln -fs "${file}" "${VIRTUALENV_PATH}/bin/${file##*/}"
        ;;
        esac
      fi
    done
  fi
}

after_virtualenv symlink_python_config
```

I confirmed this works well with current impl of dbus-python. I'm still thinking that fixing dbus-python itself would be the proper way, though.

**Comment by yyuu** [comment]
Opened posborne/dbus-python#1 for dbus-python issue.

**Comment by bartekbrak** [comment]
Tested. I confirm, this worked. You're great!

Not that I could install dbus anyway, its setup.py is broken in other ways but that's dbus problem. I gave up as this was just one of many failing dependencies for some neglected package I researched. I hope  this solution will help someone else with some similar problem.

**Comment by bmcorser** [comment]
@yyuu :+1:

**Comment by d0f** [comment]
sudo apt-get install libdbus-1-dev libdbus-glib-1-dev

**Comment by eric-burel** [comment]
For googlers, I seem to reproduce this issue when using the wrong version of pyinstall. I use Python `3.7.0` but some part of my build pipeline is trying to use `3.6.9`, leading to headers not found. So installing `python-dev` warning message is misleading, the issue is not in `pyenv` at all.

**Comment by haynesgt** [comment]
I found this issue trying to use a custom pyenv interpreter with `pipenv install`. I was getting "fatal error: Python.h: No such file or directory". Ended up doing `python-config --includes` to find the header location, then ran `export CPATH=/home/ubuntu/.pyenv/versions/3.8.12/include/python3.8` (the header location). After that, `pipenv install` worked.
