### ISSUE TITLE
Add Nuitka support

### ISSUE THREAD

**Issue by rodfersou** [yyuu/pyenv#398]
Is it possible to add Nuitka support in pyenv?

* http://nuitka.net/
* https://github.com/kayhayen/Nuitka

**Comment by yyuu** [comment]
Technically `nuitka` is a Python package and it can be installed via PyPI, by `pip install nuitka`. What you intended was to run `nuitka-run` as `python` from pyenv, like following?

```sh
$ pyenv install nuitka-dev
$ pyenv shell nuitka-dev
$ python --help
Usage: nuitka-run [options] main_module.py

Options:
  --version             show program's version number and exit
  -h, --help            show this help message and exit
  --module              Create an extension module executable instead of a
                        program. Defaults to off.
  --standalone, --portable
                        Enable standalone mode in build. This allows you to
                        transfer the created binary to other machines without
(... snip ...)
```

**Comment by rodfersou** [comment]
Oh sorry, my mistake.  I thought nuitka was something like a full python distribution, not a package.

Thank you for the answer.
