### ISSUE TITLE
Fails to add pip-installed binaries to PATH

### ISSUE THREAD

**Issue by mcandre** [yyuu/pyenv#403]
pyenv neglects to add the currently active Python's pip-installed binaries, such as shovel, to PATH.

Configuration:

https://github.com/mcandre/dotfiles/blob/master/.bashrc.d/pyenv.sh

https://github.com/mcandre/dotfiles/blob/master/.python-version

**Comment by thomasjo** [comment]
Where are you setting `PYENV_ROOT` and updating `PATH`, if at all? See [step 2](https://github.com/yyuu/pyenv#basic-github-checkout).

**Comment by yyuu** [comment]
If you installed packages into virtualenv, pyenv might not be able to hook invocation of `pip install` since virtualenv injects the path to itself at the top of PATH. If so, please run `pyenv rehash` manually to update shims.

**Comment by mcandre** [comment]
Thanks thomasjo! That fixes it.
