### ISSUE TITLE
Different behaviour when invoking .py script through symlink

### ISSUE THREAD

**Issue by blueyed** [yyuu/pyenv#404]
When calling a Python script via its shebang line, the following part in the `python` shim kicks in:

      if [ -f "$arg" ]; then
        export PYENV_DIR="${arg%/*}"
        break
      fi

However, that should resolve symlinks probably:

        arg=$(readlink -f $arg)

Otherwise calling it via a symlink from e.g. `~/bin` `pyenv-version-file` will not pick up a `.python-version` file from the final destination, but only from `~/bin`.

The current behaviour could be seen as a feature: by using symlinks you could have different Python versions (depending on where the symlink's file is), but I think it makes more sense to use the real script's dir.

btw: this code currently does not handle `python2`/`python3` in the shebang line properly (https://github.com/yyuu/pyenv/pull/379) - I will re-open that PR.

**Comment by blueyed** [comment]
I've added a proposed fix for this to #379: https://github.com/blueyed/pyenv/commit/dab47426519ac48900c80fc9de8751286a02cfe8

**Comment by blueyed** [comment]
If that's the way to go there should be some test for this then.

**Comment by yyuu** [comment]
Thanks for reporting. Please provide me some minimum script to reproduce the issue (or, test case) if you're available.

**Comment by blueyed** [comment]
Create a `test.py` file that you call then with the full path or it's symlink,
with a local version at the symlink target and symlink's place:

    % cd /tmp
    % cat > test.py
    #!/usr/bin/env python
    import sys

    print(sys.version_info)

    % chmod +x test.py
    % pyenv local 2.7.10

    % cd ~/tmp
    % pyenv local 3.4.3

    % /tmp/test.py
    sys.version_info(major=2, minor=7, micro=10, releaselevel='final', serial=0)

    % ln -s /tmp/test.py
    % ./test.py
    sys.version_info(major=3, minor=4, micro=3, releaselevel='final', serial=0)
