### ISSUE TITLE
Issue building python 3.4.3 on Alpine linux

### ISSUE THREAD

**Issue by rothnic** [yyuu/pyenv#407]
I have been trying to setup an alpine linux docker image for building python, that would then be used in a docker image for running/testing an app.

I have a docker image working for pyenv, but only can build 2.7 at the moment (2.7.10). I think the issue might be a combination of the use of pyenv and alpine linux, with alpine linux being special because it uses musl c compiler.

First you need docker, with boot2docker working on other platforms. If you clone this repo at this commit: [docker-deploy-python](https://github.com/rothnic/docker-python-deploy/commit/a6e75690c904f9c0d18b46fb9fb71fd1cf384f18). Run `./init.sh`, which will build a docker image with build requirements and pyenv setup ready to go. It will also build python 2.7.10 into your local .python directory. (The point is to contain the building of python and the requirements to build in one docker image, then utilize the many built version of python in other images as required.)

Next run `docker run --rm -v "$(pwd)"/.python:/root/.pyenv/versions  -v "$(pwd)"/.cache/python:/root/.pyenv/cache -it python-builder install -v 3.4.3`, which tries to build 3.4.3 in the same way that 2.7.10 was built.

[This gist](https://gist.github.com/rothnic/3e785df935ae0e61adb7) includes the output of that command when I run it.

**Comment by yyuu** [comment]
I'm not sure what is the root cause at least for now, but it looks like your environment has some of problems.

It failed to create symlink of python executable:

https://gist.github.com/rothnic/3e785df935ae0e61adb7#file-pyenv_3-4-3_build_log-log-L1295

It failed to build `ssl` module of CPython. It is a requirement to install setuptools/pip.

https://gist.github.com/rothnic/3e785df935ae0e61adb7#file-pyenv_3-4-3_build_log-log-L6583

Please make sure if you can build python without using pyenv. If it's possible, something might be wrong in pyenv.

**Comment by rothnic** [comment]
Yeah, looks like _ssl fails because of _socket: https://gist.github.com/rothnic/3e785df935ae0e61adb7#file-pyenv_3-4-3_build_log-log-L6566

I assumed I had all build requirements since 2.7.10 builds and runs fine. I'm not sure what the symlink would be doing since the only thing going on is running pyenv install 3.4.3 inside of a docker container. The rest of the command I stated is just mounting volumes so the build is available after the container is finished and destroyed.

**Comment by rothnic** [comment]
Ok, so I got the ssl issue fixed by adding some additional build requirements, but the main issue about the invalid python3.4 still exists. It appears the issue is related to the symlink that you pointed out.

I checked the bin directory and there was no python, andI can use the python version if I run the docker image, then manually create the symlink to python.

Here is the build script for the official alpine python3: http://git.alpinelinux.org/cgit/aports/tree/main/python3/APKBUILD

And for python2:
http://git.alpinelinux.org/cgit/aports/tree/main/python/APKBUILD

**Comment by yyuu** [comment]
I confirmed the reproduction of same compilation error of CPython 3.4.3 on Alpine Linux 3.2. It seems there're some compilation issue with gcc-musl.

https://gist.github.com/rothnic/3e785df935ae0e61adb7#file-pyenv_3-4-3_build_log-log-L6550-L6562

**Comment by yyuu** [comment]
Changing compiler could work, obviously....

```sh
# apk-install clang
# CC=clang pyenv install -v 3.4.3
```

**Comment by yyuu** [comment]
I haven't yet succeeded to build CPython with MUSL libc. Basically this would be a build problem of CPython itself. As a workaround, please explicitly specify pyenv to use `clang` when building.

**Comment by sethamclean** [comment]
This didn't work for me. This SO topic has a solution that worked though.

http://stackoverflow.com/questions/32973975/why-isnt-pyenv-finding-openssl-shared-libraries-under-alpine-linux
