### ISSUE TITLE
Failed building python 2.7.10 and 3.4.3 on Yosemite (10.10.4) due to missing OpenSSL/zlib

### ISSUE THREAD

**Issue by kmostrom** [yyuu/pyenv#408]
Neither 2.7.10 or 3.4.3 builds when using: pyenv install <version>

At first it did complain about not finding OpenSSL. After installing rbenv (which installs openssl) it complained about missing zlib.

Gist with verbose log: https://gist.github.com/kmostrom/7b1a92a1cad61264f8b9

**Comment by yyuu** [comment]
This is an issue tracker. You should debug yourself.
