### ISSUE TITLE
"pip: command not found" in installs of 2.7.9 and 2.7.10

### ISSUE THREAD

**Issue by jackmaney** [yyuu/pyenv#411]
Lately, I've noticed the following issue with 2.7 installs, especially 2.7.9 and 2.7.10 ([both of which should include pip automatically](https://pip.pypa.io/en/latest/installing.html#pip-included-with-python)).

    $ pyenv install 2.7.10
    Installing Python-2.7.10...
    Installed Python-2.7.10 to /Users/<username>/.pyenv/versions/2.7.10

Okay, let's switch...

    $ pyenv global 2.7.10
    $ python --version
    Python 2.7.10

Cool. So, let's make sure pip is working...

    $ pip --help
    pyenv: pip: command not found
    
    The `pip' command exists in these Python versions:
     2.6.9
      3.2.6
      3.3.6
      3.4.3
      ...

...huh. Well, let's install it manually, anyways:

    $ curl https://bootstrap.pypa.io/get-pip.py | python
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 1380k  100 1380k    0     0  1090k      0  0:00:01  0:00:01 --:--:-- 1614k
    Requirement already up-to-date: pip in /usr/local/lib/python2.7/site-packages

Okay, now let's see if pip even exists.

    $ which pip
    /Users/<username>/.pyenv/shims/pip

Okay, cool...

    $ pip --help
    pyenv: pip: command not found
    
    The `pip' command exists in these Python versions:
      2.6.9
      3.2.6
      3.3.6
      3.4.3

This exact same issue occurs with 2.7.9, but not any 3.X version that I've installed (recently, 3.4.3 and 3.5.0b2).

**Comment by jimmywan** [comment]
This is not a valid test for the presence of pip:
```
$ which pip
/Users/<username>/.pyenv/shims/pip
```

The shims are part of pyenv that are used to delegate work out to the "active" version of python.

You want to use the following:
```
 pyenv help which
Usage: pyenv which <command>

Displays the full path to the executable that pyenv will invoke when
you run the given command.
```

**Comment by jackmaney** [comment]
$ python --version
    Python 2.7.10
    $ pyenv which pip
    pyenv: pip: command not found
    
    The `pip' command exists in these Python versions:
      2.6.9
      3.2.6
      3.3.6
      3.4.3
      3.5.0b2
      ...

**Comment by jimmywan** [comment]
On my virtual machine::
```
$ pyenv shell 2.7.9
$ pyenv which pip
/home/vagrant/.pyenv/versions/2.7.9/bin/pip

$ pyenv shell 2.7.10
$ pyenv which pip
/home/vagrant/.pyenv/versions/2.7.10/bin/pip
```

This was all done on an ubuntu VM.
I noticed your "/Users/<username>/.pyenv" directory. Are you trying to do this on Windows via cygwin?

P.S. I'm not in any way affiliated with the project. Just another pyenv user that is not seeming the same behavior.

**Comment by thomasjo** [comment]
> I noticed your "/Users//.pyenv" directory. Are you trying to do this on Windows via cygwin?

That is not a Cygwin path; OP is using OS X.

**Comment by jimmywan** [comment]
> That is not a Cygwin path; OP is using OS X.

Ahh, updated my previous comment. Sorry, I don't use OS X. Can't really help other than to say your problem is not universal across platforms.

**Comment by jackmaney** [comment]
Well, a `pyenv shell system` seemed to do the trick, and it's still pointing to 2.7.10. I wonder if Homebrew doesn't play a part in this...I installed 2.7.10 via Homebrew (it's a prerequisite for other things that I use), and that seems to be what `system` points to (and not the actual system python at `/usr/bin/python`).

However, this doesn't work for 2.x other than 2.7.10. 

So, pyenv doesn't seem to play nicely with Homebrew's python formula. In my `PATH`, I have, `$HOME/.pyenv/shims` and `$HOME/.pyenv bin` before `/usr/local/bin`.

However, looking at the installations within `~/.pyenv`, pip doesn't seem to come with 2.7.9 or 2.7.10 via pyenv:

    ~/.pyenv/versions/2.7.9/bin $ ll
    total 5136
    drwxr-xr-x  12 <username>  staff   408B Jul 17 17:03 ./
    drwxr-xr-x   6 <username>  staff   204B Jul 17 17:03 ../
    -rwxr-xr-x   1 <username>  staff   128B Jul 17 17:02 2to3*
    -rwxr-xr-x   1 <username>  staff   126B Jul 17 17:02 idle*
    -rwxr-xr-x   1 <username>  staff   111B Jul 17 17:02 pydoc*
    lrwxr-xr-x   1 <username>  staff     7B Jul 17 17:03 python@ -> python2
    lrwxr-xr-x   1 <username>  staff    14B Jul 17 17:03 python-config@ -> python2-config
    lrwxr-xr-x   1 <username>  staff     9B Jul 17 17:03 python2@ -> python2.7
    lrwxr-xr-x   1 <username>  staff    16B Jul 17 17:03 python2-config@ -> python2.7-config
    -rwxr-xr-x   1 <username>  staff   2.5M Jul 17 17:02 python2.7*
    -rwxr-xr-x   1 <username>  staff   1.7K Jul 17 17:03 python2.7-config*
    -rwxr-xr-x   1 <username>  staff    18K Jul 17 17:02 smtpd.py*


    ~/.pyenv/versions/2.7.10/bin $ ll
    total 5136
    drwxr-xr-x  12 <username>  staff   408B Jul 17 11:33 ./
    drwxr-xr-x   6 <username>  staff   204B Jul 17 11:33 ../
    -rwxr-xr-x   1 <username>  staff   129B Jul 17 11:33 2to3*
    -rwxr-xr-x   1 <username>  staff   127B Jul 17 11:33 idle*
    -rwxr-xr-x   1 <username>  staff   112B Jul 17 11:33 pydoc*
    lrwxr-xr-x   1 <username>  staff     7B Jul 17 11:33 python@ -> python2
    lrwxr-xr-x   1 <username>  staff    14B Jul 17 11:33 python-config@ -> python2-config
    lrwxr-xr-x   1 <username>  staff     9B Jul 17 11:33 python2@ -> python2.7
    lrwxr-xr-x   1 <username>  staff    16B Jul 17 11:33 python2-config@ -> python2.7-config
    -rwxr-xr-x   1 <username>  staff   2.5M Jul 17 11:33 python2.7*
    -rwxr-xr-x   1 <username>  staff   1.7K Jul 17 11:33 python2.7-config*
    -rwxr-xr-x   1 <username>  staff    18K Jul 17 11:33 smtpd.py*

Contrast this with the pyenv installation of 3.4.3:

    ~/.pyenv/versions/3.4.3/bin $ ll
    total 14216
    drwxr-xr-x  71 <username>  staff   2.4K Jul 17 17:13 ./
    drwxr-xr-x   7 <username>  staff   238B Apr  8 14:52 ../
    lrwxr-xr-x   1 <username>  staff     8B Mar 17 15:58 2to3@ -> 2to3-3.4
    -rwxr-xr-x   1 <username>  staff   128B Mar 17 15:58 2to3-3.4*
    -rwxr-xr-x   1 <username>  staff   245B Mar 18 03:45 autopep8*
    lrwxr-xr-x   1 <username>  staff    16B Mar 17 15:58 easy_install@ -> easy_install-3.4
    -rwxr-xr-x   1 <username>  staff   268B Mar 17 15:58 easy_install-3.4*
    -rwxr-xr-x   1 <username>  staff   721B Mar 17 22:20 f2py*
    -rwxr-xr-x   1 <username>  staff   248B Mar 24 11:42 flake8*
    lrwxr-xr-x   1 <username>  staff     7B Mar 17 15:58 idle@ -> idle3.4
    lrwxr-xr-x   1 <username>  staff     7B Mar 17 15:58 idle3@ -> idle3.4
    -rwxr-xr-x   1 <username>  staff   126B Mar 17 15:58 idle3.4*
    -rwxr-xr-x   1 <username>  staff   301B Apr  8 14:52 ipcluster*
    -rwxr-xr-x   1 <username>  staff   301B Apr  8 14:52 ipcluster3*
    -rwxr-xr-x   1 <username>  staff   304B Apr  8 14:52 ipcontroller*
    -rwxr-xr-x   1 <username>  staff   304B Apr  8 14:52 ipcontroller3*
    -rwxr-xr-x   1 <username>  staff   300B Apr  8 14:52 ipengine*
    -rwxr-xr-x   1 <username>  staff   300B Apr  8 14:52 ipengine3*
    -rwxr-xr-x   1 <username>  staff   269B Apr  8 14:52 iptest*
    -rwxr-xr-x   1 <username>  staff   269B Apr  8 14:52 iptest3*
    -rwxr-xr-x   1 <username>  staff   262B Apr  8 14:52 ipython*
    -rwxr-xr-x   1 <username>  staff   262B Apr  8 14:52 ipython3*
    -rwxr-xr-x   1 <username>  staff   251B Mar 17 22:21 jsonschema*
    -rwxr-xr-x   1 <username>  staff   249B Apr  8 14:52 nosetests*
    -rwxr-xr-x   1 <username>  staff   249B Apr  8 14:52 nosetests-3.4*
    -rwxr-xr-x   1 <username>  staff   249B Mar 17 16:14 pbr*
    -rwxr-xr-x   1 <username>  staff   118B Mar 27 12:59 pep257*
    -rwxr-xr-x   1 <username>  staff   243B Mar 24 11:42 pep8*
    -rwxr-xr-x   1 <username>  staff   237B Jul 17 11:05 pip*
    -rwxr-xr-x   1 <username>  staff   237B Jul 17 11:05 pip3*
    -rwxr-xr-x   1 <username>  staff   237B Jul 17 11:05 pip3.4*
    -rwxr-xr-x   1 <username>  staff   325B Mar 17 22:21 pybabel*
    lrwxr-xr-x   1 <username>  staff     8B Mar 17 15:58 pydoc@ -> pydoc3.4
    lrwxr-xr-x   1 <username>  staff     8B Mar 17 15:58 pydoc3@ -> pydoc3.4
    -rwxr-xr-x   1 <username>  staff   111B Mar 17 15:58 pydoc3.4*
    -rwxr-xr-x   1 <username>  staff   249B Mar 24 11:42 pyflakes*
    -rwxr-xr-x   1 <username>  staff   253B Mar 17 22:21 pygmentize*
    lrwxr-xr-x   1 <username>  staff     9B Mar 17 15:58 python@ -> python3.4
    lrwxr-xr-x   1 <username>  staff    16B Mar 17 15:58 python-config@ -> python3.4-config
    lrwxr-xr-x   1 <username>  staff     9B Mar 17 15:58 python3@ -> python3.4
    lrwxr-xr-x   1 <username>  staff    16B Mar 17 15:58 python3-config@ -> python3.4-config
    -rwxr-xr-x   2 <username>  staff   3.3M Mar 17 15:58 python3.4*
    lrwxr-xr-x   1 <username>  staff    17B Mar 17 15:58 python3.4-config@ -> python3.4m-config
    -rwxr-xr-x   2 <username>  staff   3.3M Mar 17 15:58 python3.4m*
    -rwxr-xr-x   1 <username>  staff   2.0K Mar 17 15:58 python3.4m-config*
    lrwxr-xr-x   1 <username>  staff    10B Mar 17 15:58 pyvenv@ -> pyvenv-3.4
    -rwxr-xr-x   1 <username>  staff   263B Mar 17 15:58 pyvenv-3.4*
    -rwxr-xr-x   1 <username>  staff   629B Mar 17 22:21 rst2html.py*
    -rwxr-xr-x   1 <username>  staff   826B Mar 17 22:21 rst2latex.py*
    -rwxr-xr-x   1 <username>  staff   635B Mar 17 22:21 rst2man.py*
    -rwxr-xr-x   1 <username>  staff   799B Mar 17 22:21 rst2odt.py*
    -rwxr-xr-x   1 <username>  staff   1.7K Mar 17 22:21 rst2odt_prepstyles.py*
    -rwxr-xr-x   1 <username>  staff   636B Mar 17 22:21 rst2pseudoxml.py*
    -rwxr-xr-x   1 <username>  staff   672B Mar 17 22:21 rst2s5.py*
    -rwxr-xr-x   1 <username>  staff   821B Mar 17 22:21 rst2xetex.py*
    -rwxr-xr-x   1 <username>  staff   637B Mar 17 22:21 rst2xml.py*
    -rwxr-xr-x   1 <username>  staff   705B Mar 17 22:21 rstpep2html.py*
    -rwxr-xr-x   1 <username>  staff    16K Mar 24 11:01 runxlrd.py*
    -rwxr-xr-x   1 <username>  staff   250B Mar 17 22:21 sphinx-apidoc*
    -rwxr-xr-x   1 <username>  staff   268B Mar 17 22:21 sphinx-autogen*
    -rwxr-xr-x   1 <username>  staff   243B Mar 17 22:21 sphinx-build*
    -rwxr-xr-x   1 <username>  staff   254B Mar 17 22:21 sphinx-quickstart*
    -rwxr-xr-x   1 <username>  staff   317B Mar 17 16:18 tox*
    -rwxr-xr-x   1 <username>  staff   339B Mar 17 16:18 tox-quickstart*
    -rwxr-xr-x   1 <username>  staff   247B Mar 17 16:14 virtualenv*
    -rwxr-xr-x   1 <username>  staff   247B Mar 17 16:14 virtualenv-3.4*
    -rwxr-xr-x   1 <username>  staff   382B Mar 17 16:14 virtualenv-clone*
    -rwxr-xr-x   1 <username>  staff    38K Mar 17 16:14 virtualenvwrapper.sh*
    -rwxr-xr-x   1 <username>  staff   2.0K Mar 17 16:14 virtualenvwrapper_lazy.sh*
    -rwxr-xr-x   1 <username>  staff   244B Jul 17 11:05 wheel*
    -rwxr-xr-x   1 <username>  staff   311B Apr  6 11:32 x_x*

**Comment by yyuu** [comment]
@jackmaney Looks weird :disappointed: It is working fine for me with Homebrew's Python 2.7.

Can you try to reinstall 2.7.x by `pyenv install -v 2.7.x 2>&1` and create a gist from it?

**Comment by yyuu** [comment]
@jackmaney I confirmed the reproduction of the issue with existence of `~/.local/lib/python2.7/site-packages/homebrew.pth` as `import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")`. Now I'm looking for some workaround....

**Comment by yyuu** [comment]
@jackmaney I believe the following branch should fix the issue. Can you try rebuilding 2.7.9 or 2.7.10?

https://github.com/yyuu/pyenv/compare/issue411

**Comment by jackmaney** [comment]
The issue is on my work laptop, so I'll try it tomorrow or Monday and report the results. Thank you for looking into this.

**Comment by jackmaney** [comment]
After doing a bit of digging, I discovered that the `python-build` plugin was symlinked to an old version of `pyenv` (over a month old). So, after uninstalling all versions of `pyenv` via Homebrew, reinstalling, and then manually applying the changes above, things are now working.

Thanks!
