### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by avenet** [yyuu/pyenv#416]
I've been using pyenv and I think it's awesome, this is the kind of tool I've been waiting for so long!! Unfortunately ;) I have to work on a regular basis using Windows and I'd love a tool like this for Windows.

Have you thought about this feature?
Wouldn't it make sense to add this package for Windows (understanding it'd be really challenging)?

Thank you very much,

**Comment by yyuu** [comment]
Windows doesn't have bash by default
