### ISSUE TITLE
Build failed when $ sudo pyenv install 2.7.9

### ISSUE THREAD

**Issue by AttoLee** [yyuu/pyenv#418]
NAME
patching file ./Lib/site.py
Installing setuptools from https://bootstrap.pypa.io/ez_setup.py...
Installing pip from https://bootstrap.pypa.io/get-pip.py...
curl: (18) transfer closed with 857193 bytes remaining to read
error: failed to install pip via get-pip.py

BUILD FAILED (OS X 10.10.4 using python-build 20150326-498-g5402ce4)

Inspect or clean up the working tree at /tmp/python-build.20150730092617.29954
Results logged to /tmp/python-build.20150730092617.29954.log

Last 10 log lines:
Installing easy_install script to /Users/apple/.pyenv/versions/2.7.9/bin
Installing easy_install-2.7 script to /Users/apple/.pyenv/versions/2.7.9/bin

Installed /Users/apple/.pyenv/versions/2.7.9/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg
Processing dependencies for setuptools==18.0.1
Finished processing dependencies for setuptools==18.0.1
  File "/tmp/python-build.20150730092617.29954/get-pip.py", line 7048
    w#dyy3jdWw9j$g?d@OhQ^E->;%2kfp-gMnA68@}e3=_oGpkE@6Eok@6@n<S&zam#erIB(9cHnVY>Hb
                                                                                 ^
SyntaxError: EOF while scanning triple-quoted string literal

**Comment by yyuu** [comment]
Probably you had problem downloading file from https://bootstrap.pypa.io/get-pip.py at that time. I couldn't reproduce this.
