### ISSUE TITLE
Avoid dangling shims

### ISSUE THREAD

**Issue by saj** [yyuu/pyenv#420]
The `python2` shim that pyenv installs can result in surprising (and undesirable) behaviour under some circumstances.

Given the following set of Python runtimes:

    % pyenv versions
    * system (set by /Users/saj/.pyenv/version)
      2.7.10

`pyenv rehash` will install shims for `python`, `python2`, and `python2.7`.

    % ls ~/.pyenv/shims | egrep 'python[0-9\.]*$'
    python
    python2
    python2.7

Suppose we leave system `python` enabled globally.

    % pyenv global
    system

System `python` on my platform, OS X 10.10, is 2.7.6.

    % /usr/bin/python -V
    Python 2.7.6

OS X provides `python` and `python2.7` files that link to this interpreter.  More importantly, OS X does *not* provide a `python2` link.

    % pyenv which python
    /usr/bin/python

    % pyenv which python2.7
    /usr/bin/python2.7

    % pyenv which python2
    pyenv: python2: command not found

    The `python2' command exists in these Python versions:
      2.7.10

With pyenv's shims loaded into my `PATH`, trying to invoke `python2` results in a failure:

    % python2 -V
    pyenv: python2: command not found

    The `python2' command exists in these Python versions:
      2.7.10

This causes obvious problems for software that probe for `python2` before `python`.  The [ycmd](https://github.com/Valloric/ycmd/) code completion server is one such example:

https://github.com/Valloric/ycmd/blob/master/ycmd/utils.py#L154

The problem can be worked-around by manually symlinking `/usr/bin/python2` to `/usr/bin/python`, though this is rather smelly.

I take it the shims are built from the set union of all installed Python versions.  Because I have 2.7.10 installed, pyenv found `python2` in my 2.7.10 `bin/` directory and created the `python2` shim to match.

Why is this search based on the set of *installed* runtimes and not the set of *activated* runtimes?  (Would it make more sense to rehash after `pyenv global` instead of `pyenv install`?)

https://github.com/yyuu/pyenv/blob/8e276a009e592724ae9804cff328baee3a23df20/README.md#choosing-the-python-version

    % pyenv global system 2.7.10

    % pyenv global
    system
    2.7.10

    % python -V
    Python 2.7.6

    % python2 -V
    Python 2.7.10

    % python2.7 -V
    Python 2.7.6

**Comment by yyuu** [comment]
This is by design and is not easily avoidable. If the behaviour is unacceptable, I'd recommend you to build PATH by yourself.
