### ISSUE TITLE
OSX 10.10.4 pyenv install 3.4.3 fails

### ISSUE THREAD

**Issue by weems** [yyuu/pyenv#423]
/var/folders/bc/cmnr0l6n1vb76p28m_4vlwh00000gn/T/python-build.20150808103445.31774/Python-3.4.3 /var/folders/bc/cmnr0l6n1vb76p28m_4vlwh00000gn/T/python-build.20150808103445.31774 ~
checking build system type... x86_64-apple-darwin14.4.0
checking host system type... x86_64-apple-darwin14.4.0
checking for --enable-universalsdk... no
checking for --with-universal-archs... no
checking MACHDEP... darwin
checking for --without-gcc... no
checking for gcc... /usr/local/bin/gcc-4.2
checking whether the C compiler works... no
configure: error: in `/var/folders/bc/cmnr0l6n1vb76p28m_4vlwh00000gn/T/python-build.20150808103445.31774/Python-3.4.3':
configure: error: C compiler cannot create executables
See `config.log' for more details
make: *** No targets specified and no makefile found.  Stop.

**Comment by yyuu** [comment]
You have trouble to create executables. Please make sure Command Line Tools for Xcode is properly installed and is working. This isn't an issue of pyenv.
