### ISSUE TITLE
Python 2.7.10: undefined symbol: PyUnicodeUCS4_AsUTF8String

### ISSUE THREAD

**Issue by bmcorser** [yyuu/pyenv#425]
Not sure if this is a pyenv issue, but posting here anyhoo. There [seems](http://bytes.com/topic/python/answers/44374-undefined-symbol-pyunicodeucs4_asutf8string) some issue regarding unicode representations.

```
$ pyenv versions
  system
* 2.7.10 (set by /home/ben/.pyenv/version)
  2.7.8
$ python -c 'from psycopg2.extras import NumericRange'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ben/.pyenv/versions/2.7.10/lib/python2.7/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import BINARY, NUMBER, STRING, DATETIME, ROWID
ImportError: /home/ben/.pyenv/versions/2.7.10/lib/python2.7/site-packages/psycopg2/_psycopg.so: undefined symbol: PyUnicodeUCS4_AsUTF8String
```

Any advices?

**Comment by bmcorser** [comment]
One [more](http://stackoverflow.com/questions/22450848/error-loading-psycopg2-module-when-installed-from-a-wheel) google away suggests this could be related to how I am installing psycopg2 (I used `pip install pyscopg2`)

**Comment by bmcorser** [comment]
Ah -- I think this is actually a [known psycopg2 issue](https://github.com/psycopg/psycopg2/issues/230), since Pip installs from wheels (pre-compiled packages, AFAIK) so the error makes a little more sense. If I install from sauce, things seem OK:
```
$ pip uninstall psycopg2
$ git clone https://github.com/psycopg/psycopg2
$ cd psycopg2
$ python setup.py build
$ python setup.py install
$ python -c 'from psycopg2.extras import NumericRange'
$ echo $?
0
```

**Comment by twig** [comment]
Thanks for that @bmcorser, that solved my issues with UCS4.

**Comment by Harrison0x80** [comment]
> Ah -- I think this is actually a [known psycopg2 issue](https://github.com/psycopg/psycopg2/issues/230), since Pip installs from wheels (pre-compiled packages, AFAIK) so the error makes a little more sense. If I install from sauce, things seem OK:
> 
> ```
> $ pip uninstall psycopg2
> $ git clone https://github.com/psycopg/psycopg2
> $ cd psycopg2
> $ python setup.py build
> $ python setup.py install
> $ python -c 'from psycopg2.extras import NumericRange'
> $ echo $?
> 0
> ```

thanks a lot, I rebuild myself then slove the problem.

**Comment by Iva-khar** [comment]
> Ah -- I think this is actually a [known psycopg2 issue](https://github.com/psycopg/psycopg2/issues/230), since Pip installs from wheels (pre-compiled packages, AFAIK) so the error makes a little more sense. If I install from sauce, things seem OK:
> 
> ```
> $ pip uninstall psycopg2
> $ git clone https://github.com/psycopg/psycopg2
> $ cd psycopg2
> $ python setup.py build
> $ python setup.py install
> $ python -c 'from psycopg2.extras import NumericRange'
> $ echo $?
> 0
> ```

Thanks @bmcorser
