### ISSUE TITLE
pyenv versions like this on mac yosemite ,why?

### ISSUE THREAD

**Issue by gatspy** [yyuu/pyenv#426]
i install python with brew,then install pyenv, but don't install any python version with pyenv.
using pyenv versions in terminal :
$ pyenv versions
* system (set by /usr/local/opt/pyenv/version)

**Comment by thomasjo** [comment]
That output is exactly as expected; it's telling you the current python is set to your system python. If Homebrew is correctly configured on your system then the output of `pyenv which python` should point to the Python you installed via Homebrew.

**Comment by yyuu** [comment]
As @thomasjo described, it is totally expected behaviour that it means you have some system python. No bug.
