### ISSUE TITLE
[SOLVED] Cannot make pyenv work properly

### ISSUE THREAD

**Issue by TonioGela** [yyuu/pyenv#427]
Hi! I'm new on GitHub so I don't know if now if I'm violating some rule writing this post.
So, I'm on Mac OSX 10.9.5 Mavericks, I have installed homebrew, and I had just the system python (that is a 2.7.5) but since I need both 2.7.10 and 3.4.3 for thesis work I decided to use pyenv.
Using homebrew I installed pyenv
`[toniogela] ~ $ brew install pyenv`
I added these 2 lines (as suggested by brew info pyenv):
```if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi```
```export PYENV_ROOT=/usr/local/var/pyenv```
to my `~/.bash_profile` (that is extra full of aliases, so I even tried to use an empy file and add JUST these 2 lines) and I tried to use it:
```
[toniogela] ~ $ pyenv install 2.7.10
[toniogela] ~ $ pyenv install 3.4.3
[toniogela] ~ $ pyenv rehash
```
the installations had succeded (I do not have the log, sorry) but when I tried to use it the result was this:
```
[toniogela] ~ $ python --version
Python 2.7.5
[toniogela] ~ $ pyenv versions
 *system
  2.7.10 (set by /Users/toniogela/.python-version)
  3.4.3
[toniogela] ~ $ pyenv local 2.7.10
[toniogela] ~ $ pyenv rehash
[toniogela] ~ $ pyenv versions
  system
* 2.7.10 (set by /Users/toniogela/.python-version)
  3.4.3
[toniogela] ~ $ python --version
Python 2.7.5
```
I read a lot of thread opened here, so I tried a lot of commands like:
```
[toniogela] ~ $ echo $PATH
/Users/toniogela/.pyenv/shims:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
[toniogela] ~ $ echo $PYENV_ROOT
/usr/local/var/pyenv
[toniogela] ~ $ which pyenv
/usr/local/bin/pyenv
[toniogela] ~ $ pyenv local 2.7.10
[toniogela] ~ $ which python
/usr/bin/python
```
but their output was exactly like it had to be (as far as I understood reading the posts).
I even tried to entirely reinstall the OS after formatting the HD but the result with a virgin OS was the same.
So I'm asking you, what I have to do to make it work?
(If this is not the place to ask these type of questions tell me where and whom to ask)
P.S. Using `brew deps pyenv` give no problems, I have all the needed dependencies and `brew doctor` tells me my system is ready to brew.
`pyenv version is 20150719` `Homebrew version is 3cbd4292' ' OSX is 10.9.5 Build 13F1112`

**Comment by TonioGela** [comment]
Apparently everything was solved reinstalling for the 10th time, using this settings in the `.bash_profile`:
```
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
```
after removing the `~/.pyenv` folder.
Also, I suggest using this alias `alias brew="env PATH=${PATH/\/Users\/(yourusername)\/\.pyenv\/shims:/} brew"` to remove this kind of warnings when running `brew doctor`:
```
Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:

  /Users/toniogela/.pyenv/shims/python-config
  /Users/toniogela/.pyenv/shims/python2-config
  /Users/toniogela/.pyenv/shims/python2.7-config
  /Users/toniogela/.pyenv/shims/python3-config
  /Users/toniogela/.pyenv/shims/python3.4-config
  /Users/toniogela/.pyenv/shims/python3.4m-config
```
Peace!

**Comment by yyuu** [comment]
:+1:
