### ISSUE TITLE
Add support for PyPy-STM

### ISSUE THREAD

**Issue by thedrow** [yyuu/pyenv#428]
Right now PyPy-STM versions cannot be installed using pyenv.
I'd love to have those easily available in my system for testing purposes.

**Comment by yyuu** [comment]
Gimme some patch.

**Comment by yyuu** [comment]
I found there're some PyPy-STM binaries on https://bitbucket.org/pypy/pypy/downloads/. It would be easy to add definitions for them.

**Comment by thedrow** [comment]
Thanks!
