### ISSUE TITLE
Ubuntu 14.04 pyenv install failed.

### ISSUE THREAD

**Issue by CaptainFeng** [yyuu/pyenv#430]
I tried to install python version 2.7.9 by pyenv. But I failed.
Following is result log:
`checking for gettimeofday... yes`
`checking for major...yes`
`checking for getaddrinfo...yes`
`checking getaddrinfo bug...yes`
`Fatal: You must get working getaddrinfo() function.
       or you can specify "--disable-ipv6".`

I used Ubuntu 14.04 in Parallels Desktop of my mac & pyenv's version is 20150719.
Please help me to figure this out.
Thanks.

**Comment by richiverse** [comment]
Having seperate issue in ubuntu 14.04

```bash
Downloading Python-3.5.0.tgz...
-> https://yyuu.github.io/pythons/584e3d5a02692ca52fce505e68ecd77248a6f2c99adf9db144a39087336b0fe0
Installing Python-3.5.0...

BUILD FAILED (Ubuntu 14.04 using python-build 20150204-589-gc452da8)

Inspect or clean up the working tree at /tmp/user/1000/python-build.20150914223747.5925
Results logged to /tmp/user/1000/python-build.20150914223747.5925.log

Last 10 log lines:
 }
 ^
compilation terminated.
make: *** [Modules/_collectionsmodule.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Modules/itertoolsmodule.o] Error 1
The bug is not reproducible, so it is likely a hardware or OS problem.
make: *** [Modules/_sre.o] Error 1
The bug is not reproducible, so it is likely a hardware or OS problem.
make: *** [Objects/unicodeobject.o] Error 1
```

**Comment by yyuu** [comment]
I'm not sure why `getaddrinfo()` isn't working on your system, but apparently networking on your system isn't configured properly.

As workaround, as you can see in the error message, try specifying `--disable-ipv6` as a configure option.

```sh
$ PYTHON_CONFIGURE_OPTS="--disable-ipv6" pyenv install -v 2.7.9
```

**Comment by CaptainFeng** [comment]
I guess because I used proxychains as a proxy to download python version.

**Comment by kk17** [comment]
I have the same problem when installing with proxychains.

**Comment by intsilence** [comment]
Same problem with proxychains, thanks!

**Comment by LittleKey** [comment]
Same problem, thx

**Comment by shrmrf** [comment]
It fails on `Windows Subsystem for Linux` or `bash on Windows 10` too. I guess because the subsystem does not have access to the lower level functions...

**Comment by turtleizzy** [comment]
Same problem with proxychains, solved by specifying PYTHON_CONFIGURE_OPTS, thanks!

**Comment by RGD2** [comment]
+1 proxychains and fixed! Thanks!

**Comment by JunJianX** [comment]
> I guess because I used proxychains as a proxy to download the python version.

you saved my life! I struggled for this for a whole day!
