### ISSUE TITLE
pyenv: version is not installed

### ISSUE THREAD

**Issue by lostinplace** [yyuu/pyenv#431]
I'm running pyenv on OSX (installed with homebrew)

It's refusing to run any version of python other than 3.4.3

```bash
➜  ~  pyenv versions
  system
* 2.7.10 (set by /Users/cwheeler/.python-version)
  2.7.9
  3.4.3
➜  ~  python --version
pyenv: version '2.7.10' is not installed
➜  ~  pyenv local 3.4.3
➜  ~  python --version
Python 3.4.3
➜  ~  pyenv local 2.7.10
➜  ~  python --version
pyenv: version '2.7.10' is not installed
➜  ~
```

I'm kind of stumped on where to look to debug this, any ideas?

**Comment by jiucai** [comment]
use the following command to set version:
```
pyenv shell 2.7.10
```

**Comment by yyuu** [comment]
I couldn't reproduce such behaviour. Probably you have stale shim scripts in `~/.pyenv/shims/*` after you moved `~/.pyenv` from other place or doing something. Please run `pyenv rehash` and then try again.
