### ISSUE TITLE
pip broken when update pip itself

### ISSUE THREAD

**Issue by zheduanyin** [yyuu/pyenv#432]
I was using Mac + brew + pyenv + python3.4.3 with pip v7.10 and everything is cool until I upgraded pip to v7.12.
I get error like this when `pip` is called after the upgrade :
```
pyenv: pip: command not found

The `pip' command exists in these Python versions:
  2.7.9
```
Any idea?

**Comment by yyuu** [comment]
It might be depending on how you've upgraded pip. Anyway try 'pyenv rehash' and check how it goes.

**Comment by zheduanyin** [comment]
Pip was updated with:
```
pip install --upgrade pip
```

I tried `pyenv rehash` and it gave me nothing.

**Comment by yyuu** [comment]
Please check if `pyenv which pip` returns the path to `pip` executable or not. If it's still not working, please let me know the output from `pyenv whence pip2.7` and `pyenv versions`

**Comment by zheduanyin** [comment]
Here's `pyenv which pip`
```
yenv which pip
pyenv: pip: command not found

The `pip' command exists in these Python versions:
  2.7.9
```
And `pyenv whence pip2.7`:
```
2.7.9
```
And `pyenv versions` gives:
```
  system
  2.7.9
* 3.4.3
```

There's no `pip3` at all in `.pyenv/versions/3.4.3`:
```
~/.pyenv/shims ls -l | grep pip
-rwxr-xr-x  75 aaa  staff  419  9  1 14:27 pip
-rwxr-xr-x  75 aaa  staff  419  9  1 14:27 pip2
-rwxr-xr-x  75 aaa  staff  419  9  1 14:27 pip2.7
```

**Comment by zheduanyin** [comment]
I tested upgrading `pip` under python verison 2.7.9 with
```
pip install --upgrade pip
```
 and it gave me a success upgrade, i.e. pip is callable.

**Comment by zheduanyin** [comment]
Thank you yyuu :), I reinstalled python 3.4.3 and everything is fine now.
