### ISSUE TITLE
Release with PyPy 2.6.1?

### ISSUE THREAD

**Issue by dstufft** [yyuu/pyenv#433]

**Comment by joshfriend** [comment]
I was waiting on squeaky-pl/portable-pypy#17 so that [these `TODO`s](https://github.com/yyuu/pyenv/blob/c9268bb0dc62ffacc8dbc0e40e3da07e041ccab1/plugins/python-build/share/python-build/pypy-2.6.1#L6) could be resolved.

If you'd like a new tag sooner, I'm sure that wouldn't be a problem :)

**Comment by joshfriend** [comment]
@dstufft:

* https://github.com/yyuu/pyenv/releases/tag/v20150901
* Homebrew/homebrew#43478

**Comment by yyuu** [comment]
:+1:
