### ISSUE TITLE
Missing a mailinglist

### ISSUE THREAD

**Issue by COLABORATI** [yyuu/pyenv#436]
Hi, I am missing a mailing list for pyenv - I would like to ask some related questions, but these are not exactly bugs or issues - a mailing list seems appropriate for that, but I can not find one. 

Please consider using the free librelist.com service or at least a google group to enhance the community experience, thank you very much for this great tool!

**Comment by blueyed** [comment]
Maybe stackoverflow would work for this?
We could also use the wiki/doc for that, too.

**Comment by COLABORATI** [comment]
A mailing list is not an FAQ site, also a wiki is something different. I am missing the possibility to just ask anything on a list and read interesting discussions by pyenv users. However, I may ask just right here while I am at it: 

I find pyenv to be a really convenient tool, because it (besides other things) helps me to avoid having too many virtualenvs. Usually I just pip install stuff into the pyenv activated python environment - without a virtualenv - and everything works. 

But there are some pieces of software where this does not work and some modules are missing, but in a (pyenv) virtualenv they still work. An example is the [krill newsreader] (https://github.com/p-e-w/krill) - doing a `pip install krill` in a "pure" pyenv environment (no virtualenv) installs this, but executing krill does not work: 
```
user@ubuntu$ krill
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/2.7.9/bin/krill", line 7, in <module>
    from krill.krill import main
  File "/home/user/.pyenv/versions/2.7.9/lib/python2.7/site-packages/krill/krill.py", line 31, in <module>
    from blessings import Terminal
  File "/home/user/.pyenv/versions/2.7.9/lib/python2.7/site-packages/blessings/__init__.py", line 5, in <module>
    import curses
  File "/home/user/.pyenv/versions/2.7.9/lib/python2.7/curses/__init__.py", line 15, in <module>
    from _curses import *
ImportError: No module named _curses
```

When I create a virtualenv, then there are no problems and krill executes without problems.

Why is that happening? I guess something related to the sys.path, but I do not understand exactly, why things do not work in a "pure" pyenv environment without virtualenv, but do work in the same pyenv environment within a virtualenv. 

This is not related to any real life problem - I just want to understand what happens here.

Thanks for your attention!

**Comment by yyuu** [comment]
I don't like it. Use SO. It's 2015.

**Comment by joshfriend** [comment]
> I don't like it. Use SO. It's 2015.

I don't like them either. If anything it should be [Gitter](https://gitter.im)

**Comment by yyuu** [comment]
Okay. Anyway we don't have enough eyes and hands to handle requests from users. Just expanding communication channel must not be the solution for it.

**Comment by COLABORATI** [comment]
It's the other way around - giving the community a place to grow is the first step to getting enough eyes and hands - a mailinglist is the premier place to let that happen. This project is currently stared by 3000 people - these people have no way to freely communicate, so no community can grow.

A wiki, a FAQ site and an issue tracker are specialized tools for organizing certain aspects of software work, but for free communication a mailing list is needed. 

Please also see http://www.appsembler.com/blog/10-things-every-open-source-project-should-have/

However, I am happy you did not write "Let's make a facebook group, it's 2015" :)

**Comment by jimmywan** [comment]
Just an opinion from the cheap seats, but the **last** thing I want is more email.

**Comment by yyuu** [comment]
Anyone can start hosting ML, chat rooms, or something alike by themselves. I will authorize it if there's no special reason and will put a link to it in README.
