### ISSUE TITLE
The path of anaconda 's .sh is wrong?

### ISSUE THREAD

**Issue by kasajei** [yyuu/pyenv#438]
I try to install anaconda `pyenv install anaconda3-2.1.0`

However my console says
```
Downloading Anaconda3-2.1.0-MacOSX-x86_64.sh...
-> http://repo.continuum.io/anaconda3/Anaconda3-2.1.0-MacOSX-x86_64.sh
error: failed to download Anaconda3-2.1.0-MacOSX-x86_64.sh

BUILD FAILED (OS X 10.10.4 using python-build 20150818)
```

I think the path of anaconda's .sh is wrong and the collect path is http://repo.continuum.io/archive/Anaconda3-2.1.0-MacOSX-x86_64.sh

Would you check it?

**Comment by yyuu** [comment]
#439  should solve this.
