### ISSUE TITLE
setuptools must be installed while installing pip (2.6.9) (OS X 10.11 GM Candidate)

### ISSUE THREAD

**Issue by bertjwregeer** [yyuu/pyenv#441]
Collecting pip
    /var/folders/_l/cx3x95zs4yn6kb1ndy03yrzm0000z9/T/tmpotj6Y8/pip.zip/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
      Downloading pip-7.1.2-py2.py3-none-any.whl (1.1MB)
    Collecting setuptools
      Downloading setuptools-18.3.1-py2.py3-none-any.whl (462kB)
    Collecting wheel
      Downloading wheel-0.24.0-py2.py3-none-any.whl (63kB)
    Collecting argparse (from wheel)
      Downloading argparse-1.4.0.tar.gz (70kB)
    setuptools must be installed to install from a source distribution

This seems to be some sort of circular dependency issue...

**Comment by robobario** [comment]
I have the same problem with OS X 10.10, pyenv v20150913

I got 2.6.9 installed by rolling pyenv back to tags/v20150404. It looks like it runs a setuptools bootstrap before the pip bootstrap.

**Comment by yyuu** [comment]
@bertjwregeer Which Python version were you using?

**Comment by bertjwregeer** [comment]
Python 2.6.9.

**Comment by yyuu** [comment]
I couldn't reproduce the error with 2.6.9 on Raspbian. I'll try on OS X later. Anyway, this could be some dependency issue of `pip` (or, `argparse`?).

**Comment by bertjwregeer** [comment]
This seems to indeed be fixed:

    alexandra:~ xistence$ brew link --force openssl
    Linking /usr/local/Cellar/openssl/1.0.2d_1... ^[[A^[[A1548 symlinks created
    alexandra:~ xistence$ pyenv install 2.6.9
    Downloading Python-2.6.9.tgz...
    -> https://yyuu.github.io/pythons/7277b1285d8a82f374ef6ebaac85b003266f7939b3f2a24a3af52f9523ac94db
    Installing Python-2.6.9...
    patching file setup.py
    Hunk #1 succeeded at 354 (offset 9 lines).
    patching file ./configure
    patching file ./Modules/readline.c
    Hunk #1 succeeded at 199 (offset -7 lines).
    Hunk #2 succeeded at 698 (offset -51 lines).
    Hunk #3 succeeded at 808 (offset -51 lines).
    Hunk #4 succeeded at 848 with fuzz 2 (offset -70 lines).
    patching file ./setup.py
    Hunk #1 succeeded at 1698 (offset 23 lines).
    Installing pip from https://bootstrap.pypa.io/get-pip.py...
    Installed Python-2.6.9 to /Users/xistence/.pyenv/versions/2.6.9

**Comment by yyuu** [comment]
Good to know :)

**Comment by yyuu** [comment]
Reverting fe934642c51d2a3c76bff6eb4728e091fc530daf would revert the python-build behaviour to install `setuptools` separately from `pip`. I believe this is a kind of misconfiguration of `pip` package and its dependencies, and it has already been resolved.

I'd like to keep current behaviour since there's no problem with it for now. I'll revert the changes in python-build once similar issue happened again.
