### ISSUE TITLE
Could not find a way to install from source.

### ISSUE THREAD

**Issue by huntzhan** [yyuu/pyenv#445]
I want to use `pyenv install` in a environment without internet, and I couldn't find a way to install specific python version, say `2.7.10`, from a `*.zip` source.

It's there a way to solve this problem?

**Comment by yyuu** [comment]
If there's cache files in '~/.pyenv/cache', pyenv will use it instead of downloading it. Though 'ensurepip' tries to download install pip and its dependencies via internet.

**Comment by yyuu** [comment]
I confirmed that I could install CPython without internet connection with cache files.

```
$ mkdir -p "$(pyenv root)/cache"
$ wget -O "$(pyenv root)/cache/Python-2.7.10.tgz" https://www.python.org/ftp/python/2.7.10/Python-2.7.10.tgz
$ wget -O "$(pyenv root)/cache/get-pip.py" https://bootstrap.pypa.io/get-pip.py
$ pyenv install -v 2.7.10
```

**Comment by huntzhan** [comment]
It works! thx.

**Comment by huntzhan** [comment]
@yyuu I've run a few tests on different python versions, and found out that above method doesn't work for `2.6.9`. After `patching file ./setup.py`, the program would still try to download `get-pip.py` from the internet.

**Comment by yyuu** [comment]
You would need internet connections for the versions without `ensurepip`.

**Comment by huntzhan** [comment]
Thx. Installing Python 2.* offline is just like nightmare.

**Comment by yyuu** [comment]
Preparing some great-firewall-ready CDN might be good for pyenv users especially in China. I'm not sure which service is good for the purpose & how much does it costs.... Any insights?

**Comment by huntzhan** [comment]
It's not a GFW related problem. Under the consideration of security, Internet accessing is forbidden in our production environment. Hence, I have to find a way to install all Python related stuffs offline, including specific Python versions, virtualenvs and PyPI distributions.

By the way, I've kind of solve above Python 2.6.* installing problem, by just waiting for curl's timeout and then patch `setuptools\pip\...` manually.
