### ISSUE TITLE
Add `pyenv list` and `pyenv ls` as aliases of `pyenv versions`

### ISSUE THREAD

**Issue by elgalu** [yyuu/pyenv#446]
Principle of least surprise; it would be nice to add

    pyenv list

As an alias of

    pyenv versions

Similar tools have that action:
* [rvm](https://github.com/rvm/rvm) for Ruby version management
* [nvm](https://github.com/creationix/nvm) for NodeJS version management

Both support the **list** and even the **ls** shorter alias, so bonus point for:

    pyenv ls

**Comment by yyuu** [comment]
Basically I don't like to have duplications. If you really want such feature, you can write a plugin to add subcommand.

https://github.com/yyuu/pyenv/wiki/Authoring-plugins
