### ISSUE TITLE
3.1-dev missing in Ubuntu

### ISSUE THREAD

**Issue by mcandre** [yyuu/pyenv#449]
pyenv offers 3.1-dev on Mac OS X, but 3.1-dev appears to be missing when pyenv is used on Ubuntu.

**Comment by yyuu** [comment]
python-build will show all the versions in $(pyenv root)/plugins/python-build/share/python-buuld regardless current platform type. Please check output of 'pyenv --version' between them.

**Comment by yyuu** [comment]
I deleted 3.1-dev from pyenv in 78c1d7186d38d2f4ac3a6361ff431f7760a0625b#diff-829bd38e9096ee1ba2d562d4b79d392a since the branch for 3.1 is no longer available on CPython repo. Probably you are using older version of pyenv on OS X.
