### ISSUE TITLE
pyenv not able to pickup packages from system if not present in local 

### ISSUE THREAD

**Issue by ashishnegi** [yyuu/pyenv#452]
First of all, thanks for this project. It's awesome.

I have a python package `pyatspi` (python3-pyatspi) installed using `sudo apt-get install python3-pyatspi`.
This package is available through :
```
sudo apt-add-repository ppa:vinux/trusty
sudo apt-add-repository ppa:vinux/trusty-proposed
```
In the code directory,
these are the commands that i run :
```
ashish:orca$ which python3
/home/ashish/.pyenv/shims/python3
ashish:orca$ python3 -V
Python 3.4.3
ashish:orca$ pyenv versions
* system (set by /home/ashish/Documents/ashish/accessibility/orca/.python-version)
  2.7.10
  3.4.3
  orca-env
ashish:orca$ python3 -c "import pyatspi"
ashish:orca$ pyenv local orca-env 
pyenv-virtualenv: activate orca-env
(orca-env) ashish:orca$ python3 -V
Python 3.4.3
(orca-env) ashish:orca$ which python3
/home/ashish/.pyenv/versions/orca-env/bin/python3
(orca-env) ashish:orca$ python3 -c "import pyatspi"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'pyatspi'
(orca-env) ashish:orca$ pyenv versions
  system
  2.7.10
  3.4.3
* orca-env (set by /home/ashish/Documents/ashish/accessibility/orca/.python-version)
```
As you can see, i am not able to run the program with my virtual-environment `orca-env` but have to use `system` environment.

Can this issue be solved ? I want to work in a local environment.
Is there a work around ?

**Comment by yyuu** [comment]
@ashishnegi 
At first, you have to make sure if `orca-env` is a virtualenv created from Python 3.x of your `system` with `--system-site-packages`. I suspect you created the virtualenv from Python 2.x of your `system`.

You can check virtualenv's parent by `python -c 'import sys;print(sys.real_prefix)'` (or, `python -c 'import sys;print(sys.base_prefix)'` if the virtualenv is actually created by `pyvenv`). You would be also check if the virtualenv is created with `--system-site-packages` by absent of `${virtualenv_prefix}/lib/pythonX.Y/no-global-site-packages.txt`.

Even if there is something wrong in pyenv and derivatives, this must be an issue of [pyenv-virtualenv](https://github.com/yyuu/pyenv-virtualenv), not pyenv.

**Comment by yyuu** [comment]
This must not be an issue of pyenv.

**Comment by ashishnegi** [comment]
sorry for the delayed reply.

I did as you suggested : getting `base_prefix` in `orca-env`. It shows it is indeed `3.x` of local `pyenv`'s python. Here is the log.
```
^C(orca-env) ashish:orca$ python -c 'import sys; print(sys.real_prefix)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'real_prefix'
(orca-env) ashish:orca$ python -c 'import sys; print(sys.base_prefix)'
/home/ashish/.pyenv/versions/3.4.3
(orca-env) ashish:orca$ 
```

However, i could not find `${virtualenv_prefix}` directory. Where would it be located ?
but as much as i remember i did not wrote `--sysem-site-packages` while creating the virtualenv `orca-env`.  I also tried a full search for `no-global-*.txt` in `/home` and it returned nothing.

Any suggesions ?

**Comment by yyuu** [comment]
* The 'virtualenv_prefix' I meant would be '~/.pyenv/versions/orca-env', in this case
* '--system-site-packages' is a feature of virtualenv which indicates created virtualenv to be look for 'sys.real_prefix' (or 'sys.base_prefix') if a library is not available in the virtualenv. See also [virtualenv doc](https://virtualenv.pypa.io/en/latest/userguide.html#the-system-site-packages-option)

Basically your issue must not be an actual issue of pyenv/pyenv-virtualenv.  The following commands would fix your 'orca-env' to act as a virtualenv from system's 'python3' with '--system-site-packages'. See also for virtualenv docs about virtualenv options.

pyenv shell 3.4.3
 pip install -U virtualenv
mv -f ~/.pyenv/versions/orca-env ~/.pyenv/versions/orcaenv.orig || true
pyenv virtualenv --python=/usr/bin/python3 --system-site-packages system orca-env
pyenv shell --unset

**Comment by ashishnegi** [comment]
Great this works..
However, the line `pyenv virtualenv --python=/usr/bin/python3 --system-site-packages system orca-env` should be without `system`. Right ?

Also, to understand what happened is that you created a new virtualenv with `/usr/bin/python3` with system-site-packages flag. so, if orca-env can not find the packages in local site-packages it would search in /usr/bin/python3's site-packages. However, pip in orca-env would install things in local environment.
