### ISSUE TITLE
pyenv install not found on ubuntu 14.04

### ISSUE THREAD

**Issue by poc7667** [yyuu/pyenv#453]
➜  ~  git clone https://github.com/yyuu/pyenv.git ~/.pyenv
Cloning into '/home/deploy/.pyenv'...
remote: Counting objects: 10957, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 10957 (delta 0), reused 0 (delta 0), pack-reused 10950
Receiving objects: 100% (10957/10957), 1.91 MiB | 0 bytes/s, done.
Resolving deltas: 100% (7735/7735), done.
Checking connectivity... done.
➜  ~  zsh
➜  ~  pyenv
pyenv 20151006
Usage: pyenv <command> [<args>]

Some useful pyenv commands are:
   commands    List all available pyenv commands
   local       Set or show the local application-specific Python version
   global      Set or show the global Python version
   shell       Set or show the shell-specific Python version
   rehash      Rehash pyenv shims (run this after installing executables)
   version     Show the current Python version and its origin
   versions    List all Python versions available to pyenv
   which       Display the full path to an executable
   whence      List all Python versions that contain the given executable

See `pyenv help <command>' for information on a specific command.
For full documentation, see: https://github.com/yyuu/pyenv#readme
➜  ~  pyenv init
# Load pyenv automatically by adding
# the following to the end of ~/.zshrc:

eval "$(pyenv init -)"

➜  ~  python install
python: can't open file 'install': [Errno 2] No such file or directory
➜  ~  pyenv install
pyenv: no such command `install'

**Comment by yyuu** [comment]
RTFM and read messages

https://github.com/yyuu/pyenv#basic-github-checkout

**Comment by samgalam** [comment]
This took me a while to figure out, but in my config, I had:
`export PYENV_ROOT="~/.pyenv"`
instead of:
`export PYENV_ROOT="$HOME/.pyenv"`

which was causing the `install` command to not be found even after running pyenv init etc.
