### ISSUE TITLE
Requirement already satisfied (use --upgrade to upgrade): setuptools

### ISSUE THREAD

**Issue by lanox** [yyuu/pyenv#457]
Hi 
I have followed instruction on installing pyenv Homebrew on Mac OS X, 

The message where it say Requirement already satisfied (use --upgrade to upgrade): setuptools ..... is that just like FYI message or a problem ?

```
pyenv virtualenv 2.7.10 test
New python executable in /Users/xxxx/.pyenv/versions/test/bin/python2.7
Also creating executable in /Users/xxx/.pyenv/versions/test/bin/python
Installing setuptools, pip, wheel...done.
Ignoring indexes: https://pypi.python.org/simple
Requirement already satisfied (use --upgrade to upgrade): setuptools in /Users/xxxx/.pyenv/versions/test/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): pip in /Users/xxxxx/.pyenv/versions/test/lib/python2.7/site-packages
```

pyenv version
2.7.10 (set by /Users/lpuljic/.python-version)

pyenv global
2.7.10

```bash
pip install setuptools --upgrade
Requirement already up-to-date: setuptools in ./.pyenv/versions/2.7.10/lib/python2.7/site-packages
```
```bash
pip install pip --upgrade
Requirement already up-to-date: pip in ./.pyenv/versions/2.7.10/lib/python2.7/site-packages
```

Thanks

**Comment by yyuu** [comment]
Starting from 2.7.9, CPython shipped with ensurepip and it will install pip after installation without help from pyenv/pyenv-virtualenv. This should not be an issue.

https://docs.python.org/2/library/ensurepip.html

**Comment by lanox** [comment]
@yyuu thanks.

Although my 2.7.10 Python installed with pyenv does not have any outdated modules when I run pip list --outdated. 

But when I create virtualenv, setuptool are not on latest version ? I would of assumed setuptools would of been installed with latest version.

Also is there way to suppress that message ?

**Comment by yyuu** [comment]
virtualenv bundles setuptools, pip and relatives as its package contents (in the `virtualenv_support` directory). I suspect you're using way older release of virtualenv and it installed older pip.

AFAIK, there's no way to suppress to suppress the message. I confirmed that virtualenv v13.1.2 shows the message even with `--quiet`.

```sh
% pyenv virtualenv --quiet 2.7.10 foo
Ignoring indexes: https://pypi.python.org/simple
Requirement already satisfied (use --upgrade to upgrade): setuptools in /home/yyuu/.pyenv/versions/foo/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): pip in /home/yyuu/.pyenv/versions/foo/lib/python2.7/site-packages
```

**Comment by lanox** [comment]
Thanks will check when I get home. However I am using brew pyenv and pyenv-virtualenv, so I would assume I am on latest.

Thanks for the clarification

**Comment by yyuu** [comment]
Actually pyenv-virtualenv is just a wrapper for virtualenv and it will never upgrade existing installation of virtualenv if there is some version installed, at least with current impl. Just upgrading virtualenv with `pip install -U virtualenv` forces pyenv-virtualenv to use latest version of virtualenv.

**Comment by lanox** [comment]
yeah I am running

 pyenv virtualenv --version
pyenv-virtualenv 20151006 (virtualenv 13.1.2) i guess i will just leave with it if this is not an error.

**Comment by bhavsar112** [comment]
1) sudo apt update && apt upgrade
then use command;
