### ISSUE TITLE
Jython install gets executable path wrong 

### ISSUE THREAD

**Issue by regebro** [yyuu/pyenv#459]
When installing Jython-2.7.0 the easy_install and pip scripts are installed with the hashbang pointing to the build executable in /tmp/python-build.<timespamp>/jython-2.7.0/bin/jython instead of the installed location.

I used this command to install:

    sudo ./bin/python-build jython-2.7.0 --prefix /opt/jython27 -v

**Comment by yyuu** [comment]
#458
