### ISSUE TITLE
pyenv fails to install any versions on Mac OS X 10.9.5 

### ISSUE THREAD

**Issue by tjsoftworks** [yyuu/pyenv#460]
I have attempted to clean house and start the management of python with pyenv.

Following the recommendations of 
http://www.chriskrycho.com/2015/a-modern-python-development-toolchain.html
I have used homebrew to install only pyenv and pyenv-virtualenv for python base tools to get started.
   ( I use homebrew for most other command line installs. )

I believe I have only the Mac OS X standard python at /usr/bin/python only.

Here is my pyenv version, path definition and environment variables: 

```
Sun Oct 18 15:44:59 myUsername@Mys-MBP15:~ >>pyenv --version
pyenv 20151006
Sun Oct 18 15:46:30 myUsername@Mys-MBP15:~ >>which pyenv
/usr/local/bin/pyenv
Sun Oct 18 15:46:34 myUsername@Mys-MBP15:~ >>ll /usr/local/bin/pyenv
8 lrwxr-xr-x  1 myUsername  wheel  34 Oct 18 15:39 /usr/local/bin/pyenv -> ../Cellar/pyenv/20151006/bin/pyenv
Sun Oct 18 15:46:45 myUsername@Mys-MBP15:~ >>env | grep -i python
Sun Oct 18 15:47:16 myUsername@Mys-MBP15:~ >>env | grep -i py
PYENV_ROOT=/usr/local/var/pyenv
PYENV_VIRTUALENV_INIT=1
PATH=/opt/chefdk/bin:/Users/myUsername/.chefdk/gem/ruby/2.1.0/bin:/opt/chefdk/embedded/bin:/usr/local/var/pyenv/shims:/usr/local/bin:/Users/myUsername/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/Users/myUsername/opt/wireshark/bin:/bin:/bin:/usr/local/packer
PYENV_SHELL=bash
Sun Oct 18 15:47:21 myUsername@Mys-MBP15:~ >>
```

Upon running pyenv to attempt to install various python version, all fail in the follow way. Here is the run...

```
>>pyenv install 3.4.3
Downloading Python-3.4.3.tgz...
-> https://yyuu.github.io/pythons/4281ff86778db65892c05151d5de738d
Installing Python-3.4.3...

BUILD FAILED (OS X 10.9.5 using python-build 20150818)

Inspect or clean up the working tree at /var/folders/gg/bk91_2dd7f350l2js_kdvyzh0000gn/T/python-build.20151018154257.47986
Results logged to /var/folders/gg/bk91_2dd7f350l2js_kdvyzh0000gn/T/python-build.20151018154257.47986.log

Last 10 log lines:
dyld: lazy symbol binding failed: Symbol not found: _fdopendir$INODE64
  Referenced from: /private/var/folders/gg/bk91_2dd7f350l2js_kdvyzh0000gn/T/python-build.20151018154257.47986/Python-3.4.3/./python.exe
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _fdopendir$INODE64
  Referenced from: /private/var/folders/gg/bk91_2dd7f350l2js_kdvyzh0000gn/T/python-build.20151018154257.47986/Python-3.4.3/./python.exe
  Expected in: /usr/lib/libSystem.B.dylib

/bin/sh: line 1: 59494 Trace/BPT trap: 5       ./python.exe -E -m ensurepip $ensurepip --root=/
make: *** [install] Error 133
```

Is this a bug? or perhaps I have not setup a path or environment variable right to get started?

----

The tail of the log file above is:

```
.....
if test "xupgrade" != "xno"  ; then \
		case upgrade in \
			upgrade) ensurepip="--upgrade" ;; \
			install|*) ensurepip="" ;; \
		esac; \
		 ./python.exe -E -m ensurepip \
			$ensurepip --root=/ ; \
	fi
dyld: lazy symbol binding failed: Symbol not found: _fdopendir$INODE64
  Referenced from: /private/var/folders/gg/bk91_2dd7f350l2js_kdvyzh0000gn/T/python-build.20151018154257.47986/Python-3.4.3/./python.exe
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _fdopendir$INODE64
  Referenced from: /private/var/folders/gg/bk91_2dd7f350l2js_kdvyzh0000gn/T/python-build.20151018154257.47986/Python-3.4.3/./python.exe
  Expected in: /usr/lib/libSystem.B.dylib

/bin/sh: line 1: 59494 Trace/BPT trap: 5       ./python.exe -E -m ensurepip $ensurepip --root=/
make: *** [install] Error 133
```

**Comment by IsmailM** [comment]
+1

**Comment by yyuu** [comment]
I don't have 10.9 anymore. I could not reproduce this.

I suspect you have weird configuration in DYLD_LIBRARY_PATH.

**Comment by tjsoftworks** [comment]
I have repeated my attempt a number of times under 10.9.5. All fail. The same process under 10.10.5 works just fine.

Any advise as to what I should look at for figure out why pyenv is failing to install all python versions? The logs are very long and this is a level of debugging I having done with python. In the past, I have under homebrew to install version of python. I'm trying to get out of that boat.

I'm willing to dig and send a pull request but I'm needing a little help getting started on what may be wrong.

**Comment by yyuu** [comment]
@tjsoftworks Please create some gist from the full output from pyenv with enabling debug logging. That might help for investigation.

1. Output from `env` (please conceil your credentials from the output if you have something)
2. Output from `pyenv install -v 3.5.0 2>&1 | tee log.txt`

**Comment by tjsoftworks** [comment]
public gist includes
>>env
and
log.txt
git@gist.github.com:19e61edd6c39709da003.git

**Comment by yyuu** [comment]
Apparently your `libSystem.B.dylib` is broken. I'd recommend you to reinstall Command Line Tools for OS X, but not sure if it helps.

Anyway this must not be a problem with pyenv. I believe you cannot build any CPython versions even without pyenv.

**Comment by yyuu** [comment]
This must be a problem on broken system, not an issue of pyenv.

**Comment by tjsoftworks** [comment]
I haven't intentionally changed my libSystem.B.dylib. I have reinstalled Command Line Tools. If others have used pyenv on 10.9.5 successfully, with current updates, then perhaps it is something about my system. I would suspect something in the env.PATH. Does anything stand out to you? I'll plan to upgrade the problem machine to Yosemite though I try to keep a development systems using at least two ( this would be three now that El Capitan is out ) OS versions. Thank you for looking at the issue.

**Comment by ssbarnea** [comment]
Any reason not to close a 4 years of bug?
