### ISSUE TITLE
pyenv: deactivate: command not found

### ISSUE THREAD

**Issue by easior** [yyuu/pyenv#461]
Today, I get a strange error as above when I create a Python VirtualEnv by 
```sh
$ mkvirtualenv Django
```
with virtualenvwrapper.sh installed in python userbase directory. I don't know what happened. This error can be eliminated by using virtualenv.

**Comment by blueyed** [comment]
There is a activated one before already?

**Comment by easior** [comment]
No, I think. If there was an activated one of python virtualenvs, the deactivate command should make it exit. However, it reports the same error after executing deactivate command. In addition, it works well if  workon <VIRENVNAME> is executed firstly and then deactivate it.

**Comment by yyuu** [comment]
not an issue of pyenv.
