### ISSUE TITLE
"Missing the OpenSSL lib"  - CentOS release 5.11 (Final) - How to configure?

### ISSUE THREAD

**Issue by voleary** [yyuu/pyenv#462]
When attempting to run "sudo pyenv install 2.7.10" , I get the following warning/errors:
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

BUILD FAILED (CentOS release 5.11 (Final) using python-build 20150818)

I am running CentOS release 5.11, and have latest versions of readline-devel & openssl-devel installed. How can I tell the compiler where the packages are located?

**Comment by yyuu** [comment]
I suspect you are using very old version and CPython refused to use it. Plz lemme know the following.

* version of openssl-devel
* output from 'pyenv -v 2.7.10 2>&1 | tee build.log' (plz create a gist)

**Comment by voleary** [comment]
Thanks yyuu:
Here's the gist:
 https://gist.github.com/voleary/40710410faa0f7ac1637

**Comment by yyuu** [comment]
My bad, the command line I pasted was wrong. Please recreate gist with captured output from `pyenv install -v 2.7.10 2>&1`

**Comment by voleary** [comment]
ok, thanks. Have updated the gist to show output of the command:  'sudo pyenv install -v 2.7.10 2>&1 >> build.log' 
same link : https://gist.github.com/voleary/40710410faa0f7ac1637

Not sure of the impact between running 'sudo pyenv install -v 2.7.10 2>&1 >> build.log' vs. 'pyenv install -v 2.7.10 2>&1 >> build.log' . I realize each may call on different dependent packages. 

I am sudo and sole user of this virtual machine, however I would like to ensure this installation can be replicated on a similar machine without sudo access if possible. Let me know if you want to see anything else.  Really appreciate your help.

**Comment by voleary** [comment]
Hey yyuu,
Thanks again for your help. Is there anything else I can provide that might help us solve? Not sure if this is a lost cause or not.

**Comment by yyuu** [comment]
It looks like your system is just wrongly configured. Reinstalling some of broken libs installed in `/usr/local` would help. This should not be an issue of pyenv anyways.

```
building '_ssl' extension
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I. -IInclude -I./Include -I/home/voleary/.pyenv/versions/2.7.10/include -fPIC -I. -IInclude -I./Include -I/home/voleary/.pyenv/versions/2.7.10/include -I/usr/local/include -I/tmp/python-build.20151028143832.5465/Python-2.7.10/Include -I/tmp/python-build.20151028143832.5465/Python-2.7.10 -c /tmp/python-build.20151028143832.5465/Python-2.7.10/Modules/_ssl.c -o build/temp.linux-x86_64-2.7/tmp/python-build.20151028143832.5465/Python-2.7.10/Modules/_ssl.o
/tmp/python-build.20151028143832.5465/Python-2.7.10/Modules/_ssl.c: In function ‘_setup_ssl_threads’:
/tmp/python-build.20151028143832.5465/Python-2.7.10/Modules/_ssl.c:3883: warning: comparison is always false due to limited range of data type
gcc -pthread -shared -L/home/voleary/.pyenv/versions/2.7.10/lib -L/home/voleary/.pyenv/versions/2.7.10/lib -I. -IInclude -I./Include -I/home/voleary/.pyenv/versions/2.7.10/include build/temp.linux-x86_64-2.7/tmp/python-build.20151028143832.5465/Python-2.7.10/Modules/_ssl.o -L/home/voleary/.pyenv/versions/2.7.10/lib -L/usr/local/lib -lssl -lcrypto -o build/lib.linux-x86_64-2.7/_ssl.so
/usr/bin/ld: skipping incompatible /usr/local/lib/libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: skipping incompatible /usr/local/lib/libgcc_s.so when searching for -lgcc_s
*** WARNING: renaming "_ssl" since importing it failed: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

**Comment by voleary** [comment]
Alright. Thanks anyway for trying to help.
