### ISSUE TITLE
How to remove pyenv itself

### ISSUE THREAD

**Issue by lewisl** [yyuu/pyenv#465]
In typical Linux fashion, each developer considers his code so invaluable that no documented means of removing it is provided.  Install results in a sprinkling throughout the file system with a variety of settings that are difficult to completely purge.

Please document safe and complete removal.

**Comment by thomasjo** [comment]
Uhmm... pyenv is self-contained. Just nuke the folder where you cloned the repo, e.g.
``` bash
rm -rf "$HOME/.pyenv"
```

**Comment by joshfriend** [comment]
@thomasjo you also have to remember to remove the lines from your shell environment config that set `$PYENV_ROOT` and append it to your `$PATH`:

```bash
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
```

**Comment by yyuu** [comment]
Basically uninstallation is just removing ~/.pyenv and shell configurations. To make things better, only PR works.

// I might be going to add some section for uninstallation later since rbenv already has it in its README

**Comment by Nimitz14** [comment]
Bad idea, when I did this `No command 'pyenv' found, did you mean:` and similar every time I hit enter on the command line
