### ISSUE TITLE
pyenv-rehash does not work for anaconda virtualenvs?

### ISSUE THREAD

**Issue by cpaulik** [yyuu/pyenv#467]
I've made a new anaconda environment using

`conda create -n testenv pip`

i can then activate the environment using `pyenv activate miniconda-3.16.0/envs/testenv`

After that `which python` and `which pip` etc. gives me

`/home/cpa/.pyenv/versions/miniconda-3.16.0/envs/testenv/bin/python`
instead of the shim.

This behaviour does not change even after running `pyenv rehash`

Am I doing something wrong?

**Comment by yyuu** [comment]
It is expected behaviour at least with pyenv v20151006 / pyenv-virtualenv v20151006.

pyenv will do nothing for envs created by conda. pyenv-virtualenv can activate/deactivate envs created by conda. It won't manage any shims, though.

**Comment by cpaulik** [comment]
OK, thank you for the clarification. 

Would it not be a good idea to support anaconda environments like other environments?

**Comment by yyuu** [comment]
I'd like to add more sophisticated support for cobda envs. There some of differeces and it takes time to implement it, though.

Now I am planning overall refactoring of activate feature of pyenv-virtualenv (remove dependency to virtualenv/pyvenv/conda's weird activate script) I will update this issue once some of my changes became ready.

**Comment by yyuu** [comment]
Ah, actually this must be an issue of pyenv-virtualenv, not pyenv itself.

**Comment by cpaulik** [comment]
Thanks, I've opened an issue in pyenv-virtualenv. See https://github.com/yyuu/pyenv-virtualenv/issues/103
