### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by alex** [yyuu/pyenv#468]
Would it be possible to make a new release, I'd love to start rolling out pypy-4.0.0, but having a pyenv release is a blocker.

Thanks so much for all the work you do! pyenv is great

**Comment by yyuu** [comment]
I will do this tomorrow in Japan time.

**Comment by alex** [comment]
Thanks!

**Comment by yyuu** [comment]
Ah, I've just released v20151103 by some accident. Anyway it should be okay.

I'd like to ask someone to release v20151103 to Homebrew if possible....

**Comment by alex** [comment]
I'll send a PR to homebrew momentarily! Thanks!

On Tue, Nov 3, 2015 at 8:33 AM, Yamashita, Yuu <notifications@github.com>
wrote:

> Ah, I've just released v20151103 by some accident. Anyway it should be
> okay.
>
> I'd like to ask someone to release v20151103 to Homebrew if possible....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yyuu/pyenv/issues/468#issuecomment-153353726>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by yyuu** [comment]
:+1:
