### ISSUE TITLE
pip is not installed with "pyenv install <version>"

### ISSUE THREAD

**Issue by yiliangt5** [yyuu/pyenv#474]
I tried pyenv install 2.7.10, 3.4.3 and 3.5.0, but no single version would install pip for me.(under shims).
Is there some work I missed?
![Uploading Screen Shot 2015-11-07 at 14.23.46.png…]()

**Comment by yyuu** [comment]
Those all versions should install `pip` with using `ensurepip`. 

https://github.com/yyuu/pyenv/blob/9ca7de5b6c0f5b467c9a5a22471d6dc334684c52/plugins/python-build/share/python-build/2.7.10#L4
https://github.com/yyuu/pyenv/blob/9ca7de5b6c0f5b467c9a5a22471d6dc334684c52/plugins/python-build/bin/python-build#L1602-L1610

I couldn't reproduce issue with `ensurepip`. Please make sure if you really don't have `pip` executable in your `$(pyenv root)/versions/2.7.10/bin`. If there is one, running `pyenv rehash` should solve the issue.

If problem persists, there might be some problem in `ensurepip` itself. It'd be better to report it to upstream CPython.

**Comment by yiliangt5** [comment]
@yyuu now the issue is fixed by reinstalling pyenv and python.
thanks.
