### ISSUE TITLE
pyenv 20151105 can't load "~/.pyenv", PATH be set  by "/usr/local/opt/pyenv/shims"

### ISSUE THREAD

**Issue by ccqpein** [yyuu/pyenv#476]
After updating new version of pyenv, command "which python" is "/usr/bin/python". And PATH be set by "/usr/local/opt/pyenv/shims", ever I add "eval "$(pyenv init -)" " to zsh setting file. Actually I don't change anything, but pyenv can't work after updating.

**Comment by ccqpein** [comment]
On the old version, the path is "~/.pyenv/shim" and work well, can't work after update. It change the path to brew path, and  eval `"$(pyenv init -)` add another brew path at the head of the path list. It's the bug or change the setting way in new version?

**Comment by yyuu** [comment]
Nothing changed at least in recent releases, and no one encountered similar issues. It would indicate that broken part is just your sustem. Try uninstall and reinstall pyenv with using brew.

**Comment by ccqpein** [comment]
I reinstall the pyenv with brew, and relaunch the shell after install. Delete ` eval "$(pyenv init -) `in .zshrc.
And my path is "/usr/local/opt/pyenv/shims /usr/local/opt/pyenv/bin", not "~/.pyenv/shim/" as before, I haven't do anything.

**Comment by blueyed** [comment]
Somewhere PYENV_ROOT gets set to `/usr/local/opt/pyenv`.

**Comment by ccqpein** [comment]
The PYENV_ROOT exactly is `/usr/local/opt/pyenv`. I don't know why, I never change that.

 When I add `export PYENV_ROOT="$HOME/.pyenv" ` to .zshrc. The PATH become "/Users/Myname/.pyenv/shims /usr/local/opt/pyenv/shims /usr/local/opt/pyenv/bin" 

When `eval "$(pyenv init -)"` in .zshrc. The PATH including three pyenv paths, one PYENV_ROOT and "/usr/local/opt/pyenv/shims /usr/local/opt/pyenv/bin"

When `eval "$(pyenv init -)"` not in .zshrc. The PATH including only two pyenv paths, "/usr/local/opt/pyenv/shims /usr/local/opt/pyenv/bin"

**Comment by ccqpein** [comment]
And  no matter what I do for pyenv or shell config, `which python` always show "/usr/bin/python". I remember it might be "~/.pyenv/shim" before.

**Comment by blueyed** [comment]
It might be something done by brew?
You might want to try the manual installation method, which is quite trivial after all.

**Comment by ccqpein** [comment]
I will try it and send email to brew too, thank you

**Comment by yyuu** [comment]
All are expected behavior and no bugs in it. I'll close this anyways.

**Comment by ccqpein** [comment]
I found where the problem is, [oh-my-zsh pyenv plugin]<https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/pyenv/pyenv.plugin.zsh> do something for the pyenvdirs. I turn off this plugin then the pyenv work well.

Thanks guys
