### ISSUE TITLE
Python 2.7.X "No module named _struct"

### ISSUE THREAD

**Issue by mattrohland** [yyuu/pyenv#484]
I have had a lot of luck with pyenv in the past but after upgrading to Mac OS X 10.11.1 I am now seeing an "ImportError: No module named _struct" error when attempting to install older versions of python 2.7:

```
pyenv install 2.7.3        
Downloading Python-2.7.3.tgz...
-> https://yyuu.github.io/pythons/d4c20f2b5faf95999fd5fecb3f7d32071b0820516224a6d2b72932ab47a1cb8e
Installing Python-2.7.3...
patching file ./Modules/readline.c
Hunk #1 succeeded at 200 (offset -6 lines).
Hunk #2 succeeded at 735 (offset -14 lines).
Hunk #3 succeeded at 845 (offset -14 lines).
Hunk #4 succeeded at 893 with fuzz 2 (offset -25 lines).
patching file ./Lib/site.py

BUILD FAILED (OS X 10.11.1 using python-build 20151105-4-g9ca7de5)

Inspect or clean up the working tree at /var/folders/7n/4x7hyjv95191sb95wx24qm_wymlmy3/T/python-build.20151118152734.50204
Results logged to /var/folders/7n/4x7hyjv95191sb95wx24qm_wymlmy3/T/python-build.20151118152734.50204.log

Last 10 log lines:
		-d /Users/mrohland/.pyenv/versions/2.7.3/lib/python2.7 -f \
		-x 'bad_coding|badsyntax|site-packages|lib2to3/tests/data' \
		/Users/mrohland/.pyenv/versions/2.7.3/lib/python2.7
Traceback (most recent call last):
  File "/Users/mrohland/.pyenv/versions/2.7.3/lib/python2.7/compileall.py", line 16, in <module>
    import struct
  File "/Users/mrohland/.pyenv/versions/2.7.3/lib/python2.7/struct.py", line 1, in <module>
    from _struct import *
ImportError: No module named _struct
make: *** [libinstall] Error 1
```

I had run through all the items in https://github.com/yyuu/pyenv/wiki/Common-build-problems and searched both the issues already reported here and StackOverflow, but have not seen this particular issue reported.

Has this issue been reported?

**Comment by mattrohland** [comment]
I had stumbled upon that bug in my searches too, but at a glance it didn't seem related.

If 2.7.3 isn't giving others on OS X 10.11.1 any trouble, it might be something very specific surrounding my environment. I'll keep hunting and attempt to remove anything else I may have customized in my development environment.

Also, I ran the test in verbose mode so there would be more context as to where in the process the error occurred. Not sure how insightful it is:

```
...
/usr/bin/install -c -m 644 ./Lib/plat-mac/lib-scriptpackages/Terminal/Terminal_Suite.py /Users/mrohland/.pyenv/versions/2.7.3/lib/python2.7/plat-mac/lib-scriptpackages/Terminal
/usr/bin/install -c -m 644 ./Lib/plat-mac/lib-scriptpackages/Terminal/Text_Suite.py /Users/mrohland/.pyenv/versions/2.7.3/lib/python2.7/plat-mac/lib-scriptpackages/Terminal
/usr/bin/install -c -m 644 ./Lib/plat-mac/lib-scriptpackages/Terminal/__init__.py /Users/mrohland/.pyenv/versions/2.7.3/lib/python2.7/plat-mac/lib-scriptpackages/Terminal
/usr/bin/install -c -m 644 ./LICENSE /Users/mrohland/.pyenv/versions/2.7.3/lib/python2.7/LICENSE.txt
if test -d /Users/mrohland/.pyenv/versions/2.7.3/lib/python2.7/distutils/tests; then \
		/usr/bin/install -c -m 644 ./Modules/xxmodule.c \
			/Users/mrohland/.pyenv/versions/2.7.3/lib/python2.7/distutils/tests ; \
	fi
PYTHONPATH=/Users/mrohland/.pyenv/versions/2.7.3/lib/python2.7   \
		./python.exe -Wi -tt /Users/mrohland/.pyenv/versions/2.7.3/lib/python2.7/compileall.py \
		-d /Users/mrohland/.pyenv/versions/2.7.3/lib/python2.7 -f \
		-x 'bad_coding|badsyntax|site-packages|lib2to3/tests/data' \
		/Users/mrohland/.pyenv/versions/2.7.3/lib/python2.7
Traceback (most recent call last):
  File "/Users/mrohland/.pyenv/versions/2.7.3/lib/python2.7/compileall.py", line 16, in <module>
    import struct
  File "/Users/mrohland/.pyenv/versions/2.7.3/lib/python2.7/struct.py", line 1, in <module>
    from _struct import *
ImportError: No module named _struct
make: *** [libinstall] Error 1
```

**Comment by mattrohland** [comment]
After sifting through the the verbose logs I started noticing messages like `symbol(s) not found for architecture i386`. This reminded me that I had recently worked on a project where I had set the following in the shell `export ARCHFLAGS="-arch i386 -arch x86_64"`. I was working on that project around the time I upgraded to OSX 10.11.1 and had incorrectly assumed the upgrade was related to the issue.

Removing the ARCHFLAGS value from my shell environment allowed python to build correctly. For more information on ARCHFLAGS see: https://developer.apple.com/library/prerelease/mac/releasenotes/OpenSource/PerlExtensionsRelNotes/index.html

@joshfriend thank you for helping me rule out the OSX version.

**Comment by jakirkham** [comment]
Also, having this issue. Would like to install a later 2.7 preferably. Is there any way to solve this? `ARCHFLAGS` not set. Trying to install 2.7.9 on 10.11.

**Comment by tuck182** [comment]
> After sifting through the the verbose logs I started noticing messages like `symbol(s) not found for architecture i386`. This reminded me that I had recently worked on a project where I had set the following in the shell `export ARCHFLAGS="-arch i386 -arch x86_64"`. I was working on that project around the time I upgraded to OSX 10.11.1 and had incorrectly assumed the upgrade was related to the issue.
> 
> Removing the ARCHFLAGS value from my shell environment allowed python to build correctly.

Thank you! This was exactly my problem, and unsetting ARCHFLAGS fixed it.
