### ISSUE TITLE
PYENV_VERSION does not change Python version

### ISSUE THREAD

**Issue by cjerdonek** [yyuu/pyenv#492]
The `PYENV_VERSION` environment variable doesn't seem to work as documented.  The documentation says in the README:

> When you execute a shim, pyenv determines which Python version to use by reading it from the following sources, in this order:
>
> 1. The `PYENV_VERSION` environment variable (if specified). You can use the `pyenv shell` command to set this environment variable in your current shell session.
> 2. ...

However, if I manually set `PYENV_VERSION`, the version doesn't change.  So it seems like there's something more than simply this environment variable:

```
$ pyenv versions
* system (set by /Users/chris/.pyenv/version)
  2.7.10
  3.4.3
  3.5.0
$ PYENV_VERSION=3.5.0
$ echo $PYENV_VERSION
3.5.0
$ pyenv versions
* system (set by /Users/chris/.pyenv/version)
  2.7.10
  3.4.3
  3.5.0
$ pyenv shell 3.5.0
$ echo $PYENV_VERSION
3.5.0
$ pyenv versions
  system
  2.7.10
  3.4.3
* 3.5.0 (set by PYENV_VERSION environment variable)
```

The reason I'm interested in this approach is that I'm trying to use `pyenv` in a shell script to temporarily change Python versions, and using `pyenv shell` in the shell script gives me the following error:

> pyenv: no such command `shell'

If you know a better / preferred way to change the current version in a shell script, it would be appreciated.  Thanks.

**Comment by yyuu** [comment]
You need to 'export' variable to define environ variables.

**Comment by yyuu** [comment]
Obviously `eval "$(pyenv init -)"` in your shell profile isn't working due to some reason if you got this error. Please review your shell configuration and try again.

> pyenv: no such command `shell'

**Comment by blueyed** [comment]
In a shell script you would have to explicitly init pyenv - it won't come from your shell config / profile, does it?

**Comment by cjerdonek** [comment]
Thanks, @yyuu (and @blueyed). Calling `export` works.

I do have `eval "$(pyenv init -)"` in my `.bash_profile`.  Is there a recommended / preferred way to switch Python versions in a shell script using pyenv?  I first tried `pyenv shell ...` within the script but got the error above (even though other pyenv commands work).

Now I'm doing the following, but it's not ideal because you have to remember to switch back to the original version before leaving the script:

```
#!/bin/bash
original_pyenv = PYENV_VERSION
export PYENV_VERSION=2.7.10
# DO STUFF
export PYENV_VERSION=$original_pyenv
```

**Comment by yyuu** [comment]
Both `PYENV_VERSION` and `pyenv shell` should work even in shell scripts. Latter requires you to add `eval "$(pyenv init -)"` in your script, though.

Personally I like to use `PYENV_VERSION` since it doesn't require additional shell setup....

```sh
#!/bin/bash
# Set version to 2.7.10
export PYENV_VERSION=2.7.10

# DO STUFF
# python --version # ==> Python 2.7.10

# Reset version
unset PYENV_VERSION
```

**Comment by cjerdonek** [comment]
Great, thanks for the advice!

**Comment by blueyed** [comment]
In my zshenv I am only adding `$PYENV_ROOT/bin` and if they do not exist already, and do not prepend them unconditionally to the PATH.  This way the `python` will always be the one from a virtualenv, even with `PYTHON_VERSION` being set.
I'm not sure if that's really better though?!

**Comment by cjerdonek** [comment]
> `unset PYENV_VERSION`

Also, it may be preferable to restore the original `PYENV_VERSION` instead in the case that `PYENV_VERSION` was originally in effect in the caller's shell.

**Comment by yyuu** [comment]
@cjerdonek Environment variables set in child process would not affect same name in parent process. Basically you don't have to restore to original value if your script is run as a script, not `source`'d.

**Comment by cjerdonek** [comment]
@yyuu Sorry, the case I had in mind is if there is additional code later on in the shell script.

**Comment by yyuu** [comment]
Got it. If you have some script after that, it'd be better to revert to original state.
