### ISSUE TITLE
CPython 3.5.1 released

### ISSUE THREAD

**Issue by alex** [yyuu/pyenv#497]
https://www.python.org/downloads/release/python-351/

as always <3 for all the work y'all do

**Comment by yyuu** [comment]
@alex Can you create PR for this? Basically just copying & modifying the definition of 3.5.0 would work for it....

https://github.com/yyuu/pyenv/blob/20432dda88b64956969390e16bb30cbc58488fef/plugins/python-build/share/python-build/3.5.0

**Comment by yyuu** [comment]
Fixed by #498
