### ISSUE TITLE
Bash a requirement? POSIX-friendliness?

### ISSUE THREAD

**Issue by tony** [yyuu/pyenv#499]
Running FreeBSD 11-CURRENT.  Bash is not installed by default on these systems.

In many cases, you can use POSIX sh and have compatibility across all shells. I looked around for some issues on it but couldn't find anything addressing the topic.

Is bash meant to be a requirement in pyenv, or is it there out of habit?

**Comment by yyuu** [comment]
Obviously bash is a requirement. POSIX sh isn't sufficient to run pyenv itself.

**Comment by tony** [comment]
What about zsh?

**Comment by yyuu** [comment]
pyenv's shell function (output of pyenv-init) should be able to work with every bash, zsh, ksh, fish and other POSIX sh. pyenv's libexec only works with bash, though.

**Comment by tony** [comment]
I had a separate project where I tried to get script similar to what is in libexec to be as portable as possible.

I am trying to see if it's possible for pyenv to run without bash as a hard requirement (and just zsh for example).  On BSD, you can go surprisingly far without seeing bash requirement.

It may not be as relevant to many here, since bash is shipped with OS X and most linux distros. pyenv/rbenv is useful enough for me I'm fine installing bash for it.

**Comment by yyuu** [comment]
_bashism_ is also not welcomed in Debian/Ubuntu. It'd be nice if we can remove bash dependency from rbenv/pyenv completely. Though it'd be tough since it's depending on many of bash extensions like bash arrays....
