### ISSUE TITLE
pyenv global not working 

### ISSUE THREAD

**Issue by shangsunset** [yyuu/pyenv#506]
It doesnt change default python version when i use `pyenv global {version}`
I installed via Homebrew on os x 10.11.2. 

![screen shot 2015-12-17 at 1 14 55 pm](https://cloud.githubusercontent.com/assets/3700269/11877905/310df5f2-a4c0-11e5-91dc-c72d3d7f0f90.png)

**Comment by yyuu** [comment]
Review your PATH again and again and again and again.

**Comment by shangsunset** [comment]
Hi,

What could go wrong? This is my path variable but i dont know what to do about it.
![screen shot 2015-12-17 at 9 49 27 pm](https://cloud.githubusercontent.com/assets/3700269/11888097/297a9fdc-a508-11e5-8bf8-8a9b36c1ddb4.png)
