### ISSUE TITLE
How to bind an existing python version in system?

### ISSUE THREAD

**Issue by FavorMylikes** [yyuu/pyenv#508]
Hi,My OS is Fedora23 like some RatHat OS,there are python 2.7.10 and 3.4.3 in /usr/bin/.After I saw your ReadMe.md,I'm not find that how to bind an existing python version in system , and I saw the commands.md, there are so many commands I can‘t understand.For example, 
`pyenv install [-f] [-kvp] <definition-file>`
I don't know what is the definition-file.Is it the file path python  in system?
And when I enter `pyenv commands`,there are more commands appear.For example.
`version-file`
`version-file-read`
`version-file-write`
`version-name`
`version-origin`
`versions`
`virtualenv`
`virtualenv-delete`
`virtualenv-init`
`virtualenv-prefix`
`virtualenvs`
But I can't find the explaination about it.

For now,these are not important.but how to bind an existing python version in system?

**Comment by yyuu** [comment]
As [mentioned in README](https://github.com/yyuu/pyenv#choosing-the-python-version), with using `system` version it will search executables from `PATH` as standard manner as UNIX shell.

**Comment by FavorMylikes** [comment]
yes,I understand,before install pyenv,the version of python is 2.7.10,I mean when enter `python -V`,but,python3 and python3.4  is already in /usr/bin,look
    
    python               python3.4            python3-mako-render
    python2              python3.4m           python3-pyinotify
    python2.7            python3-chardetect   python-local-exec
    python3              python3-coverage 

If I want to set python version be 3.4,How can I use it that have installed,or I must install python 3.4 in /pyenv/versions again?

**Comment by theronic** [comment]
I reinstalled pyenv and have a similar problem. How do I tell pyenv about all the pre-existing Python versions?

**Comment by kootenpv** [comment]
This is a thing. I have an existing pre-pyenv python3.6 and python3.7... now I want to shell the existing python3.7 to be the "main" (one and only) python. How could I do this?

**Comment by pedzed** [comment]
I already have Python `2.7` (system default) and Python `3.6.5` (using make) installed. I find it difficult to understand what to do with those versions. @FavorMylikes's question is still unanswered, which doesn't help either.

**Comment by rbutleriii** [comment]
If you know the legacy python directory, it seems to work to symlink it into the ~/.pyenv/versions folder alongside the others.

**Comment by thoongnv** [comment]
I encounter this issue, hope to find the answer here but bot, so there is no way to archive this?

**Comment by chrahunt** [comment]
Anyone wanting to track this can see #1244.
