### ISSUE TITLE
How can I use python3.4 that have installed in system?

### ISSUE THREAD

**Issue by FavorMylikes** [yyuu/pyenv#509]
The version of python is 2.7.10,I mean when enter `python -V`,but,python3 and python3.4  is already in /usr/bin,look
    
    python               python3.4            python3-mako-render
    python2              python3.4m           python3-pyinotify
    python2.7            python3-chardetect   python-local-exec
    python3              python3-coverage 

If I want to set python version be 3.4,How can I use it that have installed,or I must install python 3.4 in /pyenv/versions again?

**Comment by yyuu** [comment]
Use `PYENV_VERSION=system python3 --version`
