### ISSUE TITLE
OS X installation hangs when official python packages installed before

### ISSUE THREAD

**Issue by ssbb** [yyuu/pyenv#512]
I just installed official package for 3.4.3 first and then removed it from /Library/Frameworks and /usr/local/bin. But forgot to remove related things from /Application folder.

pyenv install just hangs and can't continue. With `--verbose` flag it asks to overwrite things in /Application folder but I think this should be shown even w/o `-v` since now it just hangs forever.

**Comment by yyuu** [comment]
pyenv doesn't manage contrnts inside /Application. It seems there might be something wrong in CPython build script or your environment. Though python-build cannot help the situation since basically it's just a launcher of './configure && make && make install'

**Comment by achimnol** [comment]
I just faced the same situation:

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/555156/38078784-57e44462-3378-11e8-8011-9579afc3c811.png">

This may be fixed from the Python distribution, but I think at least it would be nice to have warnings or notices to the pyenv users in the README or documentation.

**Comment by achimnol** [comment]
Reported to [bugs.python.org as well](https://bugs.python.org/issue33177).

**Comment by joshfriend** [comment]
It looks like the python `make install` process only tries to touch things in `/Applications` if `--enable-framework` is passed to `./configure`. pyenv doesn't use this flag unless you pass it through `PYENV_CONFIGURE_OPTS`. The `--enable-framework` is able to take a path where you would like the framework installed, so maybe try specifying one that isn't `/Applications`?

**Comment by achimnol** [comment]
As commented in the bugs.python.org thread,
I found that the root cause was the permission issue: the official GUI installer installed Python as `root:wheel`, but my pyenv are using `joongi:admin` privilege. Changing the application folder's permission resolved the installation hang up.

What I'm curious now is, why didn't the install script show explicit permission error instead of hanging up?

**Comment by achimnol** [comment]
And yes, I'm using `--enable-framework` option.

**Comment by kabukunz** [comment]
Hello there, I don't know if this has been solved...
it takes:
`sudo env PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.5.3 --verbose`
because the installer needs to write /Application dir to install Idle and co... HTH
