### ISSUE TITLE
"exec $shell" won't reload your pyenv settings correctly most of time

### ISSUE THREAD

**Issue by woosley** [yyuu/pyenv#514]
Using exec $shell to reload shell is recommended in readme, however, it won't work most of time. 

bash for example, "exec bash" will start a `non-login` shell, which only read information from `.bashrc`. you have to start a `login shell` to read information from `.bash_profile` by using `exec bash -l`.

suggest using `source ._start_up_file` to load pyenv settings in the readme.

**Comment by yyuu** [comment]
PR welcome
