### ISSUE TITLE
pyenv homebrew formula version 20151222 suggests incorrect setting for PYENV_ROOT

### ISSUE THREAD

**Issue by ancientHacker** [yyuu/pyenv#516]
The latest brew formula for pyenv (/usr/local/Cellar/pyenv/20151222) has the following advice in its info section:
````
To use Homebrew's directories rather than ~/.pyenv add to your profile:
  export PYENV_ROOT=/usr/local/var/pyenv
````
But shouldn't that be `/usr/local/opt/pyenv` (note `opt` not `var`) as with all prior versions?

**Comment by yyuu** [comment]
There was known issue with `PYENV_ROOT=/usr/local/opt/pyenv` and the caveat has changed in https://github.com/Homebrew/homebrew/commit/5532aa02ce22b4b3ea53a770b181442c3c9b6310

**Comment by ancientHacker** [comment]
Sorry if I am being dense, but... there is no directory or symlink /usr/local/var/pyenv created by the brew install; instead, the brew install continues to create /usr/local/opt/pyenv as a symlink to the Cellar.  Is the goal here that the versions directory not be in the Cellar at all?  And will pyenv create /usr/local/var/pyenv when needed in order to create the versions and shims subdirectories?  Is that how it's supposed to work now?

**Comment by yyuu** [comment]
You're right. PYENV_ROOT will be created automatically if it doesn't exist. IIRC, creating the 'versions' directory in the 'Cellar' directory could cause problem after formula update.

**Comment by ancientHacker** [comment]
So then how am I supposed to change the PYENV_ROOT setting and make it
stick after upgrading to/installing the latest brew version?  I have two
installed versions in the Cellar (/usr/local/opt/pyenv/versions/)
directory, but resetting PYENV_ROOT to /usr/local/var/pyenv and moving the
versions/ directory there does not seem to get pyenv to notice the existing
versions.  Do I have to reinstall those versions?  Is there a way to trick
pyenv install into noticing them so it recreates shims?

**Comment by mtraynham** [comment]
So what was the out come of this?
`export PYENV_ROOT=/usr/local/var/pyenv` seems to be getting overriden now:
```
» echo $PYENV_ROOT
/usr/local/opt/pyenv
```
It still has my existing versions on the PATH, as I can run `python` and get 3.5.1, but if I run `» pyenv versions`, I only see `system`.

**Comment by ancientHacker** [comment]
What I finally had to do was to uninstall pyenv, then set the environment
variable, then reinstall pyenv, then reinstall all my python versions.
Moving the versions folder to the new location didn't seem to get pyenv to
see them properly.  I am guessing there is some data that pyenv keeps
somewhere that it uses in pyenv init, and it updates that info whenever it
installs a version.  I really think this issue should be reopened (or
another one opened instead) and directed at providing a way of explicitly
moving the PYENV_ROOT path from one place to another.

**Comment by mtraynham** [comment]
@ancientHacker Yeah, I'm going down the same road.  Even if I set it to `/usr/local/var/pyenv`, it get's overridden, but `/usr/local/opt/pyenv` is symlinked to the Cellar directory and will get removed on every upgrade of pyenv.

I basically unset the property, so that things seemingly get installed to `~/.pyenv` and therefore won't get nuked on the next upgrade.

**Comment by ancientHacker** [comment]
@yyuu @mtraynham I have opened #526 with a better title and description for this issue.

**Comment by xgess** [comment]
i had this issue as well when i upgraded pyenv to fix something unrelated. i can confirm that deleting everything pyenv on my machine was an effective (albeit annoying and slow) method to get everything working again.
