### ISSUE TITLE
Cannot find -lspotify? 

### ISSUE THREAD

**Issue by xniightx123** [yyuu/pyenv#517]
When I'm installing spotify-ripper, I'm getting an error. What's the issue?

    building 'spotify._spotify' extension
    creating build/temp.linux-i686-2.7/build
    creating build/temp.linux-i686-2.7/build/temp.linux-i686-2.7
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/spot/.pyenv/versions/2.7.10/include/python2.7 -c build/temp.linux-i686-2.7/spotify._spotify.c -o build/temp.linux-i686-2.7/build/temp.linux-i686-2.7/spotify._spotify.o
    gcc -pthread -shared -L/home/spot/.pyenv/versions/2.7.10/lib build/temp.linux-i686-2.7/build/temp.linux-i686-2.7/spotify._spotify.o -lspotify -o build/lib.linux-i686-2.7/spotify/_spotify.so
    /usr/bin/ld: skipping incompatible /usr/local/lib/libspotify.so when searching for -lspotify
    /usr/bin/ld: cannot find -lspotify
    collect2: error: ld returned 1 exit status
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/spot/.pyenv/versions/2.7.10/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-TD6uFG/pyspotify/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-b_yPcq-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-TD6uFG/pyspotify

**Comment by yyuu** [comment]
It's just a build failure of specific packagw. Not a pyenv issue.

**Comment by xniightx123** [comment]
Sorry dude, was at the wrong url
