### ISSUE TITLE
Switch to the usage of SemVer for the pyenv release tags

### ISSUE THREAD

**Issue by raphaelstolt** [yyuu/pyenv#520]
Just noticed (again) via OS X `brew` that you don't use SemVer for the `pyenv` releases itself. The current format makes it very hard to decide whether there's is a need to upgrade pyenv via `brew upgrade` or not.

**Comment by yyuu** [comment]
display label of version string doesn't explain nothing. We don't have enough resource for such release engineering.

**Comment by raphaelstolt** [comment]
Dah it does. Which ressources do you need to switch the format of the version when tagging releases? 

But it's your library and therefore your call.

**Comment by yyuu** [comment]
There are only few people actively working, and we don't have enough slots to fullfill requests except pull requests. Luckily it' 2016 and we're on GitHub, anyone can prepare their own patch. We need  actual work efforts as PRs to make things better.

**Comment by raphaelstolt** [comment]
As far as I know it's not possible to do PRs for release tags and you would also externalise the release management of the library. 

A few of the minor efforts you have to make for switching to [SemVer](http://semver.org/) is changing the release versioning format from `vYYYYMMDD` to `vMajor.Minor.Patch` when tagging releases and raising the SemVer partial version numbers `meaningful`. 

You raise the major version number when introducing API breaking changes. The minor version number is raised when new features are added and the patch version number is raised when bugs are fixed. 

Another minor effort is to also use the SemVer compliant versions in your CHANGELOG.md. — IMO not that much release engineering at all, plus more information revealing than time stamped release version numbers.
