### ISSUE TITLE
Shims not updated after running `setup.py develop`

### ISSUE THREAD

**Issue by foxx** [yyuu/pyenv#524]
It would seem that shims are not automatically updated when using `setup.py develop`, meaning that any `scripts` defined in the `setup.py` are not available on the shell `$PATH`.

Rehashing manually seems to fix the problem, as per instructions from [here][1], which references https://github.com/yyuu/pyenv/issues/31 .

```
pyenv rehash && hash -r
```

Strangely enough, using `setup.py install` doesn't seem to fix the problem either.

This could be related to [`pyenv-pip-rehash`][2], perhaps not taking `setup.py` into consideration, but I don't know enough about `pyenv` internals to make an accurate call.

Any ideas?

[1]: http://stackoverflow.com/a/29754754/1267398
[2]: https://github.com/yyuu/pyenv-pip-rehash

**Comment by yyuu** [comment]
Automated rehashing will work only after `pip install`, `pip uninstall`, `easy-install`, `conda install`, `conda remove` and `conda uninstall`. I don't like to hook up `setup.py develop` since it requires to hook every invocation of `python`.

https://github.com/yyuu/pyenv/tree/5c5205e172f532a7e7511f86666b1d842198e73a/pyenv.d/exec/pip-rehash

**Comment by foxx** [comment]
It's surprising behaviour at the very least. Is there anything we can do to make this more obvious to the user?

**Comment by yyuu** [comment]
How do you think how it should be?

**Comment by foxx** [comment]
That's an excellent question, I've been trawling through the internals and trying to think of ways this situation could either be avoided or made more obvious, but yet to think of a good solution. I was hoping you might have some ideas, as you know the code base better than I do.
