### ISSUE TITLE
Unable to install 32-bit Python 2.6.6, despite appropriate env variables set

### ISSUE THREAD

**Issue by QuarterHalf** [yyuu/pyenv#525]
On a MacBook with Mavericks (`i686-apple-darwinDarwin Kernel Version 13.4.0: Sun Aug 17 19:50:11 PDT 2014; root:xnu-2422.115.4~1/RELEASE_X86_64`) and the following flags set to force it to install 32-bit Python (as advised [here][1]):

    CONFIGURE_OPTS="--with-arch=i386" CFLAGS="-arch i386" LDFLAGS="-arch i386" python-build options

The build of Python 2.6.6 fails thus:

    MacBook-Pro-de-Quarterhalf:project Quarterhalf$ pyenv install 2.6.6
    Downloading openssl-1.0.1q.tar.gz...
    -> https://yyuu.github.io/pythons/b3658b84e9ea606a5ded3c972a5517cd785282e7ea86b20c78aa4b773a047fb7
    Installing openssl-1.0.1q...
    
    BUILD FAILED (OS X 10.9.5 using python-build 20151222-8-g5c5205e)
    
    Inspect or clean up the working tree at /var/folders/t3/yhd5b6lj2cz_b82qzw4zcwh40000gn/T/python-build.20160114111634.64051
    Results logged to /var/folders/t3/yhd5b6lj2cz_b82qzw4zcwh40000gn/T/python-build.20160114111634.64051.log
    
    Last 10 log lines:
    X-Fastly-Request-ID: 375acfca7437e654ed4a47aca0632c23b38582b4
    
    /var/folders/t3/yhd5b6lj2cz_b82qzw4zcwh40000gn/T/python-build.20160114111634.64051/openssl-1.0.1q /var/folders/t3/yhd5b6lj2cz_b82qzw4zcwh40000gn/T/python-build.20160114111634.64051 ~/repos/illuminations
    Operating system: i686-apple-darwinDarwin Kernel Version 13.4.0: Sun Aug 17 19:50:11 PDT 2014; root:xnu-2422.115.4~1/RELEASE_X86_64
    Configuring for darwin64-x86_64-cc
    Usage: Configure [no-<cipher> ...] [enable-<cipher> ...] [experimental-<cipher> ...] [-Dxxx] [-lxxx] [-Lxxx] [-fxxx] [-Kxxx] [no-hw-xxx|no-hw] [[no-]threads] [[no-]shared] [[no-]zlib|zlib-dynamic] [no-asm] [no-dso] [no-krb5] [sctp] [386] [--prefix=DIR] [--openssldir=OPENSSLDIR] [--with-xxx[=vvv]] [--test-sanity] os/compiler[:flags]
    making all in crypto...
    /usr/bin/perl ../util/mkbuildinf.pl "cc -I. -I.. -I../include  -O" "dist" >buildinf.h
    make[1]: *** No rule to make target `../include/openssl/bio.h', needed by `cryptlib.o'.  Stop.
    make: *** [build_crypto] Error 1

There had been no such issues installing 64-bit 2.6.6 (which I fully removed before setting these environment variables and attempting the 32-bit build). And by contrast, installing 32-bit 2.6.6 with the dmg directly from python.org gave no trouble.

What am I missing? Note: I am not sure what the *python build* at the end means. I simply exported the 3 env vars:

`export CONFIGURE_OPTS="--with-arch=i386" `
`export CFLAGS="-arch i386" `
`export LDFLAGS="-arch i386" `

  [1]: https://github.com/yyuu/pyenv/wiki/Common-build-problems

**Comment by yyuu** [comment]
> /var/folders/t3/yhd5b6lj2cz_b82qzw4zcwh40000gn/T/python-build.20160114111634.64051/openssl-1.0.1q /var/folders/t3/yhd5b6lj2cz_b82qzw4zcwh40000gn/T/python-build.20160114111634.64051 ~/repos/illuminations
> Operating system: i686-apple-darwinDarwin Kernel Version 13.4.0: Sun Aug 17 19:50:11 PDT 2014; root:xnu-2422.115.4~1/RELEASE_X86_64

It seems it's failing at the build of `openssl`. Please try using `PYTHON_CONFIGURE_OPTS`, `PYTHON_CFLAGS` and `PYTHON_LDFLAGS` to specify compilation options only for CPython.

https://github.com/yyuu/pyenv/blob/425e44d064f934b78c8858b6d3ad597f46a06fa8/plugins/python-build/share/python-build/2.6.6#L2

**Comment by yyuu** [comment]
Already answered.
