### ISSUE TITLE
need documentation or command for moving PYENV_ROOT location

### ISSUE THREAD

**Issue by ancientHacker** [yyuu/pyenv#526]
As per the comments in #516, it's very hard for users to move the `PYENV_ROOT` of an existing pyenv installation.  This means that existing users who want to adopt the new recommended value of `PYENV_ROOT` need to fully uninstall pyenv (and all its installed python versions) and then reinstall everything after changing their `PYENV_ROOT` setting.  If there is a way to avoid this, it would be nice to have documentation of what that is.  Even better would be for pyenv to have programmatic support for the move.

**Comment by yyuu** [comment]
Only PR solves.
