### ISSUE TITLE
who can help me,please?

### ISSUE THREAD

**Issue by FirstBlgD** [yyuu/pyenv#527]
[python@localhost Python-2.7.11]$ python
Python 2.7.11 (default, Jan 18 2016, 19:16:04) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import readline
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named readline
>>>

**Comment by yyuu** [comment]
help yourself

**Comment by FirstBlgD** [comment]
ok

**Comment by joshfriend** [comment]
> help yourself

savage...

![](http://i.imgur.com/nXPruDN.gif)

**Comment by joshfriend** [comment]
https://github.com/yyuu/pyenv/wiki/Common-build-problems
