### ISSUE TITLE
Extremely slow when debugging in PyCharm with non-system python version

### ISSUE THREAD

**Issue by SongChen** [yyuu/pyenv#528]
I love pyenv but it take a few minutes to attach the debugger in PyCharm. If I switch my version to system, it seems fine. BTW, I used "env PYTHONUSERBASE="$SOME_PATH" open "/Applications/PyCharm CE.app" to open PyCharm

**Comment by yyuu** [comment]
Generally speaking, if the problem happens only with PyCharm, it'd be a problem of PyCharm.
