### ISSUE TITLE
pip 8.x breaks python 3.2 compatibility [$30]

### ISSUE THREAD

**Issue by ThomasWaldmann** [yyuu/pyenv#531]
From our travis ci logs:
```
+pyenv install 3.2.6
Downloading Python-3.2.6.tgz...
-> https://www.python.org/ftp/python/3.2.6/Python-3.2.6.tgz
Installing Python-3.2.6...
patching file ./Modules/readline.c
Hunk #1 succeeded at 225 (offset -6 lines).
Hunk #2 succeeded at 760 (offset -13 lines).
Hunk #3 succeeded at 813 (offset -13 lines).
Hunk #4 succeeded at 871 (offset -13 lines).
Hunk #5 succeeded at 919 with fuzz 2 (offset -24 lines).
patching file ./Lib/ssl.py
patching file ./Modules/_ssl.c
Installing pip from https://bootstrap.pypa.io/get-pip.py...
error: failed to install pip via get-pip.py
BUILD FAILED (OS X 10.10.3 using python-build 20151028)

Inspect or clean up the working tree at /var/folders/vy/rcv48w3j4w79llzf_x6qnvw40000gn/T/python-build.20160123101310.1990

Results logged to /var/folders/vy/rcv48w3j4w79llzf_x6qnvw40000gn/T/python-build.20160123101310.1990.log

Last 10 log lines:

  File "/var/folders/vy/rcv48w3j4w79llzf_x6qnvw40000gn/T/python-build.20160123101310.1990/get-pip.py", line 82, in bootstrap
    import pip
  File "/var/folders/vy/rcv48w3j4w79llzf_x6qnvw40000gn/T/tmph4tbve/pip.zip/pip/__init__.py", line 15, in <module>
  File "/var/folders/vy/rcv48w3j4w79llzf_x6qnvw40000gn/T/tmph4tbve/pip.zip/pip/vcs/mercurial.py", line 9, in <module>
  File "/var/folders/vy/rcv48w3j4w79llzf_x6qnvw40000gn/T/tmph4tbve/pip.zip/pip/download.py", line 35, in <module>
  File "/var/folders/vy/rcv48w3j4w79llzf_x6qnvw40000gn/T/tmph4tbve/pip.zip/pip/utils/ui.py", line 15, in <module>
  File "/var/folders/vy/rcv48w3j4w79llzf_x6qnvw40000gn/T/tmph4tbve/pip.zip/pip/_vendor/progress/bar.py", line 48
    empty_fill = u'∙'
                      ^
SyntaxError: invalid syntax
```

**Comment by jakirkham** [comment]
Seeing the same issue. Is there a way to force installation of a particular version of `pip` when installing Python 3.2?

**Comment by ThomasWaldmann** [comment]
seems like it must be pip < 8.0 and virtualenv < 14.0 to work with python 3.2.

**Comment by yyuu** [comment]
Hmm. I will work for this in this weekend to modify the definitions of 3.2.x to use specific version of pip....

**Comment by ThomasWaldmann** [comment]
cool, thanks!

**Comment by yyuu** [comment]
@ThomasWaldmann I pushed 1dc9ef24dfd0d04d3a566ac5b19015bee5ea5f0b and I confirmed that the installation of pip succeeded with CPython 3.2.x and Stackless 3.2.x. Could you check if it's working for you?

**Comment by ThomasWaldmann** [comment]
yup, it works for me. \o/

**Comment by ThomasWaldmann** [comment]
my above comment related to a local test with linux and python 3.2.

just wanted to leave a note here that it is still broken for everybody who gets pyenv via brew on mac os x, because it gets the not-yet-fixed pyenv version from december 2015 from there.

https://travis-ci.org/borgbackup/borg/jobs/106235185

**Comment by florianpilz** [comment]
Thanks for fixing the issue so fast! Since I'm sitting on the broken version of `homebrew` I repeated the fix manually, i.e. adjusted `/usr/local/Cellar/pyenv/20151006/default-plugins/python-build/share/python-build/3.2.6` according to https://github.com/yyuu/pyenv/commit/1dc9ef24dfd0d04d3a566ac5b19015bee5ea5f0b (replace `ensurepip` with `ez_setup`)

**Comment by yyuu** [comment]
Okay, I'll release a new version of pyenv / pyenv-virtualenv soon.

**Comment by yyuu** [comment]
I released v20160202 and sent PRs to Homebrew.

**Comment by ThomasWaldmann** [comment]
thanks much! :)

**Comment by jakirkham** [comment]
Thank you.

**Comment by chrisspen** [comment]
Why was this closed? This is still broken.

**Comment by ThomasWaldmann** [comment]
@chrisspen Well, I think it was really fixed back then. Back then, we ran our tests using pyenv and travis-ci on ubuntu 12.04, so we noticed it working again (and also not breaking for a while).

Can't say anything about the current state though, because we moved on and run on ubuntu 14.04 now, so no py 3.2 there any more - also we raised our project's minimum requirements to 3.4.

**Comment by joshfriend** [comment]
@chrisspen [It is still fixed](https://github.com/yyuu/pyenv/blob/eb2e5ac4c4429444fe2cd6d6696e77967ec688f9/plugins/python-build/share/python-build/3.2#L6). As I commented on #738, part of your test configuration is trying to install a version of `pip` which is too new.

**Comment by nathanveenkersonos** [comment]
Installed Python 3.2.6 to test something today and `pip install --update pip` cause the exact same issue found at the top. Running the latest clone of pyenv from github on an up to date install of Ubuntu 16.04.

**Comment by blueyed** [comment]
@nathanveenkersonos 
See https://github.com/pyenv/pyenv/issues/738#issuecomment-254094479.
