### ISSUE TITLE
Question: renaming a pyenv install

### ISSUE THREAD

**Issue by hfoffani** [yyuu/pyenv#533]
Is there any way to name or rename a pyenv install version?
I've tried renaming the corresponding directory (and rehashing afterwards) but when I create a new virtualenv based on that python version it fails with the message 'pip: command not found'.
In concrete:
```
env PYTHON_CONFIGURE_OPTS="--enable-framework ...etc..." pyenv install 3.5.1
cd ~/.pyenv/versions; mv 3.5.1 framework351
pyenv rehash
pyenv virtualenv framework351 plotlib
pyenv: pip: command not found
```
Also tried `pyenv virtualenv -p framework351 plotlib` but it fails.
Apologize if I'm missing something obvious here.

**Comment by yyuu** [comment]
I'd not recommend to rename directory of built Python installation because path may be hardcoded in built binary or some library files. It'd be better specify custom prefix. pyenv-alias may be what you are looking for.

https://github.com/s1341/pyenv-alias

**Comment by hfoffani** [comment]
pyenv-alias did it.
Thanks a lot!
