### ISSUE TITLE
Problem when using ~/.local with Python 2.7.11

### ISSUE THREAD

**Issue by foxx** [yyuu/pyenv#535]
It would seem that using `~/.local` with Python `2.7.11` causes `sys.path` to have the wrong order;

```
['', '/vagrant/bottlecap', '/home/vagrant/.local/lib/python2.7/site-packages/bottle-0.12.9-py2.7.egg', '/usr/lib/python2.7/dist-packages', '/home/vagrant/.local/lib/python2.7/site-packages/Werkzeug-0.11.3-py2.7.egg', '/home/vagrant/.local/lib/python2.7/site-packages/click-6.2-py2.7.egg', '/vagrant/peewee-extras', '/home/vagrant/.local/lib/python2.7/site-packages/passlib-1.6.5-py2.7.egg', '/home/vagrant/.pyenv/versions/2.7.11/lib/python27.zip', '/home/vagrant/.pyenv/versions/2.7.11/lib/python2.7', '/home/vagrant/.pyenv/versions/2.7.11/lib/python2.7/plat-linux2', '/home/vagrant/.pyenv/versions/2.7.11/lib/python2.7/lib-tk', '/home/vagrant/.pyenv/versions/2.7.11/lib/python2.7/lib-old', '/home/vagrant/.pyenv/versions/2.7.11/lib/python2.7/lib-dynload', '/home/vagrant/.local/lib/python2.7/site-packages', '/home/vagrant/.pyenv/versions/2.7.11/lib/python2.7/site-packages']
```

As you can see above, `'/usr/lib/python2.7/dist-packages'` is being injected before `/home/vagrant/.pyenv/versions/2.7.11/`.

If I remove `~/.local`, the problem goes away

**Comment by yyuu** [comment]
@foxx How did you create `~/.local`? Did you use https://github.com/mitsuhiko/pipsi or something?

**Comment by foxx** [comment]
I believe I used `--user` when installing some packages previously.

**Comment by brbsix** [comment]
I'm dealing with this issue as well. It's really troubling as I'm unable to (practically) use any Python 2.7.x other than the system one in `/usr/bin/python2`.

It's not just that `~/.local` exists, it's that `~/.local/lib/python2.7/site-packages` exists. Compare the output of `python -m site` with the following pyenvs:

2.6.6

    sys.path = [
        '/home/user',
        '/home/user/.pyenv/versions/2.6.6/lib/python26.zip',
        '/home/user/.pyenv/versions/2.6.6/lib/python2.6',
        '/home/user/.pyenv/versions/2.6.6/lib/python2.6/plat-linux3',
        '/home/user/.pyenv/versions/2.6.6/lib/python2.6/lib-tk',
        '/home/user/.pyenv/versions/2.6.6/lib/python2.6/lib-old',
        '/home/user/.pyenv/versions/2.6.6/lib/python2.6/lib-dynload',
        '/home/user/.pyenv/versions/2.6.6/lib/python2.6/site-packages',
    ]
    USER_BASE: '/home/user/.local' (exists)
    USER_SITE: '/home/user/.local/lib/python2.6/site-packages' (doesn't exist)
    ENABLE_USER_SITE: True

2.7.11

    sys.path = [
        '/home/user',
        '/home/user/.pyenv/versions/2.7.11/lib/python27.zip',
        '/home/user/.pyenv/versions/2.7.11/lib/python2.7',
        '/home/user/.pyenv/versions/2.7.11/lib/python2.7/plat-linux2',
        '/home/user/.pyenv/versions/2.7.11/lib/python2.7/lib-tk',
        '/home/user/.pyenv/versions/2.7.11/lib/python2.7/lib-old',
        '/home/user/.pyenv/versions/2.7.11/lib/python2.7/lib-dynload',
        '/home/user/.local/lib/python2.7/site-packages',
        '/home/user/.pyenv/versions/2.7.11/lib/python2.7/site-packages',
    ]
    USER_BASE: '/home/user/.local' (exists)
    USER_SITE: '/home/user/.local/lib/python2.7/site-packages' (exists)
    ENABLE_USER_SITE: True

3.6-dev

    sys.path = [
        '/home/user',
        '/home/user/.pyenv/versions/3.6-dev/lib/python36.zip',
        '/home/user/.pyenv/versions/3.6-dev/lib/python3.6',
        '/home/user/.pyenv/versions/3.6-dev/lib/python3.6/plat-linux',
        '/home/user/.pyenv/versions/3.6-dev/lib/python3.6/lib-dynload',
        '/home/user/.pyenv/versions/3.6-dev/lib/python3.6/site-packages',
    ]
    USER_BASE: '/home/user/.local' (exists)
    USER_SITE: '/home/user/.local/lib/python3.6/site-packages' (doesn't exist)
    ENABLE_USER_SITE: True

**Comment by yyuu** [comment]
At least for now, pyenv doesn't support `pip install --user`. Basically it must not be a problem since users of pyenv should have permissions to install libraries into pyenv built pythons. Patches are welcome if there's some workaround to deal with it.

**Comment by digglife** [comment]
@brbsix Thanks for your explanation. 

I simply deleted all the python libs from `.local` folder. It's OK now.
