### ISSUE TITLE
How to set --gcrootfinder when building PyPy from source

### ISSUE THREAD

**Issue by thedrow** [yyuu/pyenv#537]
The documentation is not clear about how to pass options in different stages of the PyPy build.
I need to set --gcrootfinder to shadowstack in order to debug a build failure in Alpine Linux.

**Comment by yyuu** [comment]
`PYPY_OPTS` will be passed to RPython. It'd be better to be mentioned in python-build's README.

https://github.com/yyuu/pyenv/blob/c8ab429d7b0990d901494f9bcd95f6baa5cc51af/plugins/python-build/bin/python-build#L939

**Comment by yyuu** [comment]
`PYPY_OPTS` should just work for this.
