### ISSUE TITLE
pypy-c-jit-latest requires linuxaudiodev and ossaudiodev to be built

### ISSUE THREAD

**Issue by thedrow** [yyuu/pyenv#538]
I'm compiling pypy for Alpine so I don't really need or have soundcard headers available.
See full log https://gist.github.com/thedrow/7c97d423279cf9a29147

**Comment by yyuu** [comment]
`pypy-c-jit-latest` is a nightly build binaries provided by PyPy. You'd need as same libraries as their build environment to use it.
