### ISSUE TITLE
Errors building Python 2.6.6

### ISSUE THREAD

**Issue by crdoconnor** [yyuu/pyenv#540]
Output is as follows:

    Downloading Python-2.6.6.tgz...
    -> http://www.python.org/ftp/python/2.6.6/Python-2.6.6.tgz
    Installing Python-2.6.6... 
    patching file setup.py
    Hunk #1 succeeded at 354 (offset 9 lines).
    patching file ./Lib/ssl.py
    patching file ./Modules/_ssl.c
    Hunk #3 succeeded at 1691 (offset -1 lines).
    patching file ./Modules/readline.c
    Hunk #1 succeeded at 199 (offset -7 lines).
    Hunk #2 succeeded at 698 (offset -51 lines).
    Hunk #3 succeeded at 808 (offset -51 lines).
    Hunk #4 succeeded at 848 with fuzz 2 (offset -70 lines).
    patching file ./setup.py
    Hunk #1 succeeded at 1698 (offset 23 lines).
    patching file ./Lib/ssl.py
    Hunk #1 FAILED at 61.
    Hunk #2 succeeded at 394 (offset 12 lines).
    1 out of 2 hunks FAILED -- saving rejects to file ./Lib/ssl.py.rej
    patching file ./Modules/_ssl.c
    Hunk #1 FAILED at 62.
    Hunk #2 FAILED at 300.
    Hunk #3 FAILED at 1688.
    3 out of 3 hunks FAILED -- saving rejects to file ./Modules/_ssl.c.rej

    BUILD FAILED (Ubuntu 15.10 using python-build 20160130)

Build is on a 64 bit Ubuntu wily machine. libssl-dev is installed, as is libreadline6.

Any ideas?

**Comment by yyuu** [comment]
It's failing at applying patches. I confirmed that I can apply patches to Python-2.6.6.tgz, though.

https://github.com/yyuu/pyenv/tree/c8ab429d7b0990d901494f9bcd95f6baa5cc51af/plugins/python-build/share/python-build/patches/2.6.6/Python-2.6.6

**Comment by crdoconnor** [comment]
My mistake. I had an old patch file in that directory.
