### ISSUE TITLE
How to specify minor versions only

### ISSUE THREAD

**Issue by Tjorriemorrie** [yyuu/pyenv#541]
I wish to install minor versions only. The library should pull the latest patch version itself. E.g.

> pyenv install 2.7

should instal 2.7.latest, but it seems to only install 2.7.0.

Also, how would I patch a version? e.g. upgrading 2.7.8 to 2.7.9/latest?

Is this not supported? Do I manually have to specify the patch version as well?

**Comment by yyuu** [comment]
`pyenv install 2.7` should install 2.7, not the latest release of 2.7. I don't like implicit manner when specifying versions.

And, upgrading between patch releases (e.g. 2.7.8 to 2.7.9) isn't supported.
