### ISSUE TITLE
ImportError: No module named pyexpat

### ISSUE THREAD

**Issue by ymkjp** [yyuu/pyenv#544]
I got error on OS X 10.11.3 when I try to install v2.7.10 as following:

```
$ xcode-select --install
$ brew update && brew install pyenv-virtualenv
$ eval "$(pyenv init -)"
$ eval "$(pyenv virtualenv-init -)"
$ CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install -v 2.7.10
```

```
error: failed to install pip via get-pip.py

BUILD FAILED (OS X 10.11.3 using python-build 20151028)

Inspect or clean up the working tree at /var/folders/mt/vnl_kg3s72dgych6j2j4djxmlbfpd_/T/python-build.20160215184029.70850
Results logged to /var/folders/mt/vnl_kg3s72dgych6j2j4djxmlbfpd_/T/python-build.20160215184029.70850.log

Last 10 log lines:
    info = _mac_ver_xml()
  File "/Users/kenta.ky.yamamoto/.pyenv/versions/2.7.10/lib/python2.7/platform.py", line 786, in _mac_ver_xml
    pl = plistlib.readPlist(fn)
  File "/Users/kenta.ky.yamamoto/.pyenv/versions/2.7.10/lib/python2.7/plistlib.py", line 78, in readPlist
    rootObject = p.parse(pathOrFile)
  File "/Users/kenta.ky.yamamoto/.pyenv/versions/2.7.10/lib/python2.7/plistlib.py", line 401, in parse
    from xml.parsers.expat import ParserCreate
  File "/Users/kenta.ky.yamamoto/.pyenv/versions/2.7.10/lib/python2.7/xml/parsers/expat.py", line 4, in <module>
    from pyexpat import *
ImportError: No module named pyexpat
```

[**python-build.20160215184029.70850.log**](https://gist.github.com/ymkjp/0cf9b91df6ea656fb4fb#file-python-build-20160215184029-70850-log)

Here's whole output in `/var/folders/mt/vnl_kg3s72dgych6j2j4djxmlbfpd_/T/python-build.20160215184029.70850.log`.

I recently update my OS X to Mavericks and it may cause this error, but I have no idea to solve this.
Any suggestions?

Thanks.

**Comment by yyuu** [comment]
Your system's `expat` installation is broken, or there's broken build in `/usr/local/lib` or so. Don't know why, though. It's a problem of yours anyways.

```
*** WARNING: renaming "pyexpat" since importing it failed: dlopen(build/lib.macosx-10.11-x86_64-2.7/pyexpat.so, 2): Symbol not found: _XML_ErrorString
  Referenced from: build/lib.macosx-10.11-x86_64-2.7/pyexpat.so
  Expected in: flat namespace
 in build/lib.macosx-10.11-x86_64-2.7/pyexpat.so
building '_elementtree' extension
clang -fno-strict-aliasing -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DHAVE_EXPAT_CONFIG_H=1 -DUSE_PYEXPAT_CAPI -I/private/var/folders/mt/vnl_kg3s72dgych6j2j4djxmlbfpd_/T/python-build.20160215184029.70850/Python-2.7.10/./Modules/expat -I/private/var/folders/mt/vnl_kg3s72dgych6j2j4djxmlbfpd_/T/python-build.20160215184029.70850/Python-2.7.10/Mac/Include -I/private/var/folders/mt/vnl_kg3s72dgych6j2j4djxmlbfpd_/T/python-build.20160215184029.70850/Python-2.7.10/Mac/Include -I. -IInclude -I./Include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/usr/local/include -I/private/var/folders/mt/vnl_kg3s72dgych6j2j4djxmlbfpd_/T/python-build.20160215184029.70850/Python-2.7.10/Include -I/private/var/folders/mt/vnl_kg3s72dgych6j2j4djxmlbfpd_/T/python-build.20160215184029.70850/Python-2.7.10 -c /private/var/folders/mt/vnl_kg3s72dgych6j2j4djxmlbfpd_/T/python-build.20160215184029.70850/Python-2.7.10/Modules/_elementtree.c -o build/temp.macosx-10.11-x86_64-2.7/private/var/folders/mt/vnl_kg3s72dgych6j2j4djxmlbfpd_/T/python-build.20160215184029.70850/Python-2.7.10/Modules/_elementtree.o
clang -bundle -undefined dynamic_lookup -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/openssl/lib -L/Users/kenta.ky.yamamoto/.pyenv/versions/2.7.10/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/openssl/lib -L/Users/kenta.ky.yamamoto/.pyenv/versions/2.7.10/lib -fno-strict-aliasing -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I. -IInclude -I./Include -I/usr/local/opt/readline/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/Users/kenta.ky.yamamoto/.pyenv/versions/2.7.10/include build/temp.macosx-10.11-x86_64-2.7/private/var/folders/mt/vnl_kg3s72dgych6j2j4djxmlbfpd_/T/python-build.20160215184029.70850/Python-2.7.10/Modules/_elementtree.o -L/usr/local/opt/readline/lib -L/usr/local/opt/openssl/lib -L/Users/kenta.ky.yamamoto/.pyenv/versions/2.7.10/lib -L/usr/local/lib -o build/lib.macosx-10.11-x86_64-2.7/_elementtree.so
```

**Comment by wangwenpei** [comment]
I have same issue on Mac and I solved it. the problem is you use an old MacOS X but use a newer Xcode. you have to upgrade your system to Sierra.

**Comment by murawskikrzysiek** [comment]
I am using Sierra and also seeing this issue...

**Comment by wangwenpei** [comment]
@murawskikrzysiek  remove your `C_INCLUDE_PATH` `LDFLAGS` variable  ...etc...  and try it again.

**Comment by justinjdickow** [comment]
Also having this issue running `pyenv install 2.7.14` on MacOS 10.13.2

**Comment by wangwenpei** [comment]
@justinjdickow  last week, this error caused again for me... 

you can try this

- make sure your pyenv is latest version.
- PKG_CONFIG_PATH="$(brew --prefix openssl)/lib/pkgconfig" pyenv install <VERSION>

**Comment by justinjdickow** [comment]
@wangwenpei I'm still seeing the same issue

my pyenv is version 1.2.0

I'm using the following flags now

```
export CFLAGS="-I$(xcrun --show-sdk-path)/usr/include"
export CFLAGS="-I$(brew --prefix readline)/include $CFLAGS"
export LDFLAGS="-L$(brew --prefix readline)/lib $LDFLAGS"
export CFLAGS="-I$(brew --prefix openssl)/include $CFLAGS"
export LDFLAGS="-L$(brew --prefix openssl)/lib $LDFLAGS"
export PKG_CONFIG_PATH="$(brew --prefix openssl)/lib/pkgconfig"
```

**Comment by jalevin** [comment]
Besides pyenv I also could not install ruby versions via rbenv. At this point I started looking at the system. I'd recently upgraded and used the migration assistant to move to a new machine.

1. go to Applications and run Xcode. I had additional packages install
2. run brew doctor. if any files in /usr/local/include show up you have 2 options. Either rename the directory to something else like include_old or remove the offending entries. I chose the first.

``` sudo mv /usr/local/include /usr/local/include_old ```
``` sudo mkdir /usr/local/include ```
``` sudo chown $YOU_USERNAME:admin /usr/local/include ```

afterward, I was able to install ruby and python versions

**Comment by henriquebastos** [comment]
This worked for me:

```
SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk MACOSX_DEPLOYMENT_TARGET=10.14 pyenv install 3.7.3
```

**Comment by danodonovan** [comment]
@henriquebastos solution also worked for me, installing `3.7.4`
```
SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk \
MACOSX_DEPLOYMENT_TARGET=10.14 \
pyenv install 3.7.4
```

**Comment by pancodia** [comment]
Solution from @henriquebastos also work for me

```
SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk \
> MACOSX_DEPLOYMENT_TARGET=10.14 \
> python-build 3.6.8 ~/.runtimes/Python36
```

**Comment by a-ninja** [comment]
Solution from @henriquebastos also work for me:
SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk \
> MACOSX_DEPLOYMENT_TARGET=10.14 \
> pyenv install 3.7.4

**Comment by waffletower** [comment]
> SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk MACOSX_DEPLOYMENT_TARGET=10.14 pyenv install 3.7.

Would be really nice if these envvar dependencies were instrumented in `pyenv install` with sensible defaults on MacOS

**Comment by fnl** [comment]
Had the same problem when building (any) python version(s), `ModuleNotFoundError: No module named 'pyexpat'` and fixed it with the $SDKROOT setup described in this (closed?) ticket. Thank you, @henriquebastos !

**Comment by palmerc** [comment]
This comes up again. From the log you can see that 'pyenv install 3.7.4' fails to link expat because when linking pyexpat it doesn't try to link in expat and therefore the symbol XML_ErrorString is missing.

`clang -bundle -undefined dynamic_lookup -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/Users/admin/.pyenv/versions/3.7.4/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/Users/admin/.pyenv/versions/3.7.4/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/Users/admin/.pyenv/versions/3.7.4/lib -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/usr/local/opt/readline/include -I/usr/local/opt/readline/include -I/Users/admin/.pyenv/versions/3.7.4/include build/temp.macosx-10.14-x86_64-3.7/private/var/folders/x0/9tltnhy90v7fptftj3b7bl9r0000gn/T/python-build.20190913105722.52617/Python-3.7.4/Modules/pyexpat.o build/temp.macosx-10.14-x86_64-3.7/private/var/folders/x0/9tltnhy90v7fptftj3b7bl9r0000gn/T/python-build.20190913105722.52617/Python-3.7.4/Modules/expat/xmlparse.o build/temp.macosx-10.14-x86_64-3.7/private/var/folders/x0/9tltnhy90v7fptftj3b7bl9r0000gn/T/python-build.20190913105722.52617/Python-3.7.4/Modules/expat/xmlrole.o build/temp.macosx-10.14-x86_64-3.7/private/var/folders/x0/9tltnhy90v7fptftj3b7bl9r0000gn/T/python-build.20190913105722.52617/Python-3.7.4/Modules/expat/xmltok.o -L/usr/local/opt/readline/lib -L/Users/admin/.pyenv/versions/3.7.4/lib -L/usr/local/lib -o build/lib.macosx-10.14-x86_64-3.7/pyexpat.cpython-37m-darwin.so`

**Comment by palmerc** [comment]
So there pyexpatns.h renames a bunch of symbols and that seems to be the root of the trouble

**Comment by palmerc** [comment]
Building using the same tarball as pyenv downloads, configure and make works.

**Comment by robgolding** [comment]
Note that if you have the Xcode Command Line Tools installed, but not `Xcode.app` itself, you can use `/Library/Developer/CommandLineTools/SDKs/` instead:

```
SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk MACOSX_DEPLOYMENT_TARGET=10.14 pyenv install ...
```

**Comment by Zeesy** [comment]
@robgolding 's suggestion worked great for me after having some difficulty with @henriquebastos 's. Running version install for 3.5.3 on MacOS 10.14. 

I'd note for anyone having difficulty that install for v 3.5.2 fails regardless of install method on both Ubuntu and MacOS.

**Comment by terrisgit** [comment]
See also https://github.com/pyenv/pyenv/issues/950#issuecomment-662525606

**Comment by ruohola** [comment]
> > SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk MACOSX_DEPLOYMENT_TARGET=10.14 pyenv install 3.7.
> 
> Would be really nice if these envvar dependencies were instrumented in `pyenv install` with sensible defaults on MacOS. For example, the above path is really just a symbolic link to: `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk` which remains stable release to release.
> 
> I also had success building `3.7.4` using:
> 
> ```shell
> SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk \
> pyenv install 3.7.4
> ```
> 
> without setting an explicit deployment target.

This worked for me with pyenv 2.2.3 when trying to install Python 3.10.1 on macOS 12.1 👍

**Comment by justinjdickow** [comment]
It's amazing that this issue still gets comments after all these years. MacOS now has generic symlinked defaults for both of these that could be checked by pyenv to export for SDKROOT

```
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
```

**Comment by telemachus** [comment]
This same tip from @henriquebastos saved me again today, nearly three years after he posted it. I agree with @justinjdickow that it would be great if pyenv took this into account automatically.

Setting that aside, how about adding a note about this to the [Common build problems wiki page](https://github.com/pyenv/pyenv/wiki/Common-build-problems). I don't know if that's the kind of thing where a pull request makes sense, but I'm happy to do that if it would help. /cc @native-api

**Comment by native-api** [comment]
@telemachus CPython versions <3.7.8 do not officially support MacOS 11+ -- so not sure how or why you expect to be able to use them there seamlessly.

We do however accept PRs from interested users to make releases support additional, officially unsupported environments, see [CONTRIBUTING.md](https://github.com/pyenv/pyenv/blob/master/CONTRIBUTING.md).

Looks like that invocation run the build in some kind of compatibility mode with an older MacOS version.
So the extra logic needs to somehow decide, depending on running environment, whether to set these envvars and to which values.

**Comment by native-api** [comment]
> I found this issue when I was trying to install Python 3.10.5 on macOS 12.4.

You shouldn't be needing any workarounds for recent versions. So this is either a problem with Pyenv, or, more probable, a problem with your XCode installation.

Try reinstalling XCode command-line tools. If that doesn't help, report it as a separate issue. Once we know the cause, we'll know what advice to provide.

**Comment by relaxnow** [comment]
Still getting `ModuleNotFoundError: No module named 'pyexpat'` on running:
```
SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk \
pyenv install 3.11.6
```
```
% pyenv --version
pyenv 2.3.32
% sw_vers -productVersion 
13.6.1
```
