### ISSUE TITLE
[Question] Disable shim

### ISSUE THREAD

**Issue by robsonpeixoto** [yyuu/pyenv#548]
I really love the pyenv + virtualenv, but I'm not a shim fan.
Are there a way to disable it?

**Comment by yyuu** [comment]
pyenv will just work fine without having pyenv-init. Try prepending ~/.pyenv/bin to your PATH and manage PATHs to pythons in ~/.pyenv/versions by youself.

**Comment by robsonpeixoto** [comment]
Thanks @yyuu

**Comment by blueyed** [comment]
@robsonpeixoto
What's your impression/feedback?

**Comment by robsonpeixoto** [comment]
@blueyed it's don't work well, because a script can't set a environment variable =/

I miss something like the `pythonz locate 2.7.11`. Read more here: https://github.com/saghul/pythonz#print-the-path-to-the-interpreter-of-a-given-version

**Comment by yyuu** [comment]
@robsonpeixoto "pyenv prefix ${version}" could be the thing you're looking for.

**Comment by robsonpeixoto** [comment]
Thanks @yyuu
