### ISSUE TITLE
How to install a `dev` version python 2.7.

### ISSUE THREAD

**Issue by d0u9** [yyuu/pyenv#554]
How could I install python 2.7 to support `dev` mode?

**Comment by joshfriend** [comment]
`$ pyenv install 2.7-dev`

**Comment by d0u9** [comment]
@joshfriend why there isn't libpython2.7.so in `2.7-dev`...

**Comment by yyuu** [comment]
By default CPython will be built as '--disable-shared'. "PYTHON_CONFIGURE_OPTS='--enable-shared' pyenv install -v 2.7.11" could be what you are looking for. It's not so called dev mode, though.

**Comment by TaridaGeorge** [comment]
I couldn't make it work with:
PYTHON_CONFIGURE_OPTS='--enable-shared' pyenv install -v 3.10-dev
but this works:
CONFIGURE_OPTS='--enable-shared' pyenv install "3.10-dev"
