### ISSUE TITLE
[Question] Build Failed in Mac OS X 10.10 - configure: error: cannot compute sizeof (off_t)

### ISSUE THREAD

**Issue by mxgit1090** [yyuu/pyenv#559]
I have tried so many times to install python 3.5.1 by pyenv.
but I still got this following message:

My environment is:
Mac OS X: 10.10.5
pyenv: 20150310 (But I install 20160301 by Homebrew ...)
gcc: Apple LLVM version 7.0.2 (clang-700.1.81)

```sh
Downloading Python-3.5.1.tgz...
-> https://www.python.org/ftp/python/3.5.1/Python-3.5.1.tgz
Installing Python-3.5.1...

BUILD FAILED (OS X 10.10.5 using python-build 20160130)

Inspect or clean up the working tree at /var/folders/sb/b75s98mj70n1mrl9__xjlwjw0000gn/T/python-build.20160320155059.60678
Results logged to /var/folders/sb/b75s98mj70n1mrl9__xjlwjw0000gn/T/python-build.20160320155059.60678.log

Last 10 log lines:
checking size of long long... 8
checking for long double support... yes
checking size of long double... 16
checking for _Bool support... yes
checking size of _Bool... 1
checking for uintptr_t... no
checking size of off_t... configure: error: in `/var/folders/sb/b75s98mj70n1mrl9__xjlwjw0000gn/T/python-build.20160320155059.60678/Python-3.5.1':
configure: error: cannot compute sizeof (off_t)
See `config.log' for more details
make: *** No targets specified and no makefile found.  Stop.
```

I installed pyenv with homebrew, and whether I set the path written on the indication of the homebrew installing process or not, the error message still appearing.

Is the "make" or C / C++ libraries issues? Do I need to update the Library?
Thank you !

**Comment by yyuu** [comment]
Obviously this must be a kind of C / C++ build environment (compiler or headers?) issue. I'm pretty not sure why `size_of(off_t)` failed though....

**Comment by yyuu** [comment]
I couldn't reproduce this. It might be worth file an issue to CPython if the problem persists.
