### ISSUE TITLE
fail to switch from system packages(pip)

### ISSUE THREAD

**Issue by snailchan** [yyuu/pyenv#562]
Hello, everyone.
I'm confused by the failure that, after I succeeded  installing pyenv and ananconda2.5 by pyenv, I used 'pip --version' to verify whether the pyenv work well. Disappointedly, it output this below
Lenovo-Y50-70:~$ pyenv versions
  system
\* anaconda2-2.5.0 (set by /home/snailchan/.pyenv/version)
Lenovo-Y50-70:~$ pip --version
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)
snailchan@snailchan-Lenovo-Y50-70:~$ 

Is this correct?In my another computer, it doesn't like this, outputting anaconda pip package.
does matter the installation of leveldb, so I must fix it.
How can I fix it?

**Comment by yyuu** [comment]
Make sure you have pyenv's `shims` before other system paths (e.g. `/usr/bin`, `/usr/local/bin`) in your `$PATH`. Basically it's your system you should manage yourself.
