### ISSUE TITLE
How to locate the path of python-build?

### ISSUE THREAD

**Issue by huntzhan** [yyuu/pyenv#565]
I'm writing a tool to download the source packages defined in [python-build](https://github.com/yyuu/pyenv/tree/master/plugins/python-build/share/python-build), and hence I need to locate the path of directory (`pyenv/plugins/python-build/share/python-build/`).

I've installed pyenv by using homebrew, as a consequence, I couldn't locate the directory mentioned above based on `PYENV_ROOT`.

Here's the files within my `$PYENV_ROOT`:

```
➜  echo $PYENV_ROOT 
/usr/local/var/pyenv
➜  cd $PYENV_ROOT
➜  tree -L 1
.
├── cache
├── shims
├── version
└── versions

3 directories, 1 file
```

And the `python-build` directory is in the path of `/usr/local/Cellar/pyenv/20160310/plugins/python-build/share/python-build`

I've tried to solve the problem by reading:

* https://github.com/Homebrew/homebrew/blob/master/Library/Formula/pyenv.rb
* https://github.com/yyuu/pyenv/blob/master/libexec/pyenv#L120 (En...where's the `python-install` script?)

It seems that `pyenv install` could somehow locate the path of [pyenv-install](https://github.com/yyuu/pyenv/blob/master/plugins/python-build/bin/pyenv-install). I wondering if you could show me the way to do that.

Thanks.

**Comment by yyuu** [comment]
This could be what you were looking for. In brew's formula, actually it tries to install `pyenv-install`, `pyenv-uninstall` and `python-build` into brew's path for executables (==> `/usr/local/bin` by default). `pyenv-install` can execute `python-build` regardless of its installed location if it can be found in `PATH`.

https://github.com/Homebrew/homebrew/blob/9e5614117b35f049a139fb5141c7f4214ba9ee6b/Library/Formula/pyenv.rb#L18-L20
https://github.com/yyuu/pyenv/blob/v20160310/plugins/python-build/bin/pyenv-install#L244

**Comment by yyuu** [comment]
If you installed `pyenv` via `brew`, you'd be able to locate the `python-build` by `$(brew --prefix pyenv)/plugins/python-build`. Actually there's no general way to locate `python-build`'s installed location, as far as I could remember.

**Comment by huntzhan** [comment]
Thanks, solved my problem!
