### ISSUE TITLE
pyenv not recognising system 3.5.1 on ubuntu 16.04

### ISSUE THREAD

**Issue by MortalCatalyst** [yyuu/pyenv#569]
Pyenv cannot see the system installed python version of 3.5.1 on ubuntu xenial.

```bash
sayth@sayth-E6410:~$ pyenv versions
* system (set by /home/sayth/.pyenv/version)
  miniconda3-latest
  miniconda-latest
sayth@sayth-E6410:~$ python --version
Python 2.7.11+
sayth@sayth-E6410:~$ pyenv global 3.5.1
pyenv: version `3.5.1' not installed
sayth@sayth-E6410:~$ pyenv global 3.5
pyenv: version `3.5' not installed
sayth@sayth-E6410:~$ PYTHON3 --version
PYTHON3: command not found
sayth@sayth-E6410:~$ python3 --version
Python 3.5.1+
sayth@sayth-E6410:~$ pyenv global 3.5.1+
pyenv: version `3.5.1+' not installed
sayth@sayth-E6410:~$ pyenv update
```

**Comment by thomasjo** [comment]
You cannot use `pyenv global 3.5.1` since it is clearly not a version of Python managed by pyenv. You can however do `pyenv global system`.

If you want to be able to use your original command, you'll have to install 3.5.1 via `pyenv install 3.5.1` first.

**Comment by MortalCatalyst** [comment]
The issue is that by using system I get python 2.7.11 not 3.5.1

```bash
sayth@sayth-E6410:~$ pyenv global system
sayth@sayth-E6410:~$ python --version
Python 2.7.11+
sayth@sayth-E6410:~$ 
```

**Comment by thomasjo** [comment]
> No way to choose which system I want

There's only one "system". It basically means that pyenv does nothing. It's shims just point directly whatever is the "system level" Python distribution. That essentially boils down to your `PATH` environment variable, and whatever the `python` (and `python2`, `python3` etc) executable/alias points to on your machine.

To see what the pyenv `python` shim points to, run `pyenv which python`.

**Comment by MortalCatalyst** [comment]
Thanks
