### ISSUE TITLE
Is 0.6s for pyenv init normal?

### ISSUE THREAD

**Issue by cpaulik** [yyuu/pyenv#571]
This slows down startup of my shell annoyingly and is also a problem in emacs when I want to get shell variables since a new shell has to be started every time. 
```
time (eval "$(pyenv init -)")  
( eval "$(pyenv init -)"; )  0.59s user 0.20s system 112% cpu 0.700 total
```
Does this more than set the PATH correctly? If so I will just hardcode the PATH.

**Comment by yyuu** [comment]
Generally speaking it's hard to say if "0.6s" is slow or not because it's (mostly) depending on system's I/O performance.

If `eval "$(pyenv init -)"` is slow for your system, please try using `eval "$(pyenv init - --no-rehash)"`. With it, the initialization code will omit `pyenv rehash` which creates many of files and it should help improving the performance.

https://github.com/yyuu/pyenv/blob/v20160310/libexec/pyenv-init#L28-L31

**Comment by cpaulik** [comment]
Thanks. the `no-rehash` option did the trick.

**Comment by IlyaSemenov** [comment]
To whoever lands here: even though `--no-rehash` indeed speed things up, running pyenv+rbenv+jenv+nodenv from ~/.bash_profile is still noticeably slow (100-200 ms each give at least 0.5 second startup delay).

I ended up ditching bash and installing `fish`, `fisherman` and corresponding fisherman plugins (pyenv, nodenv). Now a new shell opens instantly.

**Comment by ssbarnea** [comment]
Apparently on zsh, `--no-rehash` saves only ~100ms from ~200ms, which is a LOT for anything that runs on login. Recommendation to use fish does not make sense for most people, we need to look into making the init <10ms.

**Comment by IlyaSemenov** [comment]
I'm (now) using zsh with zinit and this:

```zsh
PYENV_ROOT="$HOME/.pyenv"
if [[ -n "$PYENV_ROOT" && -d "$PYENV_ROOT" ]]; then
    if [[ ! -f "${PYENV_ROOT}/zpyenv.zsh" ]]; then
        {
            pyenv init - --no-rehash zsh
            pyenv virtualenv-init - zsh
        } >"${PYENV_ROOT}/zpyenv.zsh"
    fi

    zinit snippet "${PYENV_ROOT}/zpyenv.zsh"
fi
```

which runs <10ms.

**Comment by ssbarnea** [comment]
I was considering caching the result of `pyenv init -` in order to avoid extra time but apparently what I get locally is not safe to be cached:
```
$ pyenv init -
export PATH="/Users/ssbarnea/.pyenv/shims:${PATH}"
export PYENV_SHELL=zsh
source '/usr/local/Cellar/pyenv/HEAD-16d0f50/libexec/../completions/pyenv.zsh'
command pyenv rehash 2>/dev/null
pyenv() {
  local command
  command="${1:-}"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  activate|deactivate|rehash|shell)
    eval "$(pyenv "sh-$command" "$@")";;
  *)
    command pyenv "$command" "$@";;
  esac
}
```
