### ISSUE TITLE
Call a different pyenv environment from within a running Python script

### ISSUE THREAD

**Issue by jgrover** [yyuu/pyenv#574]
I'm running a python script that calls another python script. The first script requires Python 3.5.1.  The second requires 2.7.10.  In the second script's directory, I manually set "pyenv local 2.7.10".  Everything appears to be good until I run the first python script (from a different directory), which attempts to run the second with Python3.

Even when I set the current working directory to be the location of the second script, it still reports that it is using Python3.  When I'm outside of Python, python --version reports accurately as 2.7.10.

Is what I'm trying to do not possible with the current pyenv implementation?

**Comment by joshfriend** [comment]
Read this section in the [README](https://github.com/yyuu/pyenv#choosing-the-python-version):

> You can activate multiple versions at the same time, including multiple versions of Python2 or Python3 simultaneously.

**Comment by jgrover** [comment]
Perfect!  Thanks.
