### ISSUE TITLE
Support reading Python version from runtime.txt file?

### ISSUE THREAD

**Issue by thbar** [yyuu/pyenv#575]
(I'm a newcomer to Python so bear with me!)

Heroku relies on a [runtime.txt](https://github.com/heroku/heroku-buildpack-python#specify-a-python-runtime) file to decide which version to pick.

I figured out it would be nice if I could also use `pyenv` (which I'm just discovering) to pick the same version.

Is there a way (even a solid trick) to make sure `pyenv` would also read from there?

thanks!

**Comment by thbar** [comment]
I was mistaken and apparently, it seems that a symlink works perfectly so far. Closing!

**Comment by joshfriend** [comment]
This won't work even with a symlink. If you read the heroku page you linked you will notice that the names of the versions of python are different between heroku and pyenv.

* pyenv: `2.7.11`
* heroku: `python-2.7.11`
