### ISSUE TITLE
Symbol not found: _PyUnicodeUCS2_AsUTF8String

### ISSUE THREAD

**Issue by robsonpeixoto** [yyuu/pyenv#578]
I'm always getting the error `Symbol not found: _PyUnicodeUCS2_AsUTF8String` with the python installed by pyenv. I have teste the python installed using `brew install python` and works like a charm.

Any idea how to fix it? I got this error with `ujson` and with `lxml`.

Thanks

```
ImportError: dlopen(/Users/robinho/.pyenv/versions/2.7.11/envs/caronte/lib/python2.7/site-packages/ujson.so, 2): Symbol not found: _PyUnicodeUCS2_AsUTF8String
  Referenced from: /Users/robinho/.pyenv/versions/2.7.11/envs/caronte/lib/python2.7/site-packages/ujson.so
  Expected in: flat namespace
 in /Users/robinho/.pyenv/versions/2.7.11/envs/caronte/lib/python2.7/site-packages/ujson.so
```

**Comment by joshfriend** [comment]
The comments on #257 should help you out, namely [this one](https://github.com/yyuu/pyenv/issues/257#issuecomment-195836492)

**Comment by robsonpeixoto** [comment]
Thanks @joshfriend
