### ISSUE TITLE
Add support for PyPy 5.1

### ISSUE THREAD

**Issue by thedrow** [yyuu/pyenv#579]
PyPy 5.1 was released [yesterday](http://morepypy.blogspot.co.il/2016/04/pypy-51-released.html).
Can we add it to the build scripts?

**Comment by joshfriend** [comment]
Fun fact: If you build it from source, you get to watch it draw fractals while you wait forever for it to compile:

![](https://i.imgur.com/Z4BFBz0.png)

**Comment by alex** [comment]
Any chance of issuing a release so we can package this up for homebrew? Thanks!

**Comment by joshfriend** [comment]
@alex [`v20160422`](https://github.com/yyuu/pyenv/tree/v20160422)
