### ISSUE TITLE
installation using homebrew, PATH not correct

### ISSUE THREAD

**Issue by potatoker** [yyuu/pyenv#583]
this is how I install pyenv on my mac:    
       
    brew install pyenv

and my zshenv looks like:

    ........(my other code)
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"

    if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

then I found that when I echo $path , only shows:
    
    /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

but $PYENV_ROOT is valid

why my Path does not change?

and I can not use global command, it won't change my python version:

**Comment by yyuu** [comment]
I just guess you're overriding `$PATH` somewhere in your zsh configuration. I definitely don't know your configuration, though.
