### ISSUE TITLE
checksum mismatch for portable pypy 5.1

### ISSUE THREAD

**Issue by DRMacIver** [yyuu/pyenv#586]
When trying to install pypy-5.1 using the latest pyenv git (78b9cee98e442c16d3f6ce4eecece932e1eb170b) I get a checksum mismatch:

```
checksum mismatch: pypy-5.1-linux_x86_64-portable.tar.bz2 (file is corrupt)
expected 893507603a58b8983b69924e60591de39b8f71f70ba36d6e3894db8f7c49c3ea, got b2df9b0127457d1c3cc0dc9b8f027a53569ccd3ba5a79012d641e576d9cc003a
```
According to [the portable pypy README](https://github.com/squeaky-pl/portable-pypy) the actual checksum is correct and the expected one is not.

I'm running this on Ubuntu.

**Comment by yyuu** [comment]
Fixed~
