### ISSUE TITLE
pip shim does not get added to ~/.pyenv/shims

### ISSUE THREAD

**Issue by pcgilday** [yyuu/pyenv#590]
I installed pyenv, but there is no shim for pip. I thought at first that this was a setup problem, not a bug, so after spinning my wheels for a while trying to figure it out I posted on [stackoverflow](http://stackoverflow.com/questions/37038081/shimming-pip-with-pyenv). However, the comment from the docs below makes me believe this should have been done in the initial rehashing. I apologize if this is more of a question then a bug, but I could not figure this out and the docs make it seem like it should work. I am happy to help and contribute if this is a bug, or if docs need to be updated, I just don't know where to start.

Note in docs that made my think this should work after rehashing:

`Through a process called rehashing, pyenv maintains shims in that directory to match every Python command across every installed version of Python—python, pip, and so on.`

**Comment by yyuu** [comment]
`pyenv rehash` is a process to generate _shim_ scripts from all executables matched to `$(pyenv root)/versions/*/bin/*`. It will be called from `pyenv init -` to update shims during the initialization if the `pyenv init -` is called with `--no-rehash`.

https://github.com/yyuu/pyenv/blob/2017dd0c25467caffd6b9d6749f80dc502128842/libexec/pyenv-rehash#L87-L89
https://github.com/yyuu/pyenv/blob/2017dd0c25467caffd6b9d6749f80dc502128842/libexec/pyenv-init#L107

After clean installation of `pyenv`, obviously there should be nothing in `~/.pyenv/versions` and it lets `pyenv rehash` to skip working. `pyenv rehash` will not care about executables installed in `system` python. You need to install at least 1 python version in `pyenv` to generate `shims`.

**Comment by pcgilday** [comment]
@yyuu I have version 2.7.11 installed, and I have the correct shim for this (as well as others like 2to3). However, there is no shim for pip, it appears pip is not in the bin directory for my python version, so based on your explanation, this makes sense. However, shouldn't pip be in the bin directory here? I was under the impression pip was bundled with python for versions 2.7.9 and up, is that not the case when using pyenv?

```
$ ll .pyenv/versions/2.7.11/bin/
total 4056
drwxr-xr-x  12 patrick  staff      408 May  4 18:15 .
drwxr-xr-x   6 patrick  staff      204 May  4 18:15 ..
-rwxr-xr-x   1 patrick  staff      128 May  4 18:15 2to3
-rwxr-xr-x   1 patrick  staff      126 May  4 18:15 idle
-rwxr-xr-x   1 patrick  staff      111 May  4 18:15 pydoc
lrwxr-xr-x   1 patrick  staff        7 May  4 18:15 python -> python2
lrwxr-xr-x   1 patrick  staff       14 May  4 18:15 python-config -> python2-config
lrwxr-xr-x   1 patrick  staff        9 May  4 18:15 python2 -> python2.7
lrwxr-xr-x   1 patrick  staff       16 May  4 18:15 python2-config -> python2.7-config
-rwxr-xr-x   1 patrick  staff  2022332 May  4 18:15 python2.7
-rwxr-xr-x   1 patrick  staff     1714 May  4 18:15 python2.7-config
-rwxr-xr-x   1 patrick  staff    18574 May  4 18:15 smtpd.py
```

```
$ ll .pyenv/shims/
total 80
drwxr-xr-x  12 patrick  staff  408 May 10 10:52 .
drwxr-xr-x  22 patrick  staff  748 May  4 18:10 ..
-rwxr-xr-x   1 patrick  staff  408 May  4 18:15 2to3
-rwxr-xr-x   1 patrick  staff  408 May  4 18:15 idle
-rwxr-xr-x   1 patrick  staff  408 May  4 18:15 pydoc
-rwxr-xr-x   1 patrick  staff  408 May  4 18:15 python
-rwxr-xr-x   1 patrick  staff  408 May  4 18:15 python-config
-rwxr-xr-x   1 patrick  staff  408 May  4 18:15 python2
-rwxr-xr-x   1 patrick  staff  408 May  4 18:15 python2-config
-rwxr-xr-x   1 patrick  staff  408 May  4 18:15 python2.7
-rwxr-xr-x   1 patrick  staff  408 May  4 18:15 python2.7-config
-rwxr-xr-x   1 patrick  staff  408 May  4 18:15 smtpd.py
```

**Comment by nicktimko** [comment]
Strange, but you could try [`get-pip.py`](https://pip.pypa.io/en/stable/installing/).

**Comment by Brawnd0** [comment]
@pcgilday are you by any chance install python with --enable-framework option?

When installing python 2.7.11 with the below command, I have no pip binaries anywhere in ~/.pyenv.  I've been able to reproduce this on 2 separate OSX systems.

```
env PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 2.7.11
$ find .pyenv/ -name '*pip*'
.pyenv//plugins/pyenv-virtualenv/test/pip.bats
.pyenv//pyenv.d/exec/pip-rehash
.pyenv//pyenv.d/exec/pip-rehash/pip
.pyenv//pyenv.d/exec/pip-rehash.bash
.pyenv//versions/2.7.11/Python.framework/Versions/2.7/lib/python2.7/ensurepip
.pyenv//versions/2.7.11/Python.framework/Versions/2.7/lib/python2.7/ensurepip/_bundled/pip-7.1.2-py2.py3-none-any.whl
.pyenv//versions/2.7.11/Python.framework/Versions/2.7/lib/python2.7/pipes.py
.pyenv//versions/2.7.11/Python.framework/Versions/2.7/lib/python2.7/pipes.pyc
.pyenv//versions/2.7.11/Python.framework/Versions/2.7/lib/python2.7/pipes.pyo
.pyenv//versions/2.7.11/Python.framework/Versions/2.7/lib/python2.7/test/test_ensurepip.py
.pyenv//versions/2.7.11/Python.framework/Versions/2.7/lib/python2.7/test/test_ensurepip.pyc
.pyenv//versions/2.7.11/Python.framework/Versions/2.7/lib/python2.7/test/test_ensurepip.pyo
.pyenv//versions/2.7.11/Python.framework/Versions/2.7/lib/python2.7/test/test_pipes.py
.pyenv//versions/2.7.11/Python.framework/Versions/2.7/lib/python2.7/test/test_pipes.pyc
.pyenv//versions/2.7.11/Python.framework/Versions/2.7/lib/python2.7/test/test_pipes.pyo
```

When Installing without --enable-framework, pip is installed and available.

@nicktimko With the --enable-framework install I tried installing pip with get-pip.py, but got a permission denied error when the installer tried to write to /Library/Python/2.7/...

So python (rather site.py) adds /Library/Python/2.7/... to sys.path when compiled with --enable-framework

Did some more digging and found this post on stackoverflow: https://stackoverflow.com/questions/26471889/permanently-remove-something-from-python-sys-path

After removing the ^/Library directories from sys.path I was able to get through the get-pip.py script and found the pip binaries under ~/.pyenv/versions/2.7.11/Python.framework/Versions/2.7/bin (I think that was the dir)


Maybe that extra directory being added to sys.path is causing issues?  Let me know if you want any more information, or would like me to test anything.

**Comment by pcgilday** [comment]
> Strange, but you could try get-pip.py.

Yes I can, and have. I was more curious why the shim is not getting installed since the docs seem to indicate it would. 

@Brawnd0 I don't have `--enable-framework` option set. The solution you mentioned may very well fix my issue, but I would rather not mess with the system `site.py` main function since I am able to use pip at the moment. I use locally installed pip with the --user flag per some of the permission issues that are detailed here https://github.com/pypa/pip/issues/1668. 

I am fine not having pyenv shim for pip as I think my initial thoughts as to how it may solve my root problem were incorrect. However, since the docs say `pyenv maintains shims in that directory to match every Python command across every installed version of Python—python, pip, and so on.` I think that at minimum an error should be thrown if there is a reason pip or another shim cannot be installed. If this is something that is desired, I am happy to work on a PR, although it may be some time before I am able to get around to it.

**Comment by cuevee** [comment]
I **do** install with `--enable-framework` due to matplotlib requirements.

As @yyuu mentioned, `rehash` searches for binaries in `$(pyenv root)/versions/*/bin/*`, but skips binaries in `$(pyenv root)/versions/*/Python.framework/Versions/{version}/bin/*` when you install with `--enable-framework`. 

That seems to be because `list_executable_names` in [pyenv-rehash](https://github.com/yyuu/pyenv/blob/2017dd0c25467caffd6b9d6749f80dc502128842/libexec/pyenv-rehash#L87) lists binaries from `"${PYENV_ROOT}/versions/${version}/bin/"*`. Could we perhaps add something like `"${PYENV_ROOT}/versions/${version}/Python.framework/Version/*/bin/"*` to that search path?

Here's a clean `PYTHON_CONFIGURE_OPTS="--enable-framework CC=clang" pyenv install 2.7.12`:

`ls -al $(pyenv root)/shims`

```
-rwxr-xr-x   1 quintis  staff  419 Aug  1 09:44 2to3*
-rwxr-xr-x   1 quintis  staff  419 Aug  1 09:44 2to3-2*
-rwxr-xr-x   1 quintis  staff  419 Aug  1 09:44 2to3-2.7*
-rwxr-xr-x   1 quintis  staff  419 Aug  1 09:44 idle*
-rwxr-xr-x   1 quintis  staff  419 Aug  1 09:44 idle2*
-rwxr-xr-x   1 quintis  staff  419 Aug  1 09:44 idle2.7*
-rwxr-xr-x   1 quintis  staff  419 Aug  1 09:44 pydoc*
-rwxr-xr-x   1 quintis  staff  419 Aug  1 09:44 pydoc2*
-rwxr-xr-x   1 quintis  staff  419 Aug  1 09:44 pydoc2.7*
-rwxr-xr-x   1 quintis  staff  419 Aug  1 09:44 python*
-rwxr-xr-x   1 quintis  staff  419 Aug  1 09:44 python-config*
-rwxr-xr-x   1 quintis  staff  419 Aug  1 09:44 python2*
-rwxr-xr-x   1 quintis  staff  419 Aug  1 09:44 python2-config*
-rwxr-xr-x   1 quintis  staff  419 Aug  1 09:44 python2.7*
-rwxr-xr-x   1 quintis  staff  419 Aug  1 09:44 python2.7-config*
-rwxr-xr-x   1 quintis  staff  419 Aug  1 09:44 pythonw*
-rwxr-xr-x   1 quintis  staff  419 Aug  1 09:44 pythonw2*
-rwxr-xr-x   1 quintis  staff  419 Aug  1 09:44 pythonw2.7*
-rwxr-xr-x   1 quintis  staff  419 Aug  1 09:44 smtpd.py*
-rwxr-xr-x   1 quintis  staff  419 Aug  1 09:44 smtpd2.7.py*
-rwxr-xr-x   1 quintis  staff  419 Aug  1 09:44 smtpd2.py*
```

and `ls -al $(pyenv root)/versions/2.7.12/Python.framework/Versions/2.7/bin`

```
lrwxr-xr-x   1 quintis  staff      6 Aug  1 09:43 2to3@ -> 2to3-2
lrwxr-xr-x   1 quintis  staff      8 Aug  1 09:43 2to3-2@ -> 2to3-2.7
-rwxr-xr-x   1 quintis  staff    158 Aug  1 09:43 2to3-2.7*
-rwxr-xr-x   1 quintis  staff    327 Aug  1 09:43 easy_install*
-rwxr-xr-x   1 quintis  staff    327 Aug  1 09:43 easy_install-2.7*
lrwxr-xr-x   1 quintis  staff      5 Aug  1 09:43 idle@ -> idle2
lrwxr-xr-x   1 quintis  staff      7 Aug  1 09:43 idle2@ -> idle2.7
-rwxr-xr-x   1 quintis  staff    156 Aug  1 09:43 idle2.7*
-rwxr-xr-x   1 quintis  staff    299 Aug  1 09:44 pip*
-rwxr-xr-x   1 quintis  staff    299 Aug  1 09:44 pip2*
-rwxr-xr-x   1 quintis  staff    299 Aug  1 09:44 pip2.7*
lrwxr-xr-x   1 quintis  staff      6 Aug  1 09:43 pydoc@ -> pydoc2
lrwxr-xr-x   1 quintis  staff      8 Aug  1 09:43 pydoc2@ -> pydoc2.7
-rwxr-xr-x   1 quintis  staff    141 Aug  1 09:43 pydoc2.7*
lrwxr-xr-x   1 quintis  staff      7 Aug  1 09:43 python@ -> python2
lrwxr-xr-x   1 quintis  staff     14 Aug  1 09:43 python-config@ -> python2-config
lrwxr-xr-x   1 quintis  staff      9 Aug  1 09:43 python2@ -> python2.7
lrwxr-xr-x   1 quintis  staff     16 Aug  1 09:43 python2-config@ -> python2.7-config
-rwxr-xr-x   1 quintis  staff   9220 Aug  1 09:43 python2.7*
-rwxr-xr-x   1 quintis  staff   1744 Aug  1 09:43 python2.7-config*
lrwxr-xr-x   1 quintis  staff      8 Aug  1 09:43 pythonw@ -> pythonw2
lrwxr-xr-x   1 quintis  staff     10 Aug  1 09:43 pythonw2@ -> pythonw2.7
-rwxr-xr-x   1 quintis  staff   9220 Aug  1 09:43 pythonw2.7*
lrwxr-xr-x   1 quintis  staff      9 Aug  1 09:43 smtpd.py@ -> smtpd2.py
-rwxr-xr-x   1 quintis  staff  18604 Aug  1 09:43 smtpd2.7.py*
lrwxr-xr-x   1 quintis  staff     11 Aug  1 09:43 smtpd2.py@ -> smtpd2.7.py
```

**Comment by ojss** [comment]
I am facing the same problem, when I build with --enable-framework, the shims aren't updated to point to the pip installation.

**Comment by cuevee** [comment]
`pip` is fine for me, but something like `ipython` gets skipped for me when shims get created. It does this with all `2.x` and `3.x` versions I've tried.

**Comment by mtraynham** [comment]
Also seeing this as well, `--enable-framework` seems to skip all the shims.  I installed 3.5.1 with `--enable-frameowkr` a few months ago and the structure of the directory is quite a bit different.  I wonder what has changed.

**Comment by yyuu** [comment]
I confirmed that at least CPython 3.5.2 on OS X 10.11.6 creates `./bin` directory as normal directory instead of symlink to framework installation path. I pushed bc8dba4beabfa680b5ecc82b4bec3fa51f489c08 as a workaround for it. I'm still not sure what breaks the framework installation, though. Anyway please give it a try.

**Comment by ojss** [comment]
I shall give it a try as soon as I get the chance to.
Thank you.

**Comment by cuevee** [comment]
Tried the workaround for both `2.7.12` and `3.5.2` and both work fine. Thanks @yyuu!

**Comment by ojss** [comment]
Yup it's working. Thank you so much.
