### ISSUE TITLE
add pypy 5.1.1

### ISSUE THREAD

**Issue by jab** [yyuu/pyenv#591]
Release announced 5 days ago:
http://morepypy.blogspot.com/2016/05/pypy-511-bugfix-released.html

**Comment by Samureus** [comment]
Grateful if someone can check my PR for Portable PyPy 5.1.1 (still messing with this Git thing):

https://github.com/yyuu/pyenv/pull/592

**Comment by Samureus** [comment]
And added PyPy-5.1.1-src in a separate PR

https://github.com/yyuu/pyenv/pull/593

Should I delete the previous PR?
