### ISSUE TITLE
Bash environment variable setting of 'HOME' returns "pyenv: no such command `sh-activate'"

### ISSUE THREAD

**Issue by qwertyjune** [yyuu/pyenv#596]
Dear Yamashita,

Thank you very much for your great effort toward this amazing application.

I would like to ask you about a bash environment variable setting.

I have been running a bash script to run multiple dropbox account on my Ubuntu system. (reference link: http://askubuntu.com/a/475420 )

1. After I set up pyenv and autoenv, I found out a command in my bash script return a error message as below.
command)  HOME="$HOME/.dropbox-alt"
returns)      pyenv: no such command `sh-activate'

2. The environment variable above seems work well.
when I run a command, echo $HOME, it returns as below.
command) echo $HOME
returns) 
/home/myname/.dropbox-alt
pyenv: no such command `sh-activate'

3. And this error message comes along with all bash commands such as,
commandexport, ls, cd, mkdir, ...

Here is my ~/.bashrc ends with,

```shell
# Load pyenv automatically by adding
# the following to ~/.bash_profile:

export PATH="/home/june/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
source ~/.autoenv/activate.sh
```

I am wondering what makes this error message and am wondering whether if this error affect any of my system.
Thank you very much.

Kind regards,
June.

**Comment by joshfriend** [comment]
This is not related to pyenv. The `sh-activate` command is part of the [pyenv-virtualenv](https://github.com/yyuu/pyenv-virtualenv) plugin. Read the setup instructions for the plugin and verify that you have installed it correctly. If you continue to have issues, raise an issue on pyenv-virtualenv.
