### ISSUE TITLE
pyenv install anaconda - curl issue

### ISSUE THREAD

**Issue by landge** [yyuu/pyenv#599]
Hi,
I'm trying to install anaconda through pyenv (system 2.7.9) with 
$> pyenv install anaconda3-4.0.0
which gives me a curl certificate error (60).  When I try to download anaconda directly from
the command line with curl (/usr/bin/curl) I can download everything without problem. 
"pyenv which curl" points to my system curl!
I do not really understand what's going on here!
(I'm on debian 8.4)

Thanks in advance!!! #

**Comment by yyuu** [comment]
Basically pyenv should choose system's `curl` even if there's anaconda's `curl`. I'm not sure what's going on the machine. Though I believe #595 should solve the issue eventually.

**Comment by landge** [comment]
This [#597 ](https://github.com/yyuu/pyenv/issues/597) workaround solved it, of course. Can't figure out
what's wrong with my setup.

**Comment by yyuu** [comment]
#595 should solve this.
