### ISSUE TITLE
Homebrew instructions for enabling shims are NOT always correct

### ISSUE THREAD

**Issue by twn346** [yyuu/pyenv#611]
The output (and cause of much headache) of doing a `brew info pyenv`, and similarly advised on an `brew install pyenv` is: 

    To enable shims and autocompletion add to your profile:
    if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

This is not correct with, for example, fish. I found the closed issue that discusses this at length and finally figured out what I *should* add by following the instructions there and running `pyenv init` which does have the correct instructions. 

Just thought i'd point out that the homebrew installation can cause headaches if you don't know to run pyenv init without the `-` and don't realize that you can't just "fishify" the suggested command.

**Comment by yyuu** [comment]
brew's formula is a part of brew. Send PR to fix it by yourself
