### ISSUE TITLE
install scrapy and cronjob not work

### ISSUE THREAD

**Issue by fonewoda** [yyuu/pyenv#612]
install scrapy with pyenv

work great in normal

but not work in cronjob

cd folder && scrapy crawl spider_name >> some_log

it seem be executed but log is empty

**Comment by yyuu** [comment]
It just means you're configuring pyenv into shell's configuration file for interactive shell (e.g. .zshrc for zsh). Move it to configuration to somewhere for all shells (e.g. .zshenv), or prepending `source ~/.bashrc` before the command line of cron script, or prepending initialization code of pyenv in your cron script, every method should work.

This kind of things isn't pyenv issue anyways. Read your shell's manuals.

**Comment by fonewoda** [comment]
*/3 * * * * source ~/.bashrc && cd /home/scrapy_folder && scrapy crawl scrapy_spider

I am sorry,it doesnt work,help please~

**Comment by fonewoda** [comment]
@yyuu any solution?thanks!
