### ISSUE TITLE
Can't change python version by pyenv local "version_number"

### ISSUE THREAD

**Issue by b5y** [yyuu/pyenv#616]
This problem occurs in Mac OS X Yosemite (10.10.5). On Linux (Debian) everything is fine.

Here is screenshot of problem:

![screen shot 2016-05-30 at 2 07 22](https://cloud.githubusercontent.com/assets/1110987/15636561/d859f9ba-260b-11e6-9539-8627b306c01a.png)

**Comment by nicktimko** [comment]
If you say `which python`, does it report the shim (`/Users/____/.pyenv/shims/python`) or your system Python (`/usr/local/bin/python`)? 

If you see the latter, it's probably a `PATH` issue (`echo $PATH`) where `/usr/local/bin` is before `.../.pyenv/shims`.

**Comment by c17r** [comment]
Also, are you inside a virtualenv? That seems to take priority over everything.

**Comment by kerstin** [comment]
Echoing what @c17r said.

Try `$ pyenv deactivate` and see what pyenv tells you.

If you had a virtualenv activated, pyenv will spit out its name/path, if not, it'll print out:
`pyenv-virtualenv: no virtualenv has been activated.`
