### ISSUE TITLE
pypy 5.3 is released

### ISSUE THREAD

**Issue by alex** [yyuu/pyenv#626]
http://morepypy.blogspot.com/2016/06/pypy2-v53-released-major-c-extension.html

**Comment by joshfriend** [comment]
Its interesting that the post you linked does not list PPC arch as being supported by this release, but they have download links (which 404) and checksums for those on the downloads page.

**Comment by joshfriend** [comment]
Still working on how to support the new s390x architecture. I think I have most of it figured out, but `/etc/issue` on RHEL 7 just contains garbage:

```
\S
Kernel \r on an \m
```

Actual release info is in `/etc/redhat-release`:

```
Red Hat Enterprise Linux Server release 7.2 (Maipo)
```

**Comment by yyuu** [comment]
Isn't there any s390x user...? 😜   Please help us~

**Comment by joshfriend** [comment]
Here's what I had found:

https://twitter.com/mattgillard/status/481387591099375616

```
zlinux proc]$ uname -a
Linux zlinux 2.6.18-371.el5 #1 SMP Thu Sep 5 21:23:53 EDT 2013 s390x s390x s390x GNU/Linux
```

so, you can probably just check if `uname -m` is `s390x`...
