### ISSUE TITLE
pyenv global system does not work when Python is located under /bin

### ISSUE THREAD

**Issue by Rompei** [yyuu/pyenv#628]
In my environment, Python is installed under `/bin` not `/usr/bin`.  I typed `pyenv global system` or `pyenv prefix system`, it shows this message.

```
pyenv prefix system
pyenv: version `system' not installed
pyenv global system
pyenv: version `system' not installed
```

```
pyenv which python
/bin/python
```

It work when python is located `/usr/bin`

```
pyenv which python
/usr/bin/python
```

Could you deal with this?

**Comment by yyuu** [comment]
This is a kind of bug of both pyenv and rbenv. It's expecting `system` version is located inside `bin` directory of non-toplevel.

https://github.com/yyuu/pyenv/blob/8781d132e71b9fc53f2bea34ed3805b14f6a01cc/libexec/pyenv-prefix#L34
