### ISSUE TITLE
Pyenv install python failed, C compiled programs error.

### ISSUE THREAD

**Issue by MagisDing** [yyuu/pyenv#629]
> pyenv install 3.5.1
Downloading Python-3.5.1.tgz...
-> https://www.python.org/ftp/python/3.5.1/Python-3.5.1.tgz
Installing Python-3.5.1...

> BUILD FAILED (OS X 10.11.5 using python-build 20160130)

>Inspect or clean up the working tree at /var/folders/pp/76z_j1x56xn2t3g08k0jrvm80000gn/T/python-build.20160614001439.91808
Results logged to /var/folders/pp/76z_j1x56xn2t3g08k0jrvm80000gn/T/python-build.20160614001439.91808.log

>Last 10 log lines:
checking for --without-gcc... no
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/var/folders/pp/76z_j1x56xn2t3g08k0jrvm80000gn/T/python-build.20160614001439.91808/Python-3.5.1':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
make: *** No targets specified and no makefile found.  Stop.

I have installed gcc with x-code command line

> gcc -v
 Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin` 

and I have already installed gcc & readline via Homebrew. I tried `cc=clang(or gcc-6) pyenv install 3.5.1(or 2.7.11)`, got the same error, really need help here. Thanks.

**Comment by yyuu** [comment]
Obviously no pyenv error. Try building CPython and check config.log

**Comment by Yangzhilang** [comment]
but still not solved.
