### ISSUE TITLE
pyenv-which running once a minute, causing high CPU usage

### ISSUE THREAD

**Issue by iros** [yyuu/pyenv#632]
I'm not quite sure why this is happening, but about once a minute the following command will run:

`<pid> <user> bash /usr/local/Cellar/pyenv/20151124/libexec/pyenv-which python3`

This will result in a bash process that takes over 90% of my CPU. 
Any advice on what might be causing this or spawning it?

Thanks,

**Comment by yyuu** [comment]
`pyenv rehash` will be run implicitly after either `pyenv-init`, `pip (install|uninstall)`, `easy_install` or `conda (install|remove|uninstall)`. There must be something invoke it in your configuration.

https://github.com/yyuu/pyenv/blob/v20160509/libexec/pyenv-init#L107
https://github.com/yyuu/pyenv/blob/v20160509/pyenv.d/exec/pip-rehash/pip#L25
https://github.com/yyuu/pyenv/blob/v20160509/pyenv.d/exec/pip-rehash/easy_install#L24
https://github.com/yyuu/pyenv/blob/v20160509/pyenv.d/exec/pip-rehash/conda#L25
