### ISSUE TITLE
Simple questions about  design philosophy of pyenv and pyenv-virtualenv

### ISSUE THREAD

**Issue by NoraGithub** [yyuu/pyenv#636]
I am confusing some issues that don't illustrate in the github.
Background described : 
Default Python-->Canopy-->pyenv (by Homebrew)-->pyenv-virtual(by Homebrew)-->anaconda-1.9.2(by pyenv)-->anaconda3-4.0.0(by pyenv)-->test(of anaconda3-4.0.0 by pyenv-virtualenv)
(More details will be given in the specific case)

# pyenv-virtual to manage Canopy Default and Canopy virtualenv
1. I have modified `~./bash_profile` as the instructions told me, and now my default python is  Canopy. 
However, if I used pyenv-virtual to copy it as a virtualenv, it would always come with failure.
As I google the solution, I want to make sure if pyenv-virtual is not compatible with canopy as described [here](https://support.enthought.com/hc/en-us/articles/204469120-Use-venv-not-virtualenv-with-Canopy-Python)
`pyenv --debug` info [attached](https://gist.githubusercontent.com/NoraGithub/3c78b03185c70f6dd8bf3aa551e3cef7/raw/ed3287b17741cf5f7c734a2e7c90cda89c2facde/pyenv-virtual%2520to%2520manage%2520Canopy%2520Default%2520and%2520Canopy%2520virtualenv)

2. It's a pity that I could not find Canopy by `pyenv install -l`, and I will appreciate if you could please tell me how to use pyenv to manage Canopy version python, switching between system dault(/usr/bin/python) and Canopy, in the case that it really could.

# Anaconda-1.9.2 :too old to fix and untested&unspecified
Anaconda-1.9.2 is my target version and while using pyenv-virtual, I also encouter weird [issue](https://github.com/conda/conda/issues/2768), which I had asked conda for help.
I wonder if you could help me with it.
`pyenv --debug` info [attached](https://gist.githubusercontent.com/NoraGithub/3f5aefdc6874cd6e0ec5529ca70deb05/raw/412b377abc00fc09c17a91a0c0afff47d6db077c/Anaconda-1.9.2%2520:too%2520old%2520to%2520fix%2520and%2520untested&unspecified)

# Unauthorized to pyenv-virtualenv system default python(`/usr/bin/python`)
For testing whether pyenv-virtualenv worked, I deactivated Canopy by commenting in `~/.bash_profile`:
>#The next line updates PATH for the Google Cloud SDK.
>source '/Users/NoraChan/Downloads/google-cloud-sdk/path.bash.inc'
>
>#The next line enables bash completion for gcloud.
>source '/Users/NoraChan/Downloads/google-cloud-sdk/completion.bash.inc'
>
>#Added by Canopy installer on 2016-02-15
>#VIRTUAL_ENV_DISABLE_PROMPT can be set to '' to make the bash prompt show that Canopy is active, otherwise 1
>alias activate_canopy="source '/Users/NoraChan/Library/Enthought/Canopy_64bit/User/bin/activate'"
>VIRTUAL_ENV_DISABLE_PROMPT=1 source '/Users/NoraChan/Library/Enthought/Canopy_64bit/User/bin/activate'
>
>#node.js management by Nora
>source /usr/local/opt/nvm/nvm.sh
>nvm use --delete-prefix nvm ls node
>
>#pyenv demand
>if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
>
>#pyenv-virtualenv demand
>if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi

As a result, I had reseted `/usr/bin/python` as system default, and then here come new problems that I don't get the permission from system to install site-package.
`pyenv --debug` info [attached](https://gist.githubusercontent.com/NoraGithub/187b3dec88191a24fb50dc32ab0730f6/raw/18ea7d713d58e08528cba05e1163be4fbff35973/Unauthorized%2520to%2520pyenv-virtualenv%2520system%2520default%2520python(usr_bin_python))

# Multiplied results by one command
At the end, I pyenv-installed try `pyenv anaconda3-4.0.0` and then `pyenv virtualenv anaconda3-4.0.0 test`  to test pyenv-virtual and I found that the single command:
>pyenv virtualenv anaconda3-4.0.0 test

would make two versions(by `pyenv versions`) 
>Noras-MacBook-Air:sbin NoraChan$ pyenv versions
>\* system (set by /Users/NoraChan/.pyenv/version)
>  anaconda-1.9.2
>  anaconda3-4.0.0
>  anaconda3-4.0.0/envs/test
>  test

and two virtualenvs(`pyenv virtualenv`).
>Noras-MacBook-Air:/ NoraChan$ pyenv virtualenvs
>  anaconda-1.9.2 (created from /Users/NoraChan/.pyenv/versions/anaconda-1.9.2)
>  anaconda3-4.0.0 (created from /Users/NoraChan/.pyenv/versions/anaconda3-4.0.0)
>  anaconda3-4.0.0/envs/test (created from /Users/NoraChan/.pyenv/versions/anaconda3-4.0.0/envs/test)
>  test (created from /Users/NoraChan/.pyenv/versions/test)

1. Would there be any imcompatable issue between both installation of pyenv and pyenv-virtualenv from Homebrew which make the phenomenon above or would it be a correct output as it's designed like this.
2. What's the difference between versions and virtualenvs if they mean the same thing. And if they were the same, What may happen if I develop something in one of them and then mis-change to others to continued.(When I construct many virtualenvs, it could happen surely)

**Comment by yyuu** [comment]
Title's liying. Firstly you should consider what simple is. Don't mix up multiple things.

**Comment by NoraGithub** [comment]
Do you mean that I should ask a single question at a single time and as it's complex, I should not use this title?  @yyuu 
If yes, I apology about that and I will issue several more issues for that.
Looking forward to your reply.:)
