### ISSUE TITLE
Shims not removing correctly with develop

### ISSUE THREAD

**Issue by foxx** [yyuu/pyenv#637]
It would seem that scripts which are installed via `develop` do not have their shims removed correctly, even if using `rehash` manually.

```
$ python setup.py develop --uninstall

$ pyenv rehash && hash -rl

$ ls -lah ~/.pyenv/shims/
-rwxrwxr-x  1 vagrant vagrant  406 Jun 23 11:52 probe-dispatcher
-rwxrwxr-x  1 vagrant vagrant  406 Jun 23 11:50 probe-dispatcher.py
```

However this behaviour does not happen when using `install`, as such;

```
$ pip install bottle.py

$ ls -lah ~/.pyenv/shims/bottle.py
-rwxrwxr-x  1 vagrant vagrant  406 Jun 23 11:55 bottle.py

$ pip uninstall bottle
Uninstalling bottle-0.12.9:
  /home/vagrant/.pyenv/versions/3.4.4/bin/bottle.py

$ ls -lah ~/.pyenv/shims/bottle.py
ls: cannot access /home/vagrant/.pyenv/shims/bottle.py: No such file or directory
```

**Comment by yyuu** [comment]
#524

**Comment by foxx** [comment]
@yyuu This isn't a duplicate of #524, or doesn't appear to be. In #524, I was able to fix the problem by manually invoking `rehash`, but in this instance `rehash` doesn't appear to be removing the script when using `develop`.

Are you saying that `develop` is outright not supported with `pyenv`? If not, why?

**Comment by yyuu** [comment]
I don't need it. If you need something do it by yourself. PRs are welcome.
