### ISSUE TITLE
Failed to download different python version.

### ISSUE THREAD

**Issue by chinmaydas96** [yyuu/pyenv#641]
~  pyenv install 3.5.0
Downloading Python-3.5.0.tgz...
-> https://www.python.org/ftp/python/3.5.0/Python-3.5.0.tgz
error: failed to download Python-3.5.0.tar.gz

BUILD FAILED (Ubuntu 15.10 using python-build 20160509-42-g3d263c8)

**Comment by thomasjo** [comment]
Did you try downloading from that location using e.g. wget or curl?

``` bash
wget https://www.python.org/ftp/python/3.5.0/Python-3.5.0.tgz
```

Works fine here, so I'm guessing you're behind a proxy or some such which is preventing the download.

**Comment by yyuu** [comment]
It's working at least for me and others. Possibly networking issue.

**Comment by JamesXNelson** [comment]
Any way to add retries / longer timeouts to the curl/wget commands?  It would be nice to try at least 5-10 times before breaking builds over a network failure.
