### ISSUE TITLE
Erroneous shim created

### ISSUE THREAD

**Issue by brbsix** [yyuu/pyenv#656]
To recreate the error:

    pyenv virtualenv zzz
    touch ~/.pyenv/versions/zzz/bin/zzz
    pyenv rehash

Now check the last few shims:

    find ~/.pyenv/shims/ -type f -printf '%P\n' | LC_ALL=C sort -u | tail

Note the file *zzz* is nowhere to be found but there's a new shim named *zzzactivate*.

**Comment by nicktimko** [comment]
Works for me, though I also get a strange `zzz__pycache__` shim... I wonder if the last shim name (in some sort order) is somehow concatenated with the first shim name?

**Comment by yyuu** [comment]
It's because `pyenv-rehash` doesn't care if the files found in `PATH` is an executable file or not. It must be a user's responsibility to keep PATH clean.

https://github.com/yyuu/pyenv/blob/v20160726/libexec/pyenv-rehash#L87-L89

**Comment by nicktimko** [comment]
The `zzz__pycache__` doesn't seem to exist anywhere though. It's not that the shim is referring to a bad (non-executable, yadda, yadda) file, it's that it's created in response to (apparently) nothing.
