### ISSUE TITLE
Quick Installation Help

### ISSUE THREAD

**Issue by scroungemyvibe** [yyuu/pyenv#659]
##Dear dev's, 

When I restarted git bash as advised in the installation readme, the following is returned as the first line:
`/c/Users/GunnyLiu/.pyenv/bin/pyenv: line 1: ../libexec/pyenv: No such file or directory`

What is going on?

-gunny

**Comment by joshfriend** [comment]
https://github.com/yyuu/pyenv/issues/332#issuecomment-81199008
