### ISSUE TITLE
pyenv finding command in wrong env

### ISSUE THREAD

**Issue by jmccormac01** [yyuu/pyenv#664]
Hi, I have several versions of python installed with pyenv. I recently installed astroconda in an anaconda env and I've been having some trouble (e.g. see #662). Today I have another issue. When I run miniconda3-latest (my default env) and I try running DS9 (via pyds9) I get a strange error where pyenv finds ds9 in the astroconda env and therefore won't run it from my miniconda3 env. If i delete the astroconda env the code below works fine. 

<img width="530" alt="screenshot 2016-07-25 09 30 08" src="https://cloud.githubusercontent.com/assets/1912007/17095132/e7c4527c-524a-11e6-839b-92d2cf0f8801.png">

<img width="528" alt="screenshot 2016-07-25 09 29 51" src="https://cloud.githubusercontent.com/assets/1912007/17095139/ec500688-524a-11e6-95bb-d9c35d6a2709.png">

**Comment by nicktimko** [comment]
This seems like some strange interaction between pyenv and pyds9. Presumably `ds9` is some Python binary/script that's installed in a Python environment, then it's [called via `subprocess` in the `pyds9` package](https://github.com/ericmandel/pyds9/commit/b96d76eeba162683852abb1aa956f6e275d9e793#L441). Strange architecture...

Does `pyenv which ds9` say it's available in the `miniconda3-latest` env? If so, can you indeed run `ds9` from the command line in that env?

**Comment by yyuu** [comment]
There's nothing weird. You're using `miniconda3-latest` and the `ds9` command isn't available in the version. Please read the error message.

```
pyenv: ds9: command not found

The `ds9' command exists in these Python versions:
  anaconda-4.0.0/envs/astroconda
```
