### ISSUE TITLE
pyenv init must necessarily added in shell?

### ISSUE THREAD

**Issue by gatspy** [yyuu/pyenv#666]
add this in shell config file , shell starup slowly?
may i manually add shim path into $PATH ?
i test rbenv init on the start-up speed can be ignored.

**Comment by yyuu** [comment]
Generally speaking, pyenv can work even without calling `pyenv-init`. Some features (e.g. shell completion, `sh-*` commands) will not work though.

For many cases, the slowness of init could be coming from rehashing shim scripts. Calling as `eval "$(pyenv init - --no-rehash)"` could mitigate the slowness during the bootstrap. (this can be applied to rbenv too)

**Comment by gatspy** [comment]
tks, I understand, in my zshrc file , used pyenv and rbenv,excluded nvm, it is too slow.
