### ISSUE TITLE
Package bin script not installing into correct directory

### ISSUE THREAD

**Issue by jo-sm** [yyuu/pyenv#667]
I built a tool and added it to the `setup.py` `scripts` key, e.g.:

```
setup(
  scripts=['my_script.py']
)
```

I noticed it put the bin script into `/Users/josh/.pyenv/versions/3.5.2/Python.framework/Versions/3.5/bin`, which isn't in my `$PATH` by default rather than the `/Users/josh/.pyenv/shims` directory. 

Is there any way to make sure that the installation gets placed into the `shims` directory? `pyenv rehash` doesn't seem to fix it.

It also doesn't matter if it's in the `scripts` key or the `entry_points.console_scripts` key:

```
setup(
  entry_points={
    'console_scripts': ['my_script.py=my_script:main']
  }
)
```

**Comment by nicktimko** [comment]
Try doing `pyenv rehash`, that creates the shims from what it finds in all of the versions' `bin/` directories.

pyenv doesn't monkey around with `PATH` envvar to switch between `bin` directories when switching between versions, but instead uses a combination of the "current version" (`pyenv version`) and those shims (cookie-cutter scripts that do an `exec` to pass off to the desired executable).

**Comment by jo-sm** [comment]
Ah sorry, I meant `pyenv rehash` in my original post. Not `pyenv shims`,

**Comment by nicktimko** [comment]
Is the script executable in the directory?

Is the shim created and it pyenv complains that it just can't find it in
the current environment?

**Comment by jo-sm** [comment]
Yeah, it's executable but doesn't make a difference. 

The shim doesn't seem to be created. I run `pyenv rehash && hash -r`, and it still doesn't exist in the `shims` directory.

**Comment by jo-sm** [comment]
It was actually an issue with pip -- I had installed a different version, so it wasn't installing in the correct directory. Thanks for the help!
