### ISSUE TITLE
pyenv install 2.7.8   command failed

### ISSUE THREAD

**Issue by slankipalli** [yyuu/pyenv#677]
Downloading Python-2.7.8.tar.xz...
-> https://www.python.org/ftp/python/2.7.8/Python-2.7.8.tar.xz
Installing Python-2.7.8...
/home/core/.pyenv/plugins/python-build/bin/python-build: line 1464: patch: command not found

BUILD FAILED (CoreOS 766.5.0 using python-build 20160602)

Inspect or clean up the working tree at /tmp/python-build.20160818195434.7155
Results logged to /tmp/python-build.20160818195434.7155.log

Last 10 log lines:
/tmp/python-build.20160818195434.7155 ~
/tmp/python-build.20160818195434.7155/Python-2.7.8 /tmp/python-build.20160818195434.7155

**Comment by joshfriend** [comment]
> patch: command not found

Thats the key. You need to have `patch` installed and available somewhere in `$PATH`

**Comment by slankipalli** [comment]
Patch mean, can you please more details around.

Thanks

**Comment by yyuu** [comment]
patch is a command to apply some changes to files from input; typically which is provided as a package named "patch" by Linux distributions. It is a requirement of pyenv.

**Comment by slankipalli** [comment]
I want install pyenv on CoreOS that's where problem raised

**Comment by zzr0427** [comment]
I met the same problem in Centos7.2. I solved the problem by install a package called `patch`:
yum install patch

**Comment by blimbu1** [comment]
installing patch worked for me. Many thanks.

**Comment by Kogoon** [comment]
Installing `patch` on `centos7` worked for me too. Thanks

**Comment by native-api** [comment]
> Is it possible to add this to the [Common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems) page? I struggled for at least 30 min sweat

Added to https://github.com/pyenv/pyenv/wiki#suggested-build-environment
