### ISSUE TITLE
pyenv downloads things off http (not https!!!) sites

### ISSUE THREAD

**Issue by hawkowl** [yyuu/pyenv#679]
This is bad for security :(

**Comment by hawkowl** [comment]
There does seem to be a hash associated with it, now that I've dug into the files, although it doesn't communicate that to the user (it just gives a HTTP URL, which is why I filed this bug!). Even if it does check the hash (which I'm trusting pyenv does without...) it should probably download it off HTTPS anyway (because then it doesn't give people heart attacks ;) ).

**Comment by yyuu** [comment]
#680 has been merged.
