### ISSUE TITLE
not works with http_proxy (CURL version too old,modify the code and use wget instead)

### ISSUE THREAD

**Issue by wilsonliu0806** [yyuu/pyenv#682]
**1 first i start pyenv install 3.0.1 failed as followings:**

```
$ pyenv install 3.0.1
Downloading Python-3.0.1.tgz...
-> https://www.python.org/ftp/python/3.0.1/Python-3.0.1.tgz
error: failed to download Python-3.0.1.tar.gz

BUILD FAILED (CentOS 5.8 using python-build 20160602)
```

**2 http_proxy has set and works well with wget**

```
$ env | grep http
http_proxy=http://127.0.0.1:8118
ftp_proxy=http://127.0.0.1:8118
https_proxy=http://127.0.0.1:8118

$ wget https://www.python.org/ftp/python/3.0.1/Python-3.0.1.tgz
--2016-08-30 10:14:16--  https://www.python.org/ftp/python/3.0.1/Python-3.0.1.tgz
Connecting to 127.0.0.1:8118... connected.
Proxy request sent, awaiting response... 200 OK
Length: 11258272 (11M) [application/octet-stream]
Saving to: `Python-3.0.1.tgz'

100%[==================================================================================================================================================================================================>] 11,258,272  4.02M/s   in 2.7s    

2016-08-30 10:14:20 (4.02 MB/s) - `Python-3.0.1.tgz' saved [11258272/11258272]`
```

**i wonder what the problems could be?**

**does pyenv need extra config file?**

this situation a little bit like issue #303 ,but uninstall curl or set PYTHON_BUILD_MIRROR_URL doesnt work for me

    # curl -V
    curl 7.15.5 (x86_64-redhat-linux-gnu) libcurl/7.15.5 OpenSSL/0.9.8b zlib/1.2.3 libidn/0.6.5
    Protocols: tftp ftp telnet dict ldap http file https ftps 
    Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz

     # wget -V
    GNU Wget 1.11.4 Red Hat modified

and the error log is

    # more python-build.20160830170012.16234.log
    /tmp/python-build.20160830170012.16234 ~
     curl: (35) error:0D0C50A1:asn1 encoding routines:ASN1_item_verify:unknown message digest   algorithm

**OK I solved this problem by modify python-build code ,swtich curl and wget sequence. use wget instead of curl.My Problems seems curl version too old .**

**Comment by ldocao** [comment]
Hi @wilsonliu0806 can you say how did you modify the python-build code ? I have located the code here $HOME/.pyenv/plugins/python-build/share/python-build but I can't see where you can switch wget and curl ? There are plenty of files for each version, but I can't see any curl command

**Comment by yidaotong** [comment]
I guess it's here 
339 detect_http_client() {
 340   local client
 341   for client in aria2c **wget curl;** do
 342     if type "$client" &>/dev/null; then
 343       echo "$client"
 344       return
 345     fi
