### ISSUE TITLE
Python installation stuck on "Installing pip ..."

### ISSUE THREAD

**Issue by parthgala** [yyuu/pyenv#690]
I am trying to install Python 3.3.5 using pyenv.

The installation log shows the following so far:

Downloading Python-3.3.5.tgz...
-> https://www.python.org/ftp/python/3.3.5/Python-3.3.5.tgz
Installing Python-3.3.5...
patching file ./Lib/ssl.py
patching file ./Modules/_ssl.c
Installing pip from https://bootstrap.pypa.io/get-pip.py...

The installation is stuck on the last step (for over an hour).

Is this an issue with pyenv/pip or am I doing something wrong here? Did something change recently?

Thank you very much in advance !

**Comment by yyuu** [comment]
As you can see, it's just an ordinary call of `ensurepip`. It it stuck in your environment, there might be something bad in your network environment or https://bootstrap.pypa.io/

https://github.com/yyuu/pyenv/blob/6601c3440867778ee03b95700984a9123be2527e/plugins/python-build/bin/python-build#L1689

**Comment by parthgala** [comment]
Okay, I am not sure what is wrong with my machine but it works on another machine so closing this one.

Thanks !
