### ISSUE TITLE
pyenv: no such command `shell'

### ISSUE THREAD

**Issue by lwm** [yyuu/pyenv#708]
```
λ  ~  pyenv --version
pyenv 1.0.0-47-g5be82cb
λ  ~  pyenv shell
pyenv: no such command `shell'
λ  ~  eval "$(pyenv init -)"
λ  ~  pyenv shell 3.5.0
λ  ~  # win
```

I know you mention in the setup, that the necessary `pyenv init -` step however, perhaps the error message of `no such command ...` could be improved to say `did you forget to run 'init'`? I'd submit a PR if you think it's a good idea.

**Comment by yyuu** [comment]
It means that your shell isn't initialized with `eval "$(pyenv init -)"`. Please review your shell configurations again.

https://github.com/yyuu/pyenv#basic-github-checkout

**Comment by lwm** [comment]
What I wanted to address with this issue is that the we should create a better error message for people that forget to `eval "$(pyenv init -)"`. It's a little strange to have a missing command oh a CLI tool just because of that. No?

**Comment by julianharty** [comment]
I agree it'd be helpful for  `pyenv shell` to provide some advice on what to do in order to enable the command to work correctly.
