### ISSUE TITLE
BUILD FAILED (CentOS 4.3 using python-build 1.0.2-7)

### ISSUE THREAD

**Issue by haroldrandom** [yyuu/pyenv#719]
Hi, I got those output after typing command `pyenv install 3.5.2`.
However, later I try `pyenv install 2.7.12`, it does the similary things.

```
~/.pyenv/plugins/python-build/bin/python-build: line 277: printf: -v: invalid option
printf: usage: printf format [arguments]
~/.pyenv/plugins/python-build/bin/python-build: line 279: return: : numeric argument required
basename: too few arguments

Downloading ...

BUILD FAILED (CentOS 4.3 using python-build 1.0.2-7)
```

What should I do to fix this?
THX~
##

**Comment by ansvver** [comment]
I got the same issue too.
`
[dummy@cp01-wangjianhui-dev.epc.baidu.com ~]$ pyenv install 3.5.2
/home/dummy/.pyenv/plugins/python-build/bin/python-build: line 277: printf: -v: invalid option
printf: usage: printf format [arguments]
/home/dummy/.pyenv/plugins/python-build/bin/python-build: line 279: return: : numeric argument required
basename: too few arguments
Try 'basename --help' for more information.
Downloading ...

BUILD FAILED (CentOS 4.3 using python-build 1.0.2-48-g41606c4)
`

Anyone has hint?

**Comment by johnseekins** [comment]
basename on EL4 hosts doesn't work the same way as it does on EL5+. I don't know that this is fixable.

**Comment by haroldrandom** [comment]
@johnseekins What does EL4 and EL5 mean? What do they stand for?

**Comment by johnseekins** [comment]
EL -> Enterprise Linux.

That is, any Linux based on RHEL (like CentOS).

As a separate note, CentOS 4 has been EOL (end of life) for years now. It _might_ be time to consider upgrading.

**Comment by haroldrandom** [comment]
@johnseekins you are right, my OS is based on CentOS 4 and it's hard to update the OS version because of company restriction, so I'm here for help.

Maybe it's not worth to solve this problem whether it takes quiet a lot of work or not, I think.

**Comment by johnseekins** [comment]
I ran into this challenge before my company finally decommed all their EL4 hosts. basename _exists_ as a function in EL4, but does something significantly different. Given how much basename's current (EL5+) functionality plays a role in how pyenv works, you probably won't be able to get this fixed.

If you just need python 3.5.2, have you tried just installing it on your system with:
```
./configure
make
make altinstall
```

**Comment by haroldrandom** [comment]
@johnseekins Not yet, I think it's time to move on, let this problem go and do something worthy. 

I have turned into other tech for help instead of using `pyenv`.
