### ISSUE TITLE
python 2.7.12

### ISSUE THREAD

**Issue by zetan503** [yyuu/pyenv#721]
How do I get 2.7.12? Its not in the list

issue tracker: https://github.com/yyuu/pyenv/issues
[vagrant@local-v-test-nginxlb-01 ~]$ pyenv install --list
Available versions:
  2.4
  2.4.1
  2.4.2
  2.4.3
  2.4.4
  2.4.5
  2.4.6
  2.5
  2.5.1
  2.5.2
  2.5.3
  2.5.4
  2.5.5
  2.5.6
  2.6.6
  2.6.7
  2.6.8
  2.6.9
  2.7
  2.7.1
  2.7.2
  2.7.3
  2.7.4
  2.7.5
  2.7.6
  2.7-dev
  3.0.1
  3.1.3
  3.1.4
  3.1.5
  3.1-dev
  3.2
  3.2.1
  3.2.2
  3.2.3
  3.2.4
  3.2.5
  3.2-dev
  3.3.0
  3.3.1
  3.3.2
  3.3.3
  3.3.4
  3.3.5
  3.3-dev
  3.4.0
  3.4-dev
  anaconda-1.4.0
  anaconda-1.5.0
  anaconda-1.5.1
  anaconda-1.6.0
  anaconda-1.6.1
  anaconda-1.7.0
  anaconda-1.8.0
  anaconda-1.9.0
  anaconda-1.9.1
  anaconda-1.9.2
  ironpython-2.7.4
  ironpython-dev
  jython-2.5.0
  jython-2.5.1
  jython-2.5.2
  jython-2.5.3
  jython-2.5.4-rc1
  jython-2.5-dev
  jython-2.7-beta1
  jython-2.7-beta2
  jython-dev
  miniconda-2.2.2
  miniconda-3.0.0
  miniconda-3.0.4
  miniconda-3.0.5
  miniconda3-2.2.2
  miniconda-3.3.0
  miniconda3-3.0.0
  miniconda3-3.0.4
  miniconda3-3.0.5
  miniconda3-3.3.0
  miniconda3-3.4.2
  miniconda-3.4.2
  pypy-1.5
  pypy-1.5-src
  pypy-1.6
  pypy-1.7
  pypy-1.7-dev
  pypy-1.8
  pypy-1.8-dev
  pypy-1.9
  pypy-1.9-dev
  pypy-2.0
  pypy-2.0.1
  pypy-2.0.1-src
  pypy-2.0.2
  pypy-2.0.2-src
  pypy-2.0-dev
  pypy-2.0-src
  pypy-2.1
  pypy-2.1-src
  pypy-2.2
  pypy-2.2.1
  pypy-2.2.1-src
  pypy-2.2-src
  pypy-2.3
  pypy-2.3-src
  pypy3-2.1-beta1
  pypy3-2.1-beta1-src
  pypy3-dev
  pypy-dev
  stackless-2.7.2
  stackless-2.7.3
  stackless-2.7.4
  stackless-2.7.5
  stackless-2.7.6
  stackless-2.7-dev
  stackless-3.2.2
  stackless-3.2.5
  stackless-3.2-dev
  stackless-3.3.5
  stackless-3.3-dev
  stackless-dev

**Comment by Samureus** [comment]
@zetan503 Could you run `pyenv update` and check again? I see a lot of recent versions missing in that list.

**Comment by yyuu** [comment]
https://github.com/yyuu/pyenv/blob/v1.0.2/plugins/python-build/share/python-build/2.7.12
