### ISSUE TITLE
Pyenv only recognizes a single system python

### ISSUE THREAD

**Issue by elFua** [yyuu/pyenv#724]
**Description**
Pyenv only recognizes a single system-wide python version, whichever is currently the default, typically python2. Even though python3 is also installed system-wide it is not listed.

**Steps to reproduce the issue:**
1. Run `pyenv versions`.

**Actual result:**

```
# pyenv versions
* system (set by ~/.pyenv/version)
```

**Expected result:**

```
# pyenv versions
* system: Python 2.7.12 (/usr/bin/python)
* system: Python 3.5.2 (/usr/bin/python3)
```

**Additional information:**
By default there is no file named `~/.pyenv/version` and the docs do not elaborate on what the file must contain. Also `man pyenv` says there is no manual entry.

**Environment details:**
Tested on Ubuntu 16.04 and OSX 10.11.6
##

**Comment by DAZHANBA** [comment]
hey, have you solved that? Same issue occured to me.

**Comment by AlJohri** [comment]
hey @yyuu, just curious if this is a possibility? seems like a bit of a deviation from rbenv?

**Comment by AlJohri** [comment]
@DAZHANBA perhaps this may help https://github.com/doloopwhile/pyenv-register

**Comment by yyuu** [comment]
The "system" means "executables in PATH except puenv's". It cares nothing even if the system's "python" is a Jython ;p

**Comment by Jeklah** [comment]
I'm also having this issue.
