### ISSUE TITLE
pip3 causes ImportError: Entry point ('console_scripts', 'pip3') not found

### ISSUE THREAD

**Issue by keevee09** [yyuu/pyenv#739]
pip3 commands are failing lately.
System: Mac OS X El Capitan 10.11.6 with homebrew installed python3.5.2_3

```
tony@Macintosh:~$ pip3 list
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 9, in <module>
    load_entry_point('pip==8.1.2', 'console_scripts', 'pip3')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2568, in load_entry_point
    raise ImportError("Entry point %r not found" % ((group, name),))
ImportError: Entry point ('console_scripts', 'pip3') not found
```

I'm uncertain if this is a pyenv issue.

Tried: `$ brew uninstall python3 && brew install python3`
Tried: `$ /usr/local/Cellar/python3/3.5.2/bin/python -m pip -U --force-reinstall pip`

**Comment by keevee09** [comment]
... the solution:
`$ /usr/local/Cellar/python3/3.5.2_3/bin/python3 -m pip install --upgrade --force-reinstall pip`

`$ pip3 list` and other pip3 commands now work as expected.

**Comment by joshfriend** [comment]
TFW opening a github issue makes you immediately realize a solution to your problem...

**Comment by keevee09** [comment]
Yes. I feel suitably chagrined :)

**Comment by medington** [comment]
FYI, this appears to work for Python2 installed via Homebrew as well. In my case pip got busted when I upgraded from Python 2.7.13 to Python 2.7.14. I used this to fix it:

```/usr/local/Cellar/python/2.7.14/bin/python2 -m pip install --upgrade --force-reinstall pip```

**Comment by brianbrix** [comment]
sudo python3 -m pip install --upgrade --force-reinstall pip
