### ISSUE TITLE
pyenv raise an waring about sqlite3

### ISSUE THREAD

**Issue by JunoJunho** [yyuu/pyenv#742]
I got this message from the pyenv when I tried to install 3.5.2 using peen

```
Downloading Python-3.5.2.tar.xz...
-> https://www.python.org/ftp/python/3.5.2/Python-3.5.2.tar.xz
Installing Python-3.5.2...
WARNING: The Python sqlite3 extension was not compiled. Missing the SQLite3 lib?
Installed Python-3.5.2 to /Users/mypath/.pyenv/versions/3.5.2
```

I just worried about the warning, Did I need to something to do?
I have a plan to build a django application using this virtual environment.

Or

If there is an any issue related this one, please reference that issue because I couldn't find it.

**Comment by joshfriend** [comment]
Please see [the wiki](https://github.com/yyuu/pyenv/wiki/Common-build-problems).
