### ISSUE TITLE
pyenv cause bug in git shell tools

### ISSUE THREAD

**Issue by MikeDacre** [yyuu/pyenv#747]
I just submitted a bug to git, only to realized that the problem is pyenv.

When I try to run `git mergetool`, the code hangs indefinitely, I tried the following steps to debug it:

      export PATH=$(git --exec-path):$PATH
      sh -x $(which git-mergetool) --tool-help
    + USAGE='[--tool=tool] [--tool-help] [-y|--no-prompt|--prompt] [file to merge] ...'
    + SUBDIRECTORY_OK=Yes
    + NONGIT_OK=Yes
    + OPTIONS_SPEC=
    + TOOL_MODE=merge
    + . git-sh-setup
    ++ . git-sh-i18n
    +++ TEXTDOMAIN=git
    +++ export TEXTDOMAIN
    +++ test -z ''
    +++ TEXTDOMAINDIR=/usr/share/locale
    +++ export TEXTDOMAINDIR
    +++ GIT_INTERNAL_GETTEXT_SH_SCHEME=fallthrough
    +++ test -n ''
    +++ test -n ''
    +++ test -n ''
    +++ type gettext.sh
    +++ GIT_INTERNAL_GETTEXT_SH_SCHEME=gnu
    +++ export GIT_INTERNAL_GETTEXT_SH_SCHEME
    +++ case "$GIT_INTERNAL_GETTEXT_SH_SCHEME" in
    +++ . gettext.sh
    ++++ set -e
    ++++ '[' -n '' ']'
    ++++ program=git-mergetool
    ++++ [[ git-mergetool = \p\y\t\h\o\n* ]]
    ++++ export PYENV_ROOT=/home/dacre/.pyenv
    ++++ PYENV_ROOT=/home/dacre/.pyenv
    ++++ exec /home/dacre/.pyenv/libexec/pyenv exec git-mergetool --tool-help

So for some reason when running `git mergetool`, pyenv is being called to execute the command, and then hanging forever.

Any ideas why this could be?

**Comment by MikeDacre** [comment]
Does anyone know why exec is replaced by `exec /home/dacre/.pyenv/libexec/pyenv exec` and why this breaks git?

**Comment by MikeDacre** [comment]
In case it helps, if I set PYENV_DEBUG, the following lines are repeated forever to the shell:

https://gist.github.com/MikeDacre/4852ca4dc352a20200138db00bfdc3c3

**Comment by MikeDacre** [comment]
I have confirmed that this is an issue with one of the plugins. I erased pyenv completely and started again with the installer, I already installed all of my environments, and the git commands still work fine. My current plugins are:

    pyenv-doctor/  pyenv-installer/  pyenv-update/  pyenv-virtualenv/  pyenv-which-ext/  python-build/

My old ones were:

    pyenv-alias/  pyenv-default-packages/  pyenv-register/  pyenv-update/  pyenv-virtualenv/  pyenv-which-ext/  python-build/

I haven't narrowed which one causes the issue yet, I do know that adding the shims folder to the PATH was the part of the init that caused the problem to happen.

**Comment by joshfriend** [comment]
Closing since the issue was with a plugin and not pyenv itself. Please update if you figure out which plugin caused the issue.

**Comment by MikeDacre** [comment]
So it turns out this isn't an issue with the plugins, it is actually with the anaconda environment. I modify my anaconda environment, including installing a number of system packages (like gsl). Somewhere in that process, not sure where, the anaconda environment adds something to the shims that causes this bug, as well as a cluster of related bugs.

I am not sure how to figure out which shim is causing the issue, do any of you know how I can debug that?

**Comment by michaelmior** [comment]
I've seen a similar issue with `miniconda`. The gettext wrapper is broken in my case.
