### ISSUE TITLE
readline missing from CPython <3.6

### ISSUE THREAD

**Issue by brechtm** [yyuu/pyenv#756]
CPython versions installed by pyenv prior to 3.6 are missing the readline module. It is needed for tab completion to work in the REPL.

It is included with the 3.6.0b2 installed by pyenv and tab completion works. I'm on OS X El Capitan.

**Comment by yyuu** [comment]
pyenv will try installing readline if there's only corrupted libedit exists. Generally speaking rebuilding versions without readline should solve rhe issue

https://github.com/yyuu/pyenv/blob/master/plugins/python-build/bin/python-build#L1342
