### ISSUE TITLE
Cannot install python2.6

### ISSUE THREAD

**Issue by kelbyers** [yyuu/pyenv#759]
I'm sorry to keep opening this issue, but my questions are still not answered. (From #758).

I am not able to install any version of python 2.6 on my Mac, running 10.12.1, Sierra.

I have tried many times, with different versions (2.6.6, 2.6.7, 2.6.8, 2.6.9), and it always fails while trying to install pip.

Since the issue reported has to do with networking, I have tried on both my home network and my work network, and I have the issue in both places, and it doesn't matter if it is wi-fi or wired.

Is there any way to install a version of python using pyenv without installing pip? That seems to be nearly the last thing done, and I'd much rather debug getting pip installed with a working python that trying to debug when it fails and the already working python has been uninstalled by pyenv.

Is it possible to copy an install from another Mac? If so, what do I need to copy?

**Comment by yyuu** [comment]
Sometime you may need to apply extra patches to build 2.6 on recent systems. It's not possible to keep COython sources buildable on all systems.

**Comment by kelbyers** [comment]
I was not asking for you to keep python 2.6 buildable. I was asking if it was possible to copy an already built pyenv 2.6 from another mac. Again, you have closed my issue without even attempting to answer what my real question is.

**Comment by syddo** [comment]
I also cannot install Python2.6.6 on MacOS Catalina. The error is related to openssl.
has anyone seen this?

**Comment by kelbyers** [comment]
> I also cannot install Python2.6.6 on MacOS Catalina. The error is related to openssl.
> has anyone seen this?

It has been a long time since I tried to work with python 2.6.6 on my Mac. I ended up having to migrate my project to 2.7.

As I recall from my notes, there were two issues with Python 2.6. The first issue was when trying to create a new virtualenv using `pyenv virtualenv`. The issue here was that pyenv and the python install scripts automatically try to get the absolute latest version of pip when they create a new virtualenv. At the time I was working with it, any version after `pip==1.5.6` ran into errors with openssl. A workaround that worked for me as of November 2016 was to create the virtualenv without installing pip, then manually install pip into the virtualenv, disabling openssl checks. Once you get it installed that way, you can then use pip itself to update pip to a later version.

```
# create a virtualenv called VENV without installing pip
pyenv virtualenv 2.6.6 VENV --no-site-packages --no-pip --no-wheel --no-setuptools
# get pip installed
pyenv activate VENV
wget https://bootstrap.pypa.io/ez_setup.py --no-check-certificate -O - | \
    python easy_install pip==1.5.6
```

The other issue related to python 2.6.6 is related to openssl. The version of openssl that is available with the baseline MacOS does not work with python 2.6. You need to use openssl from homebrew. As of November 2016, again, here is what worked for me when installing packages using pip that needed to use openssl.

For example, updating the version of pip:
```
CFLAGS=-I$(brew --prefix openssl)/include LDFLAGS=-L$(brew --prefix openssl)/lib pip install -U pip setuptools
```

I have no idea if these suggestions will solve your issues, as I no longer have any version of python 2.6 available on a Mac.
