### ISSUE TITLE
 Failed to get version_info for python3.4: pyenv: python3.4: command not found

### ISSUE THREAD

**Issue by ssbarnea** [yyuu/pyenv#760]
I am trying to add 3 python versions to a Jenkins instance so I can run test with all of them. I installed pyenv for the jenkins user and also installed required versions
```
$pyenv versions
  system
  2.7.12
  3.4.5
* 3.5.2 (set by PYENV_VERSION environment variable)

$pyenv local
2.7.12
3.4.5
3.5.2
```

The problem is that if I try to run `python3.4` I get 
```
$ python3.4
pyenv: python3.4: command not found

The `python3.4' command exists in these Python versions:
  3.4.5
```

What do I need to do in order to assure that all command lines in the path are not broken:
```
python2.7 -V
python3.4 -V
python3.5 -V
```

So far the only one broken seems to be the 3.4 one.

**Comment by yyuu** [comment]
We are not doing any special things to 3.4. To check availability of a version, check the exit value of 'python -V' could be the easiest.

**Comment by v1v** [comment]
I've seen the same behaviour... 

``` bash
Downloading Python-3.4.3.tar.xz...
-> https://www.python.org/ftp/python/3.4.3/Python-3.4.3.tar.xz
Installing Python-3.4.3...
Installed Python-3.4.3 to /Volumes/jenkins/.pyenv/versions/3.4.3
pyenv global system 3.4.3 

pyenv versions
* system (set by /Volumes/jenkins/.pyenv/version)
  2.7.11
  3.4.3
  3.5.2
```

``` bash
sto-osx-tech11:~ midas$ python3.4 -V
pyenv: python3.4: command not found

The `python3.4' command exists in these Python versions:
  3.4.3
```

Any ideas?

**Comment by jgeerds** [comment]
Same here. Python 3.3 is also affected by this bug.
