### ISSUE TITLE
Can't override system python on OS X 

### ISSUE THREAD

**Issue by trueinviso** [yyuu/pyenv#769]
This is similar to #660 but I was unable to get any of their solutions to work.  I'm running macOS Sierra 10.12 and I have installed pyenv using homebrew and have installed python3.5.1.

```
pyenv versions
system
*  3.5.1 (set by /usr/local/var/pyenv/version)
```

```
python -V
Python 2.7.10
```

```
which python
/usr/bin/python
```

```
which pyenv
/usr/local/bin/pyenv
```

```
echo $PATH
/usr/local/var/pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/trueinviso/.rvm/bin
```

.zshrc contents:

```
export PYENV_ROOT="/usr/local/var/pyenv"
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
```

If I switch into my project directory and use .python-version file:

```
pyenv versions
  system
* 3.5.1 (set by /Users/trueinviso/project/pyramid-app/.python-version)
```

So it seems to be setting it correctly but it still says `Python 2.7.10` when I enter `python -V`.  My app seems to actually run fine with 3.5.1 but when I try to run the tests it is looking in 2.7.10 instead of 3.5.1 and blows up.  My understanding is that when I type python -V i should get the version that is set in pyenv?

**Comment by yyuu** [comment]
Looks weird. It seems shims path exists at the top of PATH appropriately. Can you verify if you actually have shim script at /usr/local/var/pyenv/shims/python? If there's no such script, running 'pyenv rehash' may help.

**Comment by Firemango** [comment]
I'm having a very similar, if not the same issue:

```
> pyenv versions
  system
* 3.5.1 (set by PYENV_VERSION environment variable)
------------------------------------------------------------
> python -V
Python 2.7.12
```

I do have a script at /usr/local/var/pyenv/shims/python, which when run manually starts python 3.5.1

**Comment by yyuu** [comment]
Generally speaking that's all users' shell configuration issue. pyenv's doing nothing special in shell's command look up. Review your shell configuration again and again and again

**Comment by trueinviso** [comment]
At /usr/local/var/pyenv/shims/ I have:

```
python3
python3-config
python3.5
python3.5-config
python3.5m
python3.5m-config
```

As you can see there is no python here.  `pyenv rehash` has no effect :(.

**Comment by trueinviso** [comment]
I'm new to python, so it looks like my problem was not realizing that to run python 3 from the command line I needed to use `python3` not `python`, doh!  Thanks for the help.

**Comment by joshfriend** [comment]
Thats not true, if python 3.5.2 is your active python version, the `python`, `python3`, and `python3.5` can all be used to invoke it.

**Comment by trueinviso** [comment]
Maybe not true, but there is no `python` script in my shims directory for some reason.

**Comment by prclibo** [comment]
I know this is outdated. But just met the similar issue in pyenv 1.2.9, OSX Mojave.
`~/.pyenv/shims` contains `python3` and `python3.6` but no `python`.

@trueinviso any progress on this problem?

**Comment by dlwalter** [comment]
I have the same issue on macOS 10.14.2 Mojave.  

```
➜  ~ pyenv versions
  system
  2.7.16
* 3.7.3 (set by /Users/dlw/.pyenv/version)

➜  ~ python --version
Python 2.7.10

```
➜  ~ which python
/usr/bin/python
```
```

**Comment by dlwalter** [comment]
fixed this by adding the following to my .zshrc:

```
export PATH="/Users/username/.pyenv:$PATH"
eval "$(pyenv init -)"
```

**Comment by RuleTheMoments** [comment]
@prclibo 
if you are using zsh, adding the following to '.zshrc', not '.zshenv'
`eval "$(pyenv init -)"`

**Comment by mayhd3** [comment]
some users may find it necessary to do `echo 'eval "$(pyenv init --path)"' >> ~/.zshrc` if the `python` command still runs 2.7
