### ISSUE TITLE
pyenv doesn't work with zsh

### ISSUE THREAD

**Issue by weishen** [yyuu/pyenv#773]
Hi,
I am a newbie to pyenv, I followed the installation instruction, but I could not start pyenv with zsh.
➜  ~ pyenv
env: bash: No such file or directory

➜  ~ zsh /root/.pyenv/bin/pyenv
env: bash: No such file or directory
/root/.pyenv/bin/pyenv:83: command not found: shopt

The installation is not clear how to work with zsh, please help, thanks in advance.

**Comment by yyuu** [comment]
pyenv requires bash in PATH to run. Just installing bash should solve.
