### ISSUE TITLE
pyenv command aliases

### ISSUE THREAD

**Issue by oscarmorrison** [yyuu/pyenv#776]
Would it be possible to have some common alias

`pyenv versions` -> `pyenv ls`

`pyenv global` -> `pyenv use`

etc. etc.

**Comment by yyuu** [comment]
pyenv itself don't support aliasing. If you really want to use alias, you can create some pyenv plugins or hook scripts to do so. See also wiki pages.

**Comment by ssbarnea** [comment]
I think that the aliases are an important enough feature to be included in core. 
Most people doing CI testing want to test against the lastest stable release of each python branch, without having to deal with the endless maintenance of minor versions files.

**Comment by oscarmorrison** [comment]
@yyuu I have updated my request, it was incorrectly edited.
Keen to know if this is something pyenv team would consider
