### ISSUE TITLE
pyenv shims are shadowing commands in the PATH

### ISSUE THREAD

**Issue by brechtm** [yyuu/pyenv#779]
If no pyenv env is activated, or if a command is not available in the active env, pyenv will output "command not found" even if there is a command with the same name in the PATH.

**Comment by Reafdaw** [comment]
This seems like a similar problem I reported here:
https://github.com/yyuu/pyenv/issues/772

Would be great if someone could figure out what is wrong here.

**Comment by yyuu** [comment]
It's all expected behavior. RTFM

**Comment by brechtm** [comment]
Which manual? README.md? I don't see it.

I don't think pyenv shims should output "command not found" if no env is activated and there is a command with the same name in PATH.

**Comment by Jeremias-Brand** [comment]
Apparently this plugin to pyenv solves the problem:
https://github.com/pyenv/pyenv-which-ext

I don't know of any manual. I would gladly read it if there is one. The readme is not very detailed.
