### ISSUE TITLE
How to install self-downloaded package?

### ISSUE THREAD

**Issue by melonCoder** [yyuu/pyenv#786]
For some reason, I just can't use ```pyenv install``` to download and install packages. So I downloaded a package from the website, and copy it to my working environment. 
- I directly installed the packages, but pyenv failed to recognize it as the output of ```pyenv versions``` remains the same. I tried the following solutions, but the problem still exists.
    - restart shell
    - ```pyenv rehash```
- At last, I solved this problem by hacking into ```python-build``` and told it to install my package. **But, does there exist an better solution which i failed to figure out for my problem?**

**Comment by yyuu** [comment]
pyenv doesn't care how Python installations in ${PYENV_ROOT} have been prepared. Any installation methond should work as long as you have directories at proper locations.

* 'pyenv versions' will only show installations found in ${PYENV_ROOT}/versions
 * https://github.com/yyuu/pyenv/blob/master/libexec/pyenv-versions#L110
* 'pyenv rehash' will generate shim scripts for all executables found in ${PYENV_ROOT}/versions/*/bin
  * https://github.com/yyuu/pyenv/blob/master/libexec/pyenv-versions#L110

**Comment by melonCoder** [comment]
Well, I see. Thanks for your kindness. And everything goes well if i install python in ${PYENV_ROOT}.

**But my point is: is it necessary to support installation of local packages with pyenv?**
As far as i see, using command like ```pyenv install Python-3.6.0rc2.tar.xz``` to install local packages seems more user friendly.
