### ISSUE TITLE
pyenv shell can't work each time i restart shell

### ISSUE THREAD

**Issue by CropCircles** [yyuu/pyenv#791]
I am using bash
all the other command works fine except pyenv shell
![image](https://cloud.githubusercontent.com/assets/12696298/21527649/9976eff6-cd67-11e6-9bff-307b7e2dc5d4.png)

![image](https://cloud.githubusercontent.com/assets/12696298/21527684/cb2e5d90-cd67-11e6-887f-e8f970fa0712.png)

if i restart shell, then
![image](https://cloud.githubusercontent.com/assets/12696298/21527704/e9157d8e-cd67-11e6-9ee9-042398da62b8.png)

**Comment by andyyoung01** [comment]
If you are using bash, maybe you should also add the content of ~/.zshenv into ~/.bashrc or ~/.bash_profile.
