### ISSUE TITLE
Python / Jython conflict

### ISSUE THREAD

**Issue by gobadiah** [yyuu/pyenv#800]
There is a conflict when installing `jython-2.7.0` and python `2.7.12` using pyenv.

When installing both, jython becomes unusable. Here is a Dockerfile to reproduce : 

```
FROM python:2.7.12

RUN apt-get update
RUN apt-get install -y unzip openjdk-7-jdk
RUN git clone git://github.com/yyuu/pyenv.git /root/.pyenv
ENV PYENV_ROOT /root/.pyenv
ENV PATH $PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
RUN pyenv install jython-2.7.0
RUN PYENV_VERSION=jython-2.7.0 pip --version
RUN pyenv install 2.7.12
RUN PYENV_VERSION=jython-2.7.0 pip --version
```

last command expected result : 
`pip 1.6.dev1 from /root/.pyenv/versions/jython-2.7.0/Lib/site-packages (python 2.7)`

Actual result : 
```
pyenv: python2.7: command not found

The `python2.7' command exists in these Python versions:
  2.7.12
```

If you run this docker container with `/bin/bash` (you need to remove the last line in the Dockerfile for the build to succeed), you can see that uninstalling `2.7.12` with `pyenv uninstall -f 2.7.12` makes `pip` work again.

**Comment by yyuu** [comment]
Umm. Is pip generating executable with shebang line as python2.7 on jython...? Will check later.

**Comment by yyuu** [comment]
It seems that `jython` executable is generated with `python2.7` in shebang. This file must be generated by Jython's installer. Actually pyenv isn't doing anything for it.

```
root@4ca652f34cdc:~# head -1 ~/.pyenv/versions/jython-2.7.0/bin/*
==> /root/.pyenv/versions/jython-2.7.0/bin/easy_install <==
#!/usr/bin/env /root/.pyenv/versions/jython-2.7.0/bin/jython

==> /root/.pyenv/versions/jython-2.7.0/bin/easy_install-2.7 <==
#!/usr/bin/env /root/.pyenv/versions/jython-2.7.0/bin/jython

==> /root/.pyenv/versions/jython-2.7.0/bin/jython <==
#!/usr/bin/env python2.7

==> /root/.pyenv/versions/jython-2.7.0/bin/pip <==
#!/usr/bin/env /root/.pyenv/versions/jython-2.7.0/bin/jython

==> /root/.pyenv/versions/jython-2.7.0/bin/pip2 <==
#!/usr/bin/env /root/.pyenv/versions/jython-2.7.0/bin/jython

==> /root/.pyenv/versions/jython-2.7.0/bin/pip2.7 <==
#!/usr/bin/env /root/.pyenv/versions/jython-2.7.0/bin/jython

==> /root/.pyenv/versions/jython-2.7.0/bin/python <==
#!/usr/bin/env python2.7
```

**Comment by gobadiah** [comment]
Thanks @yyuu for looking that up. 

So if I understand correctly, when `python` is only installed system wide, `jython` shebang use it without any error, and when a `python` is installed with `pyenv`, `pyenv` finds it in (in a different shim) and ask to use this one ?

Is there an easy workaround to this ? Right now, what I'm doing is using the global `python` and `pyenv` for `jython`, but ideally I would really prefer using `pyenv` for both.

**Comment by yyuu** [comment]
In the `python:2.7.12` container (based on Debian 8; jessie), `jython` executable is generated as a Python script.

```
root@4ca652f34cdc:~# cat /etc/issue
Debian GNU/Linux 8 \n \l

root@4ca652f34cdc:~# file /root/.pyenv/versions/jython-2.7.0/bin/jython
/root/.pyenv/versions/jython-2.7.0/bin/jython: Python script, ASCII text executable
```

Unlike on jessie, the script is installed as a shell script on my Debian sid box.

```sh
% cat /etc/issue
Debian GNU/Linux stretch/sid \n \l

% file ~/.pyenv/versions/jython-2.7.0/bin/jython
/home/yyuu/.pyenv/versions/jython-2.7.0/bin/jython: Bourne-Again shell script, ASCII text executable
```

It seems that Jython installer will generate `jython` executable as Python script if `python2.7` is available when installing Jython. I'm usually using 3.5 and it's the reason why my `jython` executable was created as a shell script. I'll try to prepare some workaround in `python-build` script....

**Comment by gobadiah** [comment]
Okay I get it, well thanks a lot for the explanation, I'll monitor this issue for a possible "fix".

**Comment by yyuu** [comment]
@gobadiah I believe #801 should solve the issue. Please let me know if you still have some trouble with Jython 2.7+.

**Comment by gobadiah** [comment]
Just tried it, it works with my small `Dockerfile`. I'll let you know if it comes up in a real world project, but I suspect that was it. 

Thanks again, that was awesome on your part.
