### ISSUE TITLE
It seems PYTHON_BUILD_MIRROR_URL environment variable doesn't work

### ISSUE THREAD

**Issue by andyyoung01** [yyuu/pyenv#803]
I installed pyenv through pyenv-installer according [README.rst](https://github.com/yyuu/pyenv-installer/blob/master/README.rst). Then I wanted to install Python-2.7.7 using pyenv, but the network was so slow. 
So I used [the pyenv's official mirror of Python archives](http://yyuu.github.io/pythons/) to download Python archives. I followed the instruction of the page, using command like this:
```bash
$ export PYTHON_BUILD_MIRROR_URL="http://mirrors.sohu.com/python/"
$ pyenv install -v 2.7.7
/tmp/python-build.20170111175043.4891 ~/.pyenv
Downloading Python-2.7.7.tar.xz...
-> https://www.python.org/ftp/python/2.7.7/Python-2.7.7.tar.xz
^Cerror: failed to download Python-2.7.7.tar.xz

BUILD FAILED (CentOS Linux 7 using python-build 20160602)

```
According to the output of the command, pyenv still download the archive from official website. So I cancelled the download with Ctrl-C. Was there any mistake of my configuration?
My computer's environment was like this:
```bash
$ uname -a
Linux centos7 4.5.2 #2 SMP Wed May 4 20:00:06 CST 2016 x86_64 x86_64 x86_64 GNU/Linux
$ pyenv --version
pyenv 1.0.6
```
I also tried other version of pyenv:
```
$ cd $HOME/.pyenv  
$ git fetch --tags
$ git checkout v20160726 
```
And opened a new terminal, issued the same command to install Python-2.7.7. It seems that pyenv still download archives from python official website. How can I change that?

**Comment by seozed** [comment]
Look here!
http://www.tuicool.com/articles/jAFzYrV

**Comment by andyyoung01** [comment]
@seozed Thanks!
I also found the document about "Package download mirrors" at [here](https://github.com/yyuu/pyenv/tree/master/plugins/python-build). It describe that "Package mirror URLs are constructed by joining this variable with the SHA2 checksum of the package file."

**Comment by yyuu** [comment]
I hope everything worked now. I guess that the problem was incorrect file naming on mirror site.

**Comment by ilovemysillybanana** [comment]
Can someone provide a walk through on how to do this? I'm trying to set this up now but that website linked by @seozed does not load for me.

**Comment by leafonsword** [comment]
@seozed this method still not work : http://www.tuicool.com/articles/jAFzYrV

**Comment by Reapor-Yurnero** [comment]
> @seozed this method still not work : http://www.tuicool.com/articles/jAFzYrV

The post did not mention that the filename must be the md5 hash of the compressed file. If you look at the request history of your local host http service, you are likely to find a 404 request with the target md5.

**Comment by zgj1024** [comment]
> 
> 
> @seozed this method still not work : http://www.tuicool.com/articles/jAFzYrV

you can use this way http://localhost:4000/2020/12/06/fix-pyenv-set-mirror-incorrect/

```
export PYTHON_BUILD_MIRROR_URL_SKIP_CHECKSUM=1
export PYTHON_BUILD_MIRROR_URL="https://npm.taobao.org/mirrors/python/"
```

**Comment by tsdrm** [comment]
> > @seozed this method still not work : http://www.tuicool.com/articles/jAFzYrV
> 
> you can use this way https://www.zhangguojian.com/2020/12/06/fix-pyenv-set-mirror-incorrect/
> 
> ```
> export PYTHON_BUILD_MIRROR_URL_SKIP_CHECKSUM=1
> export PYTHON_BUILD_MIRROR_URL="https://npm.taobao.org/mirrors/python/"
> ```

thx, It works for me.
