### ISSUE TITLE
Calling rehash is required after installing new python version

### ISSUE THREAD

**Issue by dangitall** [yyuu/pyenv#805]
I'm running on OS X and am observing that calling rehash is required 100% of the time after a new version of Python is installed with pyenv. My impression is that shouldn't be needed. Is this expected behavior?

    $ python -V
    Python 2.7.13
    $ pyenv install 3.6.0
    Installing Python-3.6.0...
    Installed Python-3.6.0 to /Users/dan/.pyenv/versions/3.6.0

    $ pyenv global 3.6.0
    $ python -V
    Python 2.7.13
    $ pyenv rehash
    $ python -V
    Python 3.6.0

I see a similar issue after uninstalling a version. This is run immediately after the above commands:

    $ pyenv uninstall 3.6.0
    pyenv: remove /Users/dan/.pyenv/versions/3.6.0? y
    $ python -V
    bash: /Users/dan/.pyenv/shims/python: No such file or directory
    $ pyenv versions
    pyenv: version `3.6.0' is not installed (set by /Users/dan/.pyenv/version)
      system
    $ pyenv rehash
    $ python -V
    Python 2.7.13

**Comment by yyuu** [comment]
Both install/uninstall are implemented to call `pyenv-rehash` automatically.

https://github.com/yyuu/pyenv/blob/v1.0.6/plugins/python-build/bin/pyenv-install#L276
https://github.com/yyuu/pyenv/blob/v1.0.6/plugins/python-build/bin/pyenv-uninstall#L83

**Comment by dangitall** [comment]
Yeah, I see that but it didn't really help me in the case above. Maybe it would make sense to do it any time the environment changes?
