### ISSUE TITLE
cronjob is using wrong version of Python

### ISSUE THREAD

**Issue by SamusAranX** [yyuu/pyenv#809]
I just installed pyenv on my server running Debian 8, then installed Python 3.6.0 and made it the default using `pyenv global 3.6.0`.

In a shell, `python3` will now open Python 3.6.0, as intended, but cron apparently gets the *actual* system default, which seems to be some ancient form of Python 3.4.2.

How do I get cron to use the correct version of Python?

**Comment by BanzaiMan** [comment]
`cron` sets its own `$PATH`. Read the `man` page, learn the tool. This is not a `pyrnv` issue.
