### ISSUE TITLE
Provide reason for note about using .bashrc instead .bash_profile on Ubuntu/Fedora

### ISSUE THREAD

**Issue by piotr-dobrogost** [yyuu/pyenv#810]
At https://github.com/yyuu/pyenv in _Installation/Basic GitHub Checkout_ section there's the following note:
> Ubuntu and Fedora note: Modify your `~/.bashrc` file instead of `~/.bash_profile`.

I would like to know what's the reason for this? I think this note should be expanded with this information.

**Comment by yyuu** [comment]
issue tracker is not question forum

**Comment by piotr-dobrogost** [comment]
This is issue raised against documentation...
