### ISSUE TITLE
'no such command' in my mac,how to find/fix the problem

### ISSUE THREAD

**Issue by ken0709** [yyuu/pyenv#813]
hi,
i install the pyenv, and run it, it's very ok, while i change the dictory(cd ..) ,and run it , it give me some texts;
![screen shot 2017-01-20 at 7 35 18 pm](https://cloud.githubusercontent.com/assets/13581655/22148400/d7617c12-df48-11e6-8ca0-c9929cdfc581.png)
![screen shot 2017-01-20 at 7 36 00 pm](https://cloud.githubusercontent.com/assets/13581655/22148411/e31ad792-df48-11e6-8caa-85694cd81d3d.png)
![screen shot 2017-01-20 at 7 36 16 pm](https://cloud.githubusercontent.com/assets/13581655/22148415/ec5f8ea6-df48-11e6-9aef-46a321cff57f.png)

and the .zshenv 
![screen shot 2017-01-20 at 7 46 18 pm](https://cloud.githubusercontent.com/assets/13581655/22148456/27277454-df49-11e6-8a88-d76d230cfa4c.png)

how can i do the next ?
thanks very much

**Comment by jacebrowning** [comment]
`pyenv` is not used to run scripts directly.

Install a version of python:

```
pyenv install 3.6.0
```

Make that the global version:

```
pyenv global 3.6.0
```

Run your script with `python`:

```
python ex01.py
```

**Comment by ken0709** [comment]
i see, i work fine, thank you @jacebrowning
