### ISSUE TITLE
pyenv puts incorrect path in shims with Homebrew

### ISSUE THREAD

**Issue by sr105** [yyuu/pyenv#816]
`eval "$(pyenv init -)"` installs shims if they're missing.

It appears to use the real absolute path of pyenv which is problematic when `brew upgrade` upgrades the pyenv version. It should use the symlink `/usr/local/bin/pyenv`.

```
$ which pyenv
/usr/local/bin/pyenv
$ readlink $(which pyenv)
../Cellar/pyenv/1.0.6/bin/pyenv
$ tail -n 1 ~/.pyenv/shims/python
exec "/usr/local/Cellar/pyenv/1.0.6/libexec/pyenv" exec "$program" "$@"
```

**Comment by cmcginty** [comment]
If you run `pyenv rehash` does it fix your shims?

**Comment by yyuu** [comment]
pyenv won't manage user's PATH except the n pyenv-init. Please take a look on README and review your shell configurations.

**Comment by sr105** [comment]
So I should fix this bug myself...? There's nothing wrong with my shell setup. `pyenv-init` shouldn't be using the realpath of pyenv.

**Comment by sr105** [comment]
Missed the `rehash` question....  It doesn't fix it. `rehash` doesn't overwrite the shims if they already exist. I tested that.

**Comment by BenjamenMeyer** [comment]
Same issue - ran `brew upgrade` and ran into this. Environmnent seems to be correct, and `pyenv rehash` does *not* solve the issue.

**Comment by em1208** [comment]
I did `brew upgrade` to version 1.2.14_1 and ran into the same issue but `pyenv rehash` fixed it for me.

**Comment by sr105** [comment]
I just upgraded to 1.2.14_1. Even though, the shim didn't change right after the upgrade, it did change with a minute, so brew must be scheduling a task to update the file.

```
==> Pouring pyenv-1.2.14_1.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/pyenv/1.2.14_1: 656 files, 2.4MB
Removing: /usr/local/Cellar/pyenv/1.2.13_1... (650 files, 2.4MB)
Removing: /Users/hchapman/Library/Caches/Homebrew/pyenv--1.2.13_1.mojave.bottle.tar.gz... (625.3KB)
Harvey:shims hchapman$ tail -n1 python
exec "/usr/local/Cellar/pyenv/1.2.13_1/libexec/pyenv" exec "$program" "$@"
Harvey:shims hchapman$ tail -n1 ipython
exec "/usr/local/Cellar/pyenv/1.2.14_1/libexec/pyenv" exec "$program" "$@"
Harvey:shims hchapman$ tail -n1 python
exec "/usr/local/Cellar/pyenv/1.2.14_1/libexec/pyenv" exec "$program" "$@"
```

**Comment by hectorpal** [comment]
`pyenv rehash` just worked for me when went from `1.2.19` to `1.2.20`.

**Comment by aakashbasa** [comment]
`pyenv rehash` fixed it for me. 😀
