### ISSUE TITLE
Install pyenv for all users in the server

### ISSUE THREAD

**Issue by mnach** [yyuu/pyenv#820]
Hi folks,

May be my question is silly, but.. 
Is it possible to:
1 install pyenv to the system directory, for example /usr/share/pyenv or /opt/pyenv
2 configure it to give users from pyenv group rights to install/update/uninstall pythons and all other users execute existing ones
3 Install pyenv-virtualenv in "per-user mode": Each user can create virtualenv and no one else can see it

This way will saves disk space and time for compilation(no need to have two pythons with the same version for each user), without any loss. 
I would prefer to have this configuration on the server with multiple python projects. Each project deployed in his own user, and executed in his own virtualenv.
This configuration is worthy of attention or not?

**Comment by yyuu** [comment]
That's all about Unix's file permissionissues. If you'd like to configure so, try setting setgid and/or sticky bit on installation path.

**Comment by matt3o** [comment]
I had the same thought but ran into the issues mentioned above. After reading the reply and trying out a few things I am down to setting file permission per folder but this doesn't seem right. 
Thus would you care to explain how exactly you would set setgid and the sticky bit and on what folders?

**Comment by itsthejoker** [comment]
Also seeking clarification on this, as it's relevant to a project I'm trying to deploy.

**Comment by espoelstra** [comment]
I think a good option if you want to cut down on duplication would be to install one or many versions of Python globally using `python-build` or if you really want/need Pyenv, `$(pyenv which python-build)` and if you supply the `/usr/local/` prefix it will put the Python binaries in the `/usr/local/bin/` folder which should allow any user to execute python3.x but not change it. 

Then you should have them install a copy of pyenv in their own home directories and they can use it to choose between any of the globally installed Python versions that you want to support (Python2.7/3.6/3.7/3.8) or they could install their own copy of a specific patch release or a testing version. This way if they are using a virtualenv properly they can pick from any of the installed versions without everybody having separate copies of say 3.7, and pyenv virtualenv (or python3 -m venv) can use the "system" python to set up a virtualenv and manage packages on a per user basis.

**Comment by elgalu** [comment]
Someone created https://github.com/macdub/pyenv-multiuser

**Comment by normanius** [comment]
@yyuu The reasoning for closing this issue is not complete. In my view, this is not just a matter of adjusting setgid or the sticky bit.

Referring to point 3 of the initial post: `pyenv-virtualenv` does _not_ support a "per-user mode". At least I don't see how.

If a user (that is not in the pyenv group) tries to create a virtual environment, this will fail because the `env` folder cannot be created.

```bash
# Normal user (not in group pyenv)
pyenv virtualenv 3.6.15 my-new-env

# Error: [Errno 13] Permission denied: 'PYENV_ROOT/versions/3.6.15/envs/my-new-env'
# mkdir: cannot create directory ‘PYENV_ROOT/versions/3.6.15/envs/my-new-env’: Permission denied
```

Also, when a new environment is created, `pyenv-virtualenv` will try to create a link in `$PYENV_ROOT/versions`, for which a normal user (that is not supposed to mess up the pyenv's Python installations) does not have permissions. Changing the group permissions for `$PYENV_ROOT/versions` of normal users does not make sense, because it can have side-effects not limited to pyenv-virtualenv but to pyenv overall.

**Comment by CEOSPFUTURE2** [comment]
Hello . I's this email meant for me ?

**Comment by aromatic-toast** [comment]
ah gotcha! Yes, I see that `pyenv` needs to be installed for multiple user access. I'll need to set that up later but as a quick fix for now let's see if this will fix it:

Copy/paste the following into your `.bashrc`  file located in your home directory: 
```
export PYENV_ROOT="/home/lesleymi/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
```

then 
```
source .bashrc
```

Then try again: 
```
pyenv virtualenvs
```
