### ISSUE TITLE
Pyenv not working on Sierra?

### ISSUE THREAD

**Issue by millerf** [yyuu/pyenv#821]
```
Fabiens-MacBook-Pro:Documents millerf$ pyenv global
3.4.0
Fabiens-MacBook-Pro:Documents millerf$ pyenv local
3.4.0
Fabiens-MacBook-Pro:Documents millerf$ python --version
Python 2.7.13

```
Not sure what to do... I am on mac sierra (10.12.2)
Just installed pyenv from homebrew (updated)

**Comment by millerf** [comment]
For info...

```
Book-Pro:Documents millerf$ pyenv --version
pyenv 1.0.7

```

**Comment by yyuu** [comment]
Check your shell config

**Comment by millerf** [comment]
what does that mean? I also tried pyenv shell and it is saying the command doesn't exist...

**Comment by codyli520** [comment]
I have the same issue

**Comment by programmist** [comment]
Same issue here. Followed all instructions and pyenv insists 3.6.0 is the current version, but running `python -V` shows 2.7.10.

**Comment by matinfo** [comment]
Solution - Add to your shell (~/.bashrc or ~/.zshrc) : 

```
export PATH="/Users/<username>/.pyenv:$PATH"
eval "$(pyenv init -)"
```

Remplace _<username>_ by your MacBook user.
Refresh your terminal env, example: $ source ~/.zshrc  (or restart your terminal)

**Comment by felipemrodrigues** [comment]
@matinfo really solved here. ty :)

**Comment by AgileTrossDev** [comment]
I have this issue too.   Had to manually add

export PATH="/Users/username/.pyenv:$PATH"
eval "$(pyenv init -)"

**Comment by mgfjxxiexiaolong** [comment]
@matinfo really solved too. Notice that, put
```
export PATH="/Users/username/.pyenv:$PATH"
eval "$(pyenv init -)"
```
under the python path setting, eg: 
```
# Setting PATH for Python 2.7
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
export PATH
```

**Comment by hartleybrody** [comment]
I was having this issue as well, where `pyenv local` was telling me one version and `python --version` was telling me something else. Eventually I figured out it was due to a pyenv plugin I was using.

If you're using the [pyenv-virtualenv](https://github.com/pyenv/pyenv-virtualenv) plugin, you'll need to specify the python version you want to use when you create the virtualenv.

So instead of using 

pyenv virtualenv my_virtualenv

You'll need to use

pyenv virtualenv 3.6.2 my_virtualenv

I had to blow away my current virtualenv and create a new one like that for it to correctly load the right python version.

**Comment by gloryVine** [comment]
@matinfo 

> Solution - Add to your shell (~/.bashrc or ~/.zshrc) :
> 
> ```
> export PATH="/Users/username/.pyenv:$PATH"
> eval "$(pyenv init -)"
> ```
> Remplace _username_ by your MacBook user.
> Refresh your terminal env, example: $ source ~/.zshrc (or restart your terminal)

While this results in the correct local version of Python, it messes up the system python on mac:
$python3 -V gives the correct version but
$python -V results in 'no such file or directory', whereas it should normally link to Mac's system python 2.7. Why is that? I'm scared it will screw my system up

**Comment by matinfo** [comment]
@gloryVine to use your Python 2.7 you need to use `python2.7` cmd.

**Comment by kirankotari** [comment]
> Solution - Add to your shell (~/.bashrc or ~/.zshrc) :
> 
> ```
> export PATH="/Users/username/.pyenv:$PATH"
> eval "$(pyenv init -)"
> ```
> Remplace _username_ by your MacBook user.
> Refresh your terminal env, example: $ source ~/.zshrc (or restart your terminal)

For people who are using fish shell:
```
set PYENV_ROOT $HOME/.pyenv
set -x PATH $PYENV_ROOT/shims $PYENV_ROOT/versions $PATH
pyenv rehash
```

**Comment by gloryVine** [comment]
> @gloryVine to use your Python 2.7 you need to use `python2.7` cmd. And `python -V` on my MacBook return the Python 3 version.

My questions is does OSX still understand where to find its system python after this change.
