### ISSUE TITLE
Last pyenv merge is breaking virtual environment installation on Travis-ci

### ISSUE THREAD

**Issue by lmctv** [yyuu/pyenv#822]
I've just proposed pyca/pynacl#241 as a solution to breaking installations of cpython virtual environments, which fail with an error like:

```
[...]/.tox/py33/bin/python3.3: error while loading shared libraries: libpython3.3m.so.1.0: cannot open shared object file: No such file or directory
ERROR: The executable [...]/.tox/py33/bin/python3.3 is not functioning
ERROR: It thinks sys.prefix is '[...]/.tox' (should be '[...]/.tox/py33')
ERROR: virtualenv is not compatible with this system or executable
```

You can find an example at https://travis-ci.org/lmctv/pynacl/jobs/196112043

**Comment by yyuu** [comment]
You mean #819 is problematic? Honestly speaking I didn't test with virutalenv after merging it.

**Comment by yyuu** [comment]
Just in case, I reverted the changes from master once. Will try investigating later.

**Comment by yyuu** [comment]
Already reverted from master
