### ISSUE TITLE
pyenv with python32 bit on Arch linux 64 bit

### ISSUE THREAD

**Issue by dummys** [yyuu/pyenv#829]
Hi,

Do you have a documentation in order to install python2-32bit with pyenv on Arch linux or on any flavor of linux ?
thanks

**Comment by dummys** [comment]
someone is listening to issue here ?

**Comment by yyuu** [comment]
32bit build is a kind of feature of CPython `./configure` and pyenv will NOT take care nothing about it. I guess the configurations like follows will just work.

```
% env CFLAGS="-m32" LDFLAGS="-m32" pyenv install 2.7.13
```

**Comment by yyuu** [comment]
no responce

**Comment by dummys** [comment]
sorry, i'm testing it right now

**Comment by dummys** [comment]
@yyuu I tested the 32bit install and it seems to work. In order to use it for IDA pro I need the following library: libpython2.7.so.1.0
Where does pyenv store this files ? I checked everywhere here: ~/.pyenv/versions/2.7.13

**Comment by dummys** [comment]
@yyuu Hi again, quick question. How is it possible to have python 2.7.13 32bit and python 2.7.13 64bit on the same computer ?
Let me explain my need, normaly to not dirt my system install I used mkvirtualenv -p python2 or python3 depend of which version I want to use.
Now with pyenv + pyenv-virtualenv + pyenv-wirtualenvwrapper:

How can i do the same ? How to differ between 32/64 bit python because they will have the same name versions/2.7.13 ?
So as I understand now with pyenv when I do mkvirtualenv I get pyenv to use pyenv-virtualenv to create my venv.
