### ISSUE TITLE
Pyenv - virtualenv -- urllib.request no module

### ISSUE THREAD

**Issue by BLCKPSTV** [yyuu/pyenv#830]
I've succesfully installed pyenv and virtualenv. Pyenv versions give me both 2.7.5 and 3.5.0.

When using pyenv global 3.5.0 and using following script. 
`import urllib.request
import time
from bs4 import BeautifulSoup

newstext = urllib.request.Request('http://www.guardian.co.uk/')
resp = urllib.request.urlopen(newstext)
respData = resp.read()
soup = BeautifulSoup(respData, 'html.parser')

displayText = []

i = 0

for interesting in soup.findAll(class_='js-headline-text'):displayText.append(interesting.text)
msg = osc_message_builder.OscMessageBuilder(address="/headlines")
msg.add_arg(displayText[i])
msg = msg.build()
client.send(msg)
i += 1
time.sleep(.5)`

I get following error. 

File "testosc.py", line 19, in <module>
    import urllib.request
ImportError: No module named request

**Comment by thomasjo** [comment]
I'm going to assume you're running the script via `python testosc.py`; what is the output of `python -V`?
Judging from the error you are definitely not running the script using Python 3.5.0 like you think you are.

**Comment by BLCKPSTV** [comment]
I'm doing workon cv followed by virtualenv --version = 15.1.0 , then pyenv version = 3.5.0 (set by /Users/username/.python-version) 
When python -v 

installing zipimport hook
import zipimport # builtin
# installed zipimport hook

.....
.....


But everything shows python 2.7 directories, in the cv environment?

**Comment by yyuu** [comment]
Kind of basic usage issue. Not a problem in pyenv.
