### ISSUE TITLE
sha256sum --quiet invalid usage

### ISSUE THREAD

**Issue by parkerd** [yyuu/pyenv#840]
`compute_sha2` calls `sha256sum --quiet` which prints the following error during `pyenv install <version>` on Linux:

```
sha256sum: the --quiet option is meaningful only when verifying checksums
Try 'sha256sum --help' for more information.
```

Unfortunately, this doesn't cause the install to fail, instead the checksum is skipped and the install proceeds. Simple fix is to replace `sha256sum --quiet` with `sha256sum | awk '{print $1}'` or similar.

**Comment by yyuu** [comment]
What platform are you using?

**Comment by parkerd** [comment]
This is on Linux, confirmed on both CentOS 7.2 and Ubuntu 16.04.

You can also see the error in output other users have posted for other issues, but they didn't report this specifically as an issue.

**Comment by yyuu** [comment]
Hmm. It seems it came from ruby-build.

https://github.com/rbenv/ruby-build/blob/5d62e84c7b59cc3e44c7b83063613a258e1cdf10/bin/ruby-build#L227

Honestly speaking, I've never realized this since it's 3rd option to compute SHA256. Anyway it'd be better to be fixed.
