### ISSUE TITLE
No such command: `shell`

### ISSUE THREAD

**Issue by lukesneeringer** [yyuu/pyenv#842]
For whatever reason, I get

```$ pyenv shell 3.6.0
pyenv: no such command `shell'
```

Installed on Ubuntu using LinuxBrew.

Note that `pyenv help shell` works.

**Comment by yyuu** [comment]
It just mean your shell isn't loading pyenv function properly. Please follow installation instruction. For typical cases, restarting shell could work.

https://github.com/yyuu/pyenv/tree/ad8f2886aecd7226225c567e5a04c770b70d69b1#installation

**Comment by lukesneeringer** [comment]
Really? All the _other_ commands work...why would that one be different?
(I double checked the instructions; they are done.)

**Comment by okor** [comment]
@lukesneeringer You probably just need to run `echo 'eval "$(pyenv init -)"' >> ~/.bash_profile`

Worth noting that on my system, homebrew did NOT print that detail in the caveats as mentioned in the install instructions. Could just be me but it's an easy miss.

> After installation, you'll need to add eval "$(pyenv init -)" to your profile (**as stated in the caveats displayed by Homebrew — to display them again, use brew info pyenv**). You only need to add that to your profile once.

```
 ~ $ brew info pyenv
pyenv: stable 1.0.8, HEAD
Python version management
https://github.com/yyuu/pyenv
/usr/local/Cellar/pyenv/1.0.8 (548 files, 2.2M) *
  Built from source on 2017-03-03 at 09:59:26
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/pyenv.rb
==> Dependencies
Recommended: autoconf ✔, pkg-config ✔, openssl ✔, readline ✔
==> Options
--without-autoconf
	Build without autoconf support
--without-openssl
	Build without openssl support
--without-pkg-config
	Build without pkg-config support
--without-readline
	Build without readline support
--HEAD
	Install HEAD version
```
