### ISSUE TITLE
Symlinking the active bin

### ISSUE THREAD

**Issue by 3rd3** [yyuu/pyenv#848]
Is there a way to always have the respective `$HOME/.pyenv/versions/$VERSION/bin` to be symlinked to a canonical directory which one could add to the $PATH variable? Or is it preferred to add these paths for each Python version manually?

**Comment by joshfriend** [comment]
You may not have finished setup completely. pyenv does what you are describing already with its [shims directory](https://github.com/yyuu/pyenv#understanding-shims). You do have to make sure that this is [set up correctly though](https://github.com/yyuu/pyenv#installation).

If you installed from homebrew, it is easy to miss these instructions (which print out to the "caveats" section after the install finishes)

**Comment by 3rd3** [comment]
I think I've done all of that.

For now I've solved it by adding ´export PATH="$(pyenv prefix)/bin:$PATH"´ to `.zshenv`. Is that the correct way of doing it?

**Comment by joshfriend** [comment]
no, you should use the output of `pyenv root` to build the `$PATH`, e.g.

```bash
export PATH="$(pyenv root)/bin:$PATH"
# Also very important:
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
```

**Comment by 3rd3** [comment]
The problem seems to be that `$(pyenv root)/bin` does not exist. The `.pyenv` directory only contains `shims` and `versions` as sub-directories.

**Comment by 3rd3** [comment]
Perhaps this issue should be re-opened.
